In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv(r"D:\Sociometrik\rent prediction\raw files\DataOnHexgridFor(5)cities_comb.csv")

In [4]:
df.head()

,hexid08,t_name,locality,green_space_density,public_infrastructure_index,road_length,transportation_hubs,daily_avg_footfall,total_digital_consumers,pop_density_per_sqm,...,home_specialty_store,office_supply_services_store,petrol_gasoline_station,shopping,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price
0,883cf28945fffff,Kolkata,Sinthi,0.086059,6.84,26367.10879,5,119,3982,0.056038,...,5,0,0,0,0,0,1,0,0,13.491124
1,883cf28949fffff,Kolkata,Baranagar,0.169749,4.10,21240.03259,0,111,3725,0.037358,...,1,0,0,0,0,0,0,0,0,10.000000
2,883cf2894dfffff,Kolkata,Baranagar,0.311278,0.37,20571.44863,0,105,3403,0.030660,...,1,0,0,0,0,0,0,0,0,10.575139
3,883cf28961fffff,Kolkata,Paikpara,0.232866,11.60,20129.57346,0,101,4111,0.028392,...,1,3,0,1,1,0,0,0,0,22.123577
4,883cf28965fffff,Kolkata,Tala,0.149823,13.25,18224.29134,5,255,4157,0.029187,...,0,0,0,0,0,0,2,2,1,16.339713

In [5]:
df.shape

(6423, 56)

In [6]:
# plt.figure(figsize=(60,60))
# sns.heatmap(df.corr(),annot=True)
# plt.show

In [7]:
df=df.drop(columns=['shopping','medical_service','atm','bank','road_length','home_improvement_hardware_store','bar_or_pub','coffee_shop','business_facility','pharmacy','daily_avg_footfall','school','restaurant','training_centre_institute'])

# drop grids which have no population

In [8]:
df=df[df["pop_density_per_sqm"]!=0].reset_index(drop=True)

In [9]:
print(df.shape)
df.head()

(5720, 42)

,hexid08,t_name,locality,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,...,grocery_store,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price
0,883cf28945fffff,Kolkata,Sinthi,0.086059,6.84,5,3982,0.056038,0.004971,0.244236,...,45,5,0,0,0,0,1,0,0,13.491124
1,883cf28949fffff,Kolkata,Baranagar,0.169749,4.10,0,3725,0.037358,0.004139,0.309732,...,0,1,0,0,0,0,0,0,0,10.000000
2,883cf2894dfffff,Kolkata,Baranagar,0.311278,0.37,0,3403,0.030660,0.003579,0.469274,...,18,1,0,0,0,0,0,0,0,10.575139
3,883cf28961fffff,Kolkata,Paikpara,0.232866,11.60,0,4111,0.028392,0.003431,0.341649,...,12,1,3,0,1,0,0,0,0,22.123577
4,883cf28965fffff,Kolkata,Tala,0.149823,13.25,5,4157,0.029187,0.001848,0.277745,...,0,0,0,0,0,0,2,2,1,16.339713

# mask the value with 95th percentile

In [10]:
for i in df['t_name'].unique():
    print(i)
    max_value = df[df['t_name'] == i]['average_monthly_residential_rental_price'].max()
    print("Max Value:", max_value)
    
    percentile = df[df['t_name'] == i]['average_monthly_residential_rental_price'].quantile(0.95)
    print("95th Percentile:", percentile)
    
    # Replace values above the 95th percentile with the 95th percentile value
    df.loc[df['t_name'] == i, 'average_monthly_residential_rental_price'] = df[df['t_name'] == i]['average_monthly_residential_rental_price'].apply(lambda x: percentile if x > percentile else x)
    
    print("Updated Max Value:", df[df['t_name'] == i]['average_monthly_residential_rental_price'].max())

Kolkata
Max Value: 163.5090636
95th Percentile: 41.664035090999995
Updated Max Value: 41.664035090999995
Delhi
Max Value: 426.5873016
95th Percentile: 119.96153845999994
Updated Max Value: 119.96153845999994
Gurugram
Max Value: 649.5936412
95th Percentile: 52.220376378999944
Updated Max Value: 52.220376378999944
Bengaluru
Max Value: 409.0
95th Percentile: 51.768
Updated Max Value: 51.768
Mumbai
Max Value: 1375.294118
95th Percentile: 137.72629277999997
Updated Max Value: 137.72629277999997

In [11]:
print(df.shape)
df.head(5)

(5720, 42)

,hexid08,t_name,locality,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,...,grocery_store,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price
0,883cf28945fffff,Kolkata,Sinthi,0.086059,6.84,5,3982,0.056038,0.004971,0.244236,...,45,5,0,0,0,0,1,0,0,13.491124
1,883cf28949fffff,Kolkata,Baranagar,0.169749,4.10,0,3725,0.037358,0.004139,0.309732,...,0,1,0,0,0,0,0,0,0,10.000000
2,883cf2894dfffff,Kolkata,Baranagar,0.311278,0.37,0,3403,0.030660,0.003579,0.469274,...,18,1,0,0,0,0,0,0,0,10.575139
3,883cf28961fffff,Kolkata,Paikpara,0.232866,11.60,0,4111,0.028392,0.003431,0.341649,...,12,1,3,0,1,0,0,0,0,22.123577
4,883cf28965fffff,Kolkata,Tala,0.149823,13.25,5,4157,0.029187,0.001848,0.277745,...,0,0,0,0,0,0,2,2,1,16.339713

In [12]:
print(df.shape)
df.head(2)

(5720, 42)

,hexid08,t_name,locality,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,...,grocery_store,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price
0,883cf28945fffff,Kolkata,Sinthi,0.086059,6.84,5,3982,0.056038,0.004971,0.244236,...,45,5,0,0,0,0,1,0,0,13.491124
1,883cf28949fffff,Kolkata,Baranagar,0.169749,4.10,0,3725,0.037358,0.004139,0.309732,...,0,1,0,0,0,0,0,0,0,10.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5720 entries, 0 to 5719
Data columns (total 42 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   hexid08                                   5720 non-null   object
 1   t_name                                    5720 non-null   object
 2   locality                                  5720 non-null   object
 3   green_space_density                       5720 non-null   float64
 4   public_infrastructure_index               5720 non-null   float64
 5   transportation_hubs                       5720 non-null   int64
 6   total_digital_consumers                   5720 non-null   int64
 7   pop_density_per_sqm                       5720 non-null   float64
 8   building_density_per_sqm                  5720 non-null   float64
 9   luxery_percentage                         5523 non-null   float64
 10  auto_dealership                           5720 non-null   int64
 11  auto_service_maintenance                  5720 non-null   int64
 12  motorcycle_dealership                     5720 non-null   int64
 13  truck_dealership                          5720 non-null   int64
 14  government_office                         5720 non-null   int64
 15  higher_education                          5720 non-null   int64
 16  library                                   5720 non-null   int64
 17  amusement_park                            5720 non-null   int64
 18  bowling_centre                            5720 non-null   int64
 19  cinema                                    5720 non-null   int64
 20  golf_course                               5720 non-null   int64
 21  ice_skating_rink                          5720 non-null   int64
 22  museum                                    5720 non-null   int64
 23  nightlife                                 5720 non-null   int64
 24  sports_centre                             5720 non-null   int64
 25  hospital                                  5720 non-null   int64
 26  industrial_zone                           5720 non-null   int64
 27  police_station                            5720 non-null   int64
 28  clothing_store                            5720 non-null   int64
 29  consumer_electronics_store                5720 non-null   int64
 30  convenience_store                         5720 non-null   int64
 31  department_store                          5720 non-null   int64
 32  grocery_store                             5720 non-null   int64
 33  home_specialty_store                      5720 non-null   int64
 34  office_supply_services_store              5720 non-null   int64
 35  petrol_gasoline_station                   5720 non-null   int64
 36  sporting_goods_store                      5720 non-null   int64
 37  airport                                   5720 non-null   int64
 38  bus_station                               5720 non-null   int64
 39  train_station                             5720 non-null   int64
 40  hotel                                     5720 non-null   int64
 41  average_monthly_residential_rental_price  2077 non-null   float64
dtypes: float64(6), int64(33), object(3)
memory usage: 1.8+ MB

# On locality level

In [14]:
df_loca=df.groupby(['t_name','locality']).mean().reset_index()

C:\Users\chemi\AppData\Local\Temp\ipykernel_5772\1200697170.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_loca=df.groupby(['t_name','locality']).mean().reset_index()

In [15]:
df_loca

,t_name,locality,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,auto_dealership,...,grocery_store,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price
0,Bengaluru,Aanchepalya Village,0.090000,18.430000,3.000000,18086.000000,0.005798,0.001151,0.563758,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1.000000,27.650000
1,Bengaluru,Aavalahalli,0.013333,10.331111,0.111111,1273.111111,0.001309,0.000123,0.421013,0.333333,...,0.333333,0.222222,0.111111,0.111111,0.111111,0.000000,0.000000,0.000000,0.000000,13.694000
2,Bengaluru,Abbigere,0.223333,2.350000,0.000000,4620.000000,0.007311,0.001419,0.341669,0.000000,...,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,10.975000
3,Bengaluru,Adakamaranahalli,0.070000,1.075000,0.000000,87.000000,0.002355,0.000369,0.322497,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
4,Bengaluru,Adarsh Palm Retreat,0.000000,12.276667,2.666667,5085.333333,0.006444,0.001446,0.389965,0.333333,...,2.000000,3.666667,0.666667,0.333333,0.000000,0.000000,0.000000,0.000000,1.333333,27.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1502,Mumbai,Vile Parle East,0.004047,7.286000,8.866667,17228.066667,0.029464,0.000641,0.402751,0.133333,...,9.133333,2.733333,3.400000,0.200000,0.200000,0.466667,0.000000,0.000000,4.666667,80.394037
1503,Mumbai,Vile Parle West,0.003480,13.665000,16.000000,17678.500000,0.059851,0.001301,0.469677,1.000000,...,13.500000,16.500000,4.500000,2.500000,9.500000,0.000000,0.000000,5.000000,4.500000,97.823249
1504,Mumbai,Wadala,0.024497,11.003333,4.500000,17210.333333,0.037207,0.000152,0.487969,0.000000,...,17.333333,3.166667,1.666667,0.500000,1.166667,0.000000,0.666667,0.833333,0.500000,72.473459
1505,Mumbai,Worli,0.006298,13.735714,3.857143,18054.428571,0.044387,0.000498,0.523847,2.857143,...,27.142857,16.142857,11.000000,1.142857,8.428571,0.000000,0.285714,0.000000,1.857143,111.436195
1506,Mumbai,kandiwali East,0.013491,9.601667,4.500000,18271.333333,0.077735,0.000700,0.568189,0.166667,...,35.000000,10.916667,5.000000,0.083333,1.333333,0.000000,0.333333,0.000000,0.750000,40.579091

In [16]:
df_loca_2=df_loca.set_index(['t_name','locality'])

In [17]:
df_loca_2

                               green_space_density  \
t_name    locality
Bengaluru Aanchepalya Village             0.090000
          Aavalahalli                     0.013333
          Abbigere                        0.223333
          Adakamaranahalli                0.070000
          Adarsh Palm Retreat             0.000000
...                                            ...
Mumbai    Vile Parle East                 0.004047
          Vile Parle West                 0.003480
          Wadala                          0.024497
          Worli                           0.006298
          kandiwali East                  0.013491

                               public_infrastructure_index  \
t_name    locality
Bengaluru Aanchepalya Village                    18.430000
          Aavalahalli                            10.331111
          Abbigere                                2.350000
          Adakamaranahalli                        1.075000
          Adarsh Palm Retreat                    12.276667
...                                                    ...
Mumbai    Vile Parle East                         7.286000
          Vile Parle West                        13.665000
          Wadala                                 11.003333
          Worli                                  13.735714
          kandiwali East                          9.601667

                               transportation_hubs  total_digital_consumers  \
t_name    locality
Bengaluru Aanchepalya Village             3.000000             18086.000000
          Aavalahalli                     0.111111              1273.111111
          Abbigere                        0.000000              4620.000000
          Adakamaranahalli                0.000000                87.000000
          Adarsh Palm Retreat             2.666667              5085.333333
...                                            ...                      ...
Mumbai    Vile Parle East                 8.866667             17228.066667
          Vile Parle West                16.000000             17678.500000
          Wadala                          4.500000             17210.333333
          Worli                           3.857143             18054.428571
          kandiwali East                  4.500000             18271.333333

                               pop_density_per_sqm  building_density_per_sqm  \
t_name    locality
Bengaluru Aanchepalya Village             0.005798                  0.001151
          Aavalahalli                     0.001309                  0.000123
          Abbigere                        0.007311                  0.001419
          Adakamaranahalli                0.002355                  0.000369
          Adarsh Palm Retreat             0.006444                  0.001446
...                                            ...                       ...
Mumbai    Vile Parle East                 0.029464                  0.000641
          Vile Parle West                 0.059851                  0.001301
          Wadala                          0.037207                  0.000152
          Worli                           0.044387                  0.000498
          kandiwali East                  0.077735                  0.000700

                               luxery_percentage  auto_dealership  \
t_name    locality
Bengaluru Aanchepalya Village           0.563758         0.000000
          Aavalahalli                   0.421013         0.333333
          Abbigere                      0.341669         0.000000
          Adakamaranahalli              0.322497         0.000000
          Adarsh Palm Retreat           0.389965         0.333333
...                                          ...              ...
Mumbai    Vile Parle East               0.402751         0.133333
          Vile Parle West               0.469677         1.000000
          Wadala                        0.487969         0.000000
          Worli                         0.523847         2.857143
          kandiwali East                0.568189         0.166667

                               auto_service_maintenance  \
t_name    locality
Bengaluru Aanchepalya Village                  1.000000
          Aavalahalli                          0.444444
          Abbigere                             0.333333
          Adakamaranahalli                     0.000000
          Adarsh Palm Retreat                  4.333333
...                                                 ...
Mumbai    Vile Parle East                      3.533333
          Vile Parle West                      7.500000
          Wadala                               2.166667
          Worli                               13.428571
          kandiwali East                       6.750000

                               motorcycle_dealership  ...  grocery_store  \
t_name    locality                                    ...
Bengaluru Aanchepalya Village               0.000000  ...       0.000000
          Aavalahalli                       0.000000  ...       0.333333
          Abbigere                          0.000000  ...       0.000000
          Adakamaranahalli                  0.000000  ...       0.000000
          Adarsh Palm Retreat               0.666667  ...       2.000000
...                                              ...  ...            ...
Mumbai    Vile Parle East                   0.200000  ...       9.133333
          Vile Parle West                   0.500000  ...      13.500000
          Wadala                            0.000000  ...      17.333333
          Worli                             1.142857  ...      27.142857
          kandiwali East                    0.416667  ...      35.000000

                               home_specialty_store  \
t_name    locality
Bengaluru Aanchepalya Village              1.000000
          Aavalahalli                      0.222222
          Abbigere                         0.000000
          Adakamaranahalli                 0.000000
          Adarsh Palm Retreat              3.666667
...                                             ...
Mumbai    Vile Parle East                  2.733333
          Vile Parle West                 16.500000
          Wadala                           3.166667
          Worli                           16.142857
          kandiwali East                  10.916667

                               office_supply_services_store  \
t_name    locality
Bengaluru Aanchepalya Village                      0.000000
          Aavalahalli                              0.111111
          Abbigere                                 0.000000
          Adakamaranahalli                         0.000000
          Adarsh Palm Retreat                      0.666667
...                                                     ...
Mumbai    Vile Parle East                          3.400000
          Vile Parle West                          4.500000
          Wadala                                   1.666667
          Worli                                   11.000000
          kandiwali East                           5.000000

                               petrol_gasoline_station  sporting_goods_store  \
t_name    locality
Bengaluru Aanchepalya Village                 0.000000              0.000000
          Aavalahalli                         0.111111              0.111111
          Abbigere                            0.333333              0.000000
          Adakamaranahalli                    0.000000              0.000000
          Adarsh Palm Retreat                 0.333333              0.000000
...                                                ...                   ...
Mumbai    Vile Parle East                     0.200000              0.200000
          Vile Parle West                     2.500000              9.500000
          Wadala                              0.500000              1.166667
          Worli                               1.142857              8.428571
          kandiwali East                      0.083333              1.333333

                                airport  bus_station  train_station     hotel  \
t_name    locality
Bengaluru Aanchepalya Village  0.000000     2.000000       0.000000  1.000000
          Aavalahalli          0.000000     0.000000       0.000000  0.000000
          Abbigere             0.000000     0.000000       0.000000  0.000000
          Adakamaranahalli     0.000000     0.000000       0.000000  0.000000
          Adarsh Palm Retreat  0.000000     0.000000       0.000000  1.333333
...                                 ...          ...            ...       ...
Mumbai    Vile Parle East      0.466667     0.000000       0.000000  4.666667
          Vile Parle West      0.000000     0.000000       5.000000  4.500000
          Wadala               0.000000     0.666667       0.833333  0.500000
          Worli                0.000000     0.285714       0.000000  1.857143
          kandiwali East       0.000000     0.333333       0.000000  0.750000

                               average_monthly_residential_rental_price
t_name    locality
Bengaluru Aanchepalya Village                                 27.650000
          Aavalahalli                                         13.694000
          Abbigere                                            10.975000
          Adakamaranahalli                                          NaN
          Adarsh Palm Retreat                                 27.200000
...                                                                 ...
Mumbai    Vile Parle East                                     80.394037
          Vile Parle West                                     97.823249
          Wadala                                              72.473459
          Worli                                              111.436195
          kandiwali East                                      40.579091

[1507 rows x 39 columns]

In [18]:
df_loca_for_prediction=df_loca_2[df_loca_2['average_monthly_residential_rental_price'].isnull()]
df_loca_train_and_test=df_loca_2[df_loca_2['average_monthly_residential_rental_price'].notnull()]

In [19]:
df_loca_train_and_test

                                green_space_density  \
t_name    locality
Bengaluru Aanchepalya Village              0.090000
          Aavalahalli                      0.013333
          Abbigere                         0.223333
          Adarsh Palm Retreat              0.000000
          Adde Vishwanathapura             0.030000
...                                             ...
Mumbai    Vile Parle East                  0.004047
          Vile Parle West                  0.003480
          Wadala                           0.024497
          Worli                            0.006298
          kandiwali East                   0.013491

                                public_infrastructure_index  \
t_name    locality
Bengaluru Aanchepalya Village                     18.430000
          Aavalahalli                             10.331111
          Abbigere                                 2.350000
          Adarsh Palm Retreat                     12.276667
          Adde Vishwanathapura                     3.180000
...                                                     ...
Mumbai    Vile Parle East                          7.286000
          Vile Parle West                         13.665000
          Wadala                                  11.003333
          Worli                                   13.735714
          kandiwali East                           9.601667

                                transportation_hubs  total_digital_consumers  \
t_name    locality
Bengaluru Aanchepalya Village              3.000000             18086.000000
          Aavalahalli                      0.111111              1273.111111
          Abbigere                         0.000000              4620.000000
          Adarsh Palm Retreat              2.666667              5085.333333
          Adde Vishwanathapura             0.000000               977.000000
...                                             ...                      ...
Mumbai    Vile Parle East                  8.866667             17228.066667
          Vile Parle West                 16.000000             17678.500000
          Wadala                           4.500000             17210.333333
          Worli                            3.857143             18054.428571
          kandiwali East                   4.500000             18271.333333

                                pop_density_per_sqm  building_density_per_sqm  \
t_name    locality
Bengaluru Aanchepalya Village              0.005798                  0.001151
          Aavalahalli                      0.001309                  0.000123
          Abbigere                         0.007311                  0.001419
          Adarsh Palm Retreat              0.006444                  0.001446
          Adde Vishwanathapura             0.003118                  0.000175
...                                             ...                       ...
Mumbai    Vile Parle East                  0.029464                  0.000641
          Vile Parle West                  0.059851                  0.001301
          Wadala                           0.037207                  0.000152
          Worli                            0.044387                  0.000498
          kandiwali East                   0.077735                  0.000700

                                luxery_percentage  auto_dealership  \
t_name    locality
Bengaluru Aanchepalya Village            0.563758         0.000000
          Aavalahalli                    0.421013         0.333333
          Abbigere                       0.341669         0.000000
          Adarsh Palm Retreat            0.389965         0.333333
          Adde Vishwanathapura           0.131367         0.000000
...                                           ...              ...
Mumbai    Vile Parle East                0.402751         0.133333
          Vile Parle West                0.469677         1.000000
          Wadala                         0.487969         0.000000
          Worli                          0.523847         2.857143
          kandiwali East                 0.568189         0.166667

                                auto_service_maintenance  \
t_name    locality
Bengaluru Aanchepalya Village                   1.000000
          Aavalahalli                           0.444444
          Abbigere                              0.333333
          Adarsh Palm Retreat                   4.333333
          Adde Vishwanathapura                  0.000000
...                                                  ...
Mumbai    Vile Parle East                       3.533333
          Vile Parle West                       7.500000
          Wadala                                2.166667
          Worli                                13.428571
          kandiwali East                        6.750000

                                motorcycle_dealership  ...  grocery_store  \
t_name    locality                                     ...
Bengaluru Aanchepalya Village                0.000000  ...       0.000000
          Aavalahalli                        0.000000  ...       0.333333
          Abbigere                           0.000000  ...       0.000000
          Adarsh Palm Retreat                0.666667  ...       2.000000
          Adde Vishwanathapura               0.000000  ...       0.000000
...                                               ...  ...            ...
Mumbai    Vile Parle East                    0.200000  ...       9.133333
          Vile Parle West                    0.500000  ...      13.500000
          Wadala                             0.000000  ...      17.333333
          Worli                              1.142857  ...      27.142857
          kandiwali East                     0.416667  ...      35.000000

                                home_specialty_store  \
t_name    locality
Bengaluru Aanchepalya Village               1.000000
          Aavalahalli                       0.222222
          Abbigere                          0.000000
          Adarsh Palm Retreat               3.666667
          Adde Vishwanathapura              0.000000
...                                              ...
Mumbai    Vile Parle East                   2.733333
          Vile Parle West                  16.500000
          Wadala                            3.166667
          Worli                            16.142857
          kandiwali East                   10.916667

                                office_supply_services_store  \
t_name    locality
Bengaluru Aanchepalya Village                       0.000000
          Aavalahalli                               0.111111
          Abbigere                                  0.000000
          Adarsh Palm Retreat                       0.666667
          Adde Vishwanathapura                      0.000000
...                                                      ...
Mumbai    Vile Parle East                           3.400000
          Vile Parle West                           4.500000
          Wadala                                    1.666667
          Worli                                    11.000000
          kandiwali East                            5.000000

                                petrol_gasoline_station  sporting_goods_store  \
t_name    locality
Bengaluru Aanchepalya Village                  0.000000              0.000000
          Aavalahalli                          0.111111              0.111111
          Abbigere                             0.333333              0.000000
          Adarsh Palm Retreat                  0.333333              0.000000
          Adde Vishwanathapura                 0.000000              0.000000
...                                                 ...                   ...
Mumbai    Vile Parle East                      0.200000              0.200000
          Vile Parle West                      2.500000              9.500000
          Wadala                               0.500000              1.166667
          Worli                                1.142857              8.428571
          kandiwali East                       0.083333              1.333333

                                 airport  bus_station  train_station  \
t_name    locality
Bengaluru Aanchepalya Village   0.000000     2.000000       0.000000
          Aavalahalli           0.000000     0.000000       0.000000
          Abbigere              0.000000     0.000000       0.000000
          Adarsh Palm Retreat   0.000000     0.000000       0.000000
          Adde Vishwanathapura  0.000000     0.000000       0.000000
...                                  ...          ...            ...
Mumbai    Vile Parle East       0.466667     0.000000       0.000000
          Vile Parle West       0.000000     0.000000       5.000000
          Wadala                0.000000     0.666667       0.833333
          Worli                 0.000000     0.285714       0.000000
          kandiwali East        0.000000     0.333333       0.000000

                                   hotel  \
t_name    locality
Bengaluru Aanchepalya Village   1.000000
          Aavalahalli           0.000000
          Abbigere              0.000000
          Adarsh Palm Retreat   1.333333
          Adde Vishwanathapura  0.000000
...                                  ...
Mumbai    Vile Parle East       4.666667
          Vile Parle West       4.500000
          Wadala                0.500000
          Worli                 1.857143
          kandiwali East        0.750000

                                average_monthly_residential_rental_price
t_name    locality
Bengaluru Aanchepalya Village                                  27.650000
          Aavalahalli                                          13.694000
          Abbigere                                             10.975000
          Adarsh Palm Retreat                                  27.200000
          Adde Vishwanathapura                                 25.220000
...                                                                  ...
Mumbai    Vile Parle East                                      80.394037
          Vile Parle West                                      97.823249
          Wadala                                               72.473459
          Worli                                               111.436195
          kandiwali East                                       40.579091

[915 rows x 39 columns]

In [20]:
x_loc=df_loca_train_and_test.iloc[:,:-1]
y_loc=df_loca_train_and_test.iloc[:,-1]

In [21]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(x_loc,y_loc,test_size=0.2,random_state=1)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(732, 38)
(732,)
(183, 38)
(183,)

In [22]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [42]:
import pickle
pickle.dump(sc,open("scaling.pkl",'wb'))

In [245]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor
n_estimators= [int(x) for x in np.linspace(start=200,stop=3000,num=10)]
max_features=['auto','sqrt']
max_depth=[int(x) for x in np.linspace(start=10,stop=110,num=11)]
# when there is no max_depth it takes none so that the model go to its maximum extent 
max_depth.append(None)
min_samples_split = [2,5,10]
min_samples_leaf=[1,2,4]
bootstrap=[True,False]
# Create the random grid
random_grid={'n_estimators': n_estimators , 'max_features':max_features,
             'max_depth':max_depth,
             'min_samples_split':min_samples_split,'min_samples_leaf':min_samples_leaf,
            'bootstrap':bootstrap}
random_grid
rf=RandomForestRegressor(random_state=42)
# here cv is cross validation and n_jobs=-1 tell to run all trees simulteniously
rf_random=RandomizedSearchCV(estimator=rf,param_distributions=random_grid,n_iter=100,
                             scoring='neg_mean_absolute_error',cv=3,verbose=4,
                             random_state=42,n_jobs=-1,return_train_score=True)

rf2=rf_random.fit(x_train,y_train);
# by runninng below code we get  the parameter for best model
print("best parameter",rf2.best_params_)
y_pred=rf2.predict(x_test)
# Now accuracy improve
#accuracy_score(y_pred,y_test)
print("r2_on_train: ", (y_pred,y_test))
rf2.cv_results_
#importance=rf2.feature_importances_

Fitting 3 folds for each of 100 candidates, totalling 300 fits

C:\Users\chemi\Desktop\enviroments\myml\lib\site-packages\sklearn\ensemble\_forest.py:416: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(

best parameter {'n_estimators': 1444, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'auto', 'max_depth': 100, 'bootstrap': True}
r2_on_train:  (array([29.56797068, 28.28209212, 32.73707948, 23.94492668, 37.9328395 ,
       21.10794411, 49.06429391, 23.849948  , 71.65534486, 25.91187358,
       18.62793743, 41.60023293, 18.86757645, 29.97760678, 22.32204354,
       24.1530176 , 46.06648542, 19.75478539, 42.16322472, 21.14066716,
       20.71408388, 17.0504996 , 31.51274293, 25.42679722, 35.95226609,
       18.86740675, 24.88484635, 17.15222243, 24.46391229, 61.88833653,
       19.78394877, 41.79331306, 26.39734628, 74.87410554, 27.72044267,
       40.81077882, 17.09305239, 20.72751971, 19.91491628, 27.56736544,
       26.0848796 , 20.26374957, 29.72823097, 38.9943003 , 33.92313483,
       23.37209741, 28.15655665, 27.2916447 , 21.6254183 , 39.68910194,
       35.20233814, 21.22623365, 38.99671457, 28.28570244, 25.30451763,
       24.8957629 , 16.90684103, 35.40089187, 48.27290637, 39.13774413,
       51.01721677, 27.63542747, 29.59851381, 20.38242006, 17.25606227,
       20.53171203, 22.9213716 , 24.38452157, 18.7854638 , 19.20001915,
       22.11618686, 25.28955122, 19.34867265, 42.44363902, 35.28987158,
       23.01231851, 26.70839628, 17.25971344, 25.90383529, 31.81923941,
       34.55125424, 34.19854008, 30.67869152, 24.58736938, 20.8089428 ,
       22.67766243, 27.26558702, 36.06862389, 24.13337544, 14.69091938,
       20.56790992, 33.23636827, 18.23516401, 24.39739001, 15.04232599,
       27.32019581, 33.3262089 , 39.92734557, 33.17766489, 20.92623246,
       27.39950433, 20.61145526, 32.9703126 , 18.45594183, 15.07673371,
       42.96677839, 38.0252519 , 14.6373965 , 31.43810608, 78.40566062,
       20.62612797, 31.81314013, 59.3343343 , 24.98937398, 39.50857521,
       18.39262384, 38.58886518, 34.76360791, 23.91003013, 24.97626016,
       25.50369186, 26.4292847 , 28.11296798, 20.07089036, 22.43553348,
       29.44027904, 38.04490097, 25.43103401, 28.16470093, 74.54995716,
       21.04437468, 44.91354182, 18.88883056, 29.52352162, 46.13684615,
       74.50016763, 25.24625205, 26.26939454, 24.76386879, 22.21956341,
       42.40641464, 50.5838622 , 27.65702054, 26.2609561 , 34.31130956,
       15.7608881 , 14.20432178, 68.70264429, 34.06660357, 20.25964389,
       21.40892025, 26.06852016, 31.58066274, 21.30442666, 21.88904323,
       31.95784038, 22.89092954, 53.52942009, 25.67435808, 39.59556136,
       30.84432372, 69.57664094, 15.72158654, 24.59896094, 52.04590448,
       16.59400007, 23.16000219, 19.86331706, 23.03282592, 66.23960129,
       16.25367123, 33.16911041, 15.79140473, 15.55891962, 26.34181286,
       58.06025168, 44.33574688, 51.84671212, 37.25318163, 20.30022774,
       23.86486084, 31.7670719 , 18.8465878 ]), t_name     locality
Bengaluru  Neelasandra                     32.596000
Gurugram   Sector 17                       18.390453
Bengaluru  Hebbal Kempapura                19.435000
           Srirampura                      25.255000
Mumbai     Malad West                      45.782347
                                             ...
Delhi      Nizamuddin East                 53.053053
Bengaluru  Doddabommasandra                15.433333
           Benson Town                     51.768000
Delhi      Central Ridge Reserve Forest    24.000000
Bengaluru  Gantiganahalli                  14.980000
Name: average_monthly_residential_rental_price, Length: 183, dtype: float64)

{'mean_fit_time': array([ 1.85590974,  9.42598955,  6.22857189, 29.93739692,  7.25715836,
         2.99365298,  4.28713234,  2.63805707, 20.20837593, 23.58147279,
         3.04976122,  3.7075727 ,  7.6838007 ,  6.62666321,  3.39856339,
        26.70836186, 10.111998  ,  4.82341401, 30.03113095,  7.15053773,
         7.99219433,  7.75193357,  5.37670859, 22.33287883,  6.86120605,
         2.02618965, 31.18452183,  4.00079616, 29.61445157,  5.08534122,
         4.54084261,  3.66130225,  4.06990099,  3.32378467,  7.85877657,
         3.4008685 ,  5.08976364, 11.46464992,  9.53256051,  4.5264353 ,
         1.37982249,  2.34362793,  3.00864848,  1.28699613,  2.50649405,
         5.01030072, 24.59398309,  1.51829767,  5.17359869,  2.74638017,
        39.2708536 , 33.93169626, 14.38077553, 14.571467  ,  6.16656876,
         2.22801669, 17.66995875, 22.27374872, 19.5082438 ,  5.39071401,
         0.66239842,  1.41678437, 14.19583138, 19.38762585,  6.27455131,
        17.2681764 , 24.92624625, 17.25888777,  4.52149844, 34.10618583,
         5.66027761,  3.14009349,  7.91612871,  6.9716514 , 20.8900737 ,
         1.52745469,  6.59170524,  9.39106003,  3.97217655,  1.38744148,
        30.91866104,  6.3447179 , 10.12950611, 12.61142325,  3.05539942,
         2.53212714,  1.59825174,  6.78754489,  3.17292794,  3.98319554,
         2.39891473,  8.4464097 ,  3.43215267,  5.64440203,  2.19034576,
         6.22035138, 14.16296625,  2.08077081,  8.00119114, 17.24650582]),
 'std_fit_time': array([0.06297114, 0.26438957, 0.26283119, 0.73801181, 0.34331324,
        0.11870364, 0.16021178, 0.06995388, 1.17874249, 0.55369909,
        0.02976935, 0.13796915, 0.28049785, 0.14120417, 0.02241276,
        0.33088259, 0.53933195, 0.11617169, 1.87623878, 0.15016212,
        0.12867456, 0.07040905, 0.08425874, 0.47072046, 0.03634354,
        0.04120889, 0.09091909, 0.01132496, 0.95865562, 0.07064036,
        0.16915625, 0.085571  , 0.07814487, 0.29955635, 0.20318031,
        0.06424093, 0.0816933 , 0.73407136, 0.34858138, 0.25562268,
        0.05939504, 0.09344162, 0.06343057, 0.03391772, 0.11892776,
        0.11613516, 0.53682062, 0.10590815, 0.06397448, 0.05894822,
        0.88962521, 1.80524534, 0.22495191, 0.33763493, 0.19619131,
        0.07987177, 0.27126669, 0.28831601, 0.23530061, 0.0066449 ,
        0.01346454, 0.11953122, 0.41201536, 0.94773274, 0.07715494,
        0.17220783, 0.24765003, 0.63192456, 0.26817374, 1.07756662,
        0.33338442, 0.03064138, 0.10200764, 0.16055269, 0.64891723,
        0.12791134, 0.23980763, 0.24805757, 0.07566482, 0.0180705 ,
        0.03874621, 0.08737808, 0.2528346 , 0.63533642, 0.08336885,
        0.18748725, 0.10914612, 0.26711034, 0.25673228, 0.09688224,
        0.03559053, 0.28242674, 0.09610103, 0.18088249, 0.0446404 ,
        0.17881297, 0.1805227 , 0.08961632, 0.12310633, 0.35899856]),
 'mean_score_time': array([0.08919239, 0.40805864, 0.24243855, 0.36489344, 0.33397444,
        0.15687188, 0.18145585, 0.106637  , 0.26857106, 0.31367707,
        0.05757419, 0.14635793, 0.39237579, 0.3231612 , 0.14108109,
        0.35127831, 0.1307656 , 0.20651118, 0.33495577, 0.12737632,
        0.36738666, 0.34093078, 0.27543728, 0.3662103 , 0.2894973 ,
        0.08915019, 0.31400132, 0.20688732, 0.3694911 , 0.24568073,
        0.24031075, 0.20067255, 0.19843896, 0.14877184, 0.39238509,
        0.15179245, 0.24653029, 0.17604033, 0.14660064, 0.22028677,
        0.02923934, 0.11503061, 0.15177457, 0.06282791, 0.03139416,
        0.2080934 , 0.39250628, 0.07223161, 0.24095345, 0.1198264 ,
        0.4006323 , 0.34300391, 0.17040491, 0.18838286, 0.28776463,
        0.10470049, 0.34658138, 0.35054326, 0.26697302, 0.26159978,
        0.03668761, 0.0733757 , 0.17458169, 0.20403703, 0.2929825 ,
        0.30341736, 0.35560234, 0.30342301, 0.19113016, 0.34590284,
        0.30369425, 0.15698918, 0.37175179, 0.0625174 , 0.33971302,
        0.07857641, 0.30928842, 0.38640984, 0.1971786 , 0.02482096,
        0.42919978, 0.11819736, 0.18479133, 0.14107227, 0.15406473,
        0.10461887, 0.07297945, 0.31400204, 0.15233127, 0.1943663 ,
        0.11221345, 0.39236871, 0.14180533, 0.1109    , 0.10462101,
        0.07838535, 0.13007498, 0.03124976, 0.33690373, 0.25259972]),
 'std_score_time': array([1.96193994e-02, 3.86600837e-02, 1.21705843e-02, 1.75878660e-02,
        5.36906172e-02, 1.29315122e-02, 1.79005726e-02, 1.35203231e-02,
        3.61693105e-02, 3.35196424e-02, 7.28624366e-03, 1.94608969e-02,
        4.42064248e-02, 1.82906611e-02, 9.44891863e-06, 2.02876583e-02,
        1.94646578e-02, 3.18531917e-02, 2.09345549e-02, 2.10829979e-02,
        3.15359133e-02, 2.66233754e-02, 1.22548516e-02, 1.49234628e-02,
        6.66139592e-03, 1.51212949e-02, 2.56881072e-02, 1.67235692e-02,
        3.41571544e-02, 7.36401125e-03, 7.10287366e-03, 2.68561084e-02,
        1.99204604e-02, 6.56750853e-03, 1.27370272e-02, 7.22956799e-03,
        6.51513229e-03, 8.67258436e-03, 7.13737384e-03, 1.29561431e-02,
        2.85075665e-03, 7.36822468e-03, 7.25405990e-03, 2.29235989e-04,
        1.25749843e-02, 8.31768288e-03, 2.16682901e-02, 6.70939988e-03,
        1.93649560e-02, 1.41518878e-02, 1.72064965e-02, 1.00050120e-02,
        1.88000243e-02, 2.21188386e-02, 3.24449633e-02, 7.43046119e-03,
        6.95960948e-02, 3.21897588e-02, 2.57160715e-05, 1.48252521e-02,
        7.49989962e-03, 7.66910442e-03, 2.71033020e-03, 2.72766786e-06,
        2.01142050e-02, 7.36007656e-03, 2.63023048e-02, 2.68561110e-02,
        4.53895390e-03, 1.14019021e-02, 4.49683017e-02, 1.29718022e-02,
        7.79443107e-03, 7.90984553e-06, 7.26875546e-03, 1.27452054e-02,
        2.05058685e-02, 1.35359955e-02, 2.46090817e-02, 6.41785871e-03,
        2.64667264e-02, 6.33846760e-03, 2.12517189e-02, 3.76676205e-05,
        1.83754655e-02, 7.35333269e-03, 7.54704895e-03, 7.97219347e-05,
        1.55905253e-02, 1.52490349e-02, 3.31961188e-03, 2.21020887e-02,
        1.36503570e-02, 1.15288891e-02, 7.36378504e-03, 1.79707914e-02,
        2.79748283e-02, 6.77992463e-06, 1.46819688e-02, 1.19498129e-02]),
 'param_n_estimators': masked_array(data=[511, 3000, 1755, 3000, 2377, 1133, 1444, 822, 1444,
                    2688, 511, 1133, 3000, 2377, 1133, 2688, 822, 1444,
                    2688, 822, 2688, 2377, 2066, 2688, 2066, 511, 2066,
                    1444, 3000, 1755, 1755, 1133, 1133, 1133, 2688, 1133,
                    1755, 1133, 1133, 1444, 200, 822, 1133, 511, 200, 1444,
                    3000, 511, 1755, 822, 2688, 3000, 1444, 1444, 2066,
                    822, 2377, 2688, 2066, 2066, 200, 511, 1444, 1755,
                    2377, 2377, 2688, 2066, 1444, 3000, 2066, 1133, 2688,
                    511, 2377, 511, 2377, 3000, 1444, 200, 3000, 822, 1444,
                    1133, 1133, 822, 511, 2377, 1133, 1444, 822, 3000,
                    1133, 822, 822, 511, 1444, 200, 3000, 3000],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[5, 5, 5, 2, 2, 5, 5, 5, 2, 5, 10, 5, 10, 5, 10, 2, 5,
                    2, 10, 5, 10, 5, 5, 2, 5, 2, 2, 5, 10, 2, 10, 2, 5, 10,
                    2, 10, 5, 2, 5, 2, 5, 10, 2, 10, 5, 2, 2, 10, 2, 2, 2,
                    10, 10, 5, 5, 2, 5, 2, 2, 10, 2, 2, 10, 10, 10, 10, 2,
                    2, 10, 10, 2, 2, 5, 5, 5, 10, 10, 5, 5, 5, 2, 10, 5,
                    10, 5, 10, 5, 2, 10, 10, 10, 5, 5, 2, 2, 10, 2, 5, 2,
                    10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_leaf': masked_array(data=[1, 1, 2, 4, 4, 4, 2, 1, 1, 4, 4, 1, 1, 2, 2, 4, 2, 1,
                    2, 1, 1, 1, 4, 2, 1, 1, 1, 2, 4, 2, 4, 2, 1, 4, 4, 2,
                    2, 1, 2, 2, 4, 2, 4, 4, 2, 1, 2, 4, 4, 2, 1, 2, 4, 4,
                    2, 4, 1, 2, 1, 2, 1, 4, 4, 2, 1, 2, 4, 2, 1, 2, 4, 4,
                    2, 1, 1, 2, 1, 1, 2, 4, 4, 2, 4, 2, 4, 1, 1, 4, 4, 2,
                    1, 4, 1, 4, 4, 2, 1, 4, 2, 2],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_max_features': masked_array(data=['sqrt', 'sqrt', 'sqrt', 'auto', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'auto', 'auto', 'auto', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'auto', 'auto', 'sqrt', 'auto', 'auto', 'sqrt',
                    'sqrt', 'sqrt', 'auto', 'sqrt', 'sqrt', 'auto', 'sqrt',
                    'auto', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'sqrt', 'auto', 'auto', 'sqrt', 'auto', 'sqrt',
                    'sqrt', 'sqrt', 'auto', 'sqrt', 'auto', 'sqrt', 'sqrt',
                    'sqrt', 'auto', 'auto', 'auto', 'auto', 'sqrt', 'sqrt',
                    'auto', 'auto', 'auto', 'sqrt', 'sqrt', 'sqrt', 'auto',
                    'auto', 'sqrt', 'auto', 'auto', 'auto', 'sqrt', 'auto',
                    'sqrt', 'sqrt', 'sqrt', 'auto', 'auto', 'sqrt', 'sqrt',
                    'sqrt', 'sqrt', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'sqrt', 'auto', 'sqrt', 'auto', 'auto', 'auto',
                    'sqrt', 'auto'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_max_depth': masked_array(data=[30, 10, 10, 30, 10, 30, 100, 60, 50, 10, 70, 90, 10,
                    10, 30, 50, 70, 20, 110, 80, 30, 70, 80, None, 80,
                    None, 40, 20, 100, 20, 20, 50, 100, 50, 90, 20, 20,
                    100, None, 60, 10, 60, 90, 90, 90, 110, 90, 80, 70,
                    110, 20, 50, 50, 30, None, 60, 10, 80, 100, 80, 50, 10,
                    80, None, 20, None, 10, 70, 80, 60, 80, 20, 60, 90, 90,
                    90, None, 100, 10, 80, 60, 100, 100, None, 70, 40, 100,
                    80, 100, 10, 110, None, 40, 40, 30, 40, 10, 100, 20,
                    40],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_bootstrap': masked_array(data=[True, True, False, False, True, False, False, False,
                    False, False, True, False, False, False, False, False,
                    False, True, False, True, False, False, True, True,
                    False, False, False, True, False, True, False, False,
                    False, True, True, False, True, True, True, True, True,
                    True, True, True, False, True, True, False, False,
                    False, False, False, False, False, False, False, True,
                    True, True, True, True, True, False, False, True, True,
                    False, True, False, False, False, False, True, False,
                    True, False, True, True, True, True, False, True, True,
                    False, False, False, True, True, True, True, True,
                    False, True, True, False, False, False, False, True,
                    True],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_estimators': 511,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'max_features': 'sqrt',
   'max_depth': 30,
   'bootstrap': True},
  {'n_estimators': 3000,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'max_features': 'sqrt',
   'max_depth': 10,
   'bootstrap': True},
  {'n_estimators': 1755,
   'min_samples_split': 5,
   'min_samples_leaf': 2,
   'max_features': 'sqrt',
   'max_depth': 10,
   'bootstrap': False},
  {'n_estimators': 3000,
   'min_samples_split': 2,
   'min_samples_leaf': 4,
   'max_features': 'auto',
   'max_depth': 30,
   'bootstrap': False},
  {'n_estimators': 2377,
   'min_samples_split': 2,
   'min_samples_leaf': 4,
   'max_features': 'sqrt',
   'max_depth': 10,
   'bootstrap': True},
  {'n_estimators': 1133,
   'min_samples_split': 5,
   'min_samples_leaf': 4,
   'max_features': 'sqrt',
   'max_depth': 30,
   'bootstrap': False},
  {'n_estimators': 1444,
   'min_samples_split': 5,
   'min_samples_leaf': 2,
   'max_features': 'sqrt',
   'max_depth': 100,
   'bootstrap': False},
  {'n_estimators': 822,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'max_features': 'sqrt',
   'max_depth': 60,
   'bootstrap': False},
  {'n_estimators': 1444,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'max_features': 'auto',
   'max_depth': 50,
   'bootstrap': False},
  {'n_estimators': 2688,
   'min_samples_split': 5,
   'min_samples_leaf': 4,
   'max_features': 'auto',
   'max_depth': 10,
   'bootstrap': False},
  {'n_estimators': 511,
   'min_samples_split': 10,
   'min_samples_leaf': 4,
   'max_features': 'auto',
   'max_depth': 70,
   'bootstrap': True},
  {'n_estimators': 1133,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'max_features': 'sqrt',
   'max_depth': 90,
   'bootstrap': False},
  {'n_estimators': 3000,
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'max_features': 'sqrt',
   'max_depth': 10,
   'bootstrap': False},
  {'n_estimators': 2377,
   'min_samples_split': 5,
   'min_samples_leaf': 2,
   'max_features': 'sqrt',
   'max_depth': 10,
   'bootstrap': False},
  {'n_estimators': 1133,
   'min_samples_split': 10,
   'min_samples_leaf': 2,
   'max_features': 'sqrt',
   'max_depth': 30,
   'bootstrap': False},
  {'n_estimators': 2688,
   'min_samples_split': 2,
   'min_samples_leaf': 4,
   'max_features': 'auto',
   'max_depth': 50,
   'bootstrap': False},
  {'n_estimators': 822,
   'min_samples_split': 5,
   'min_samples_leaf': 2,
   'max_features': 'auto',
   'max_depth': 70,
   'bootstrap': False},
  {'n_estimators': 1444,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'max_features': 'sqrt',
   'max_depth': 20,
   'bootstrap': True},
  {'n_estimators': 2688,
   'min_samples_split': 10,
   'min_samples_leaf': 2,
   'max_features': 'auto',
   'max_depth': 110,
   'bootstrap': False},
  {'n_estimators': 822,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'max_features': 'auto',
   'max_depth': 80,
   'bootstrap': True},
  {'n_estimators': 2688,
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'max_features': 'sqrt',
   'max_depth': 30,
   'bootstrap': False},
  {'n_estimators': 2377,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'max_features': 'sqrt',
   'max_depth': 70,
   'bootstrap': False},
  {'n_estimators': 2066,
   'min_samples_split': 5,
   'min_samples_leaf': 4,
   'max_features': 'sqrt',
   'max_depth': 80,

In [23]:
from sklearn.ensemble import RandomForestRegressor
model_r_b=RandomForestRegressor(n_estimators=1444,min_samples_split=5,min_samples_leaf=4,max_features='auto',max_depth=100,bootstrap= True )

In [24]:
model_r_b.fit(x_train,y_train)

C:\Users\chemi\Desktop\enviroments\myml\lib\site-packages\sklearn\ensemble\_forest.py:416: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(

RandomForestRegressor(max_depth=100, max_features='auto', min_samples_leaf=4,
                      min_samples_split=5, n_estimators=1444)

In [ ]:
import pickle
pickle.dump(sc,open("rent_model_predcit.pkl",'wb'))

In [25]:
["{:.6f}".format(importance) for importance in model_r_b.feature_importances_]

['0.103138',
 '0.046943',
 '0.023308',
 '0.041331',
 '0.048444',
 '0.216177',
 '0.029653',
 '0.006258',
 '0.022538',
 '0.004222',
 '0.000709',
 '0.050806',
 '0.009845',
 '0.003936',
 '0.001309',
 '0.000011',
 '0.003551',
 '0.000316',
 '0.000020',
 '0.066226',
 '0.030201',
 '0.010220',
 '0.009136',
 '0.005775',
 '0.011026',
 '0.011416',
 '0.013689',
 '0.022997',
 '0.009272',
 '0.014444',
 '0.011884',
 '0.010302',
 '0.008313',
 '0.036456',
 '0.000022',
 '0.003251',
 '0.034100',
 '0.078756']

In [459]:
feature_importances = [
    '0.101690', '0.045933', '0.024752', '0.040333', '0.049887', '0.219024', '0.027571',
    '0.005908', '0.023402', '0.003974', '0.000768', '0.052452', '0.009970', '0.004266',
    '0.001157', '0.000007', '0.003919', '0.000316', '0.000025', '0.065882', '0.028013',
    '0.009616', '0.008886', '0.006733', '0.010895', '0.010881', '0.013816', '0.023076',
    '0.009655', '0.013688', '0.011158', '0.010953', '0.008711', '0.035668', '0.000061',
    '0.003119', '0.031244', '0.082590'
]

# Convert feature importances to float numbers
feature_importances = [float(importance) for importance in feature_importances]

# Get the top 5 indices and values
top_indices = np.argsort(feature_importances)[::-1][:5]
top_values = [feature_importances[i] for i in top_indices]

print("Top 5 Indices:", top_indices)
print("Top 5 Values:", top_values)

Top 5 Indices: [ 5  0 37 19 11]
Top 5 Values: [0.219024, 0.10169, 0.08259, 0.065882, 0.052452]

In [26]:
x_loc.columns
#top 5 columns as per importance:- 'green_space_density','building_density_per_sqm','government_offic','museum','hotel'

Index(['green_space_density', 'public_infrastructure_index',
       'transportation_hubs', 'total_digital_consumers', 'pop_density_per_sqm',
       'building_density_per_sqm', 'luxery_percentage', 'auto_dealership',
       'auto_service_maintenance', 'motorcycle_dealership', 'truck_dealership',
       'government_office', 'higher_education', 'library', 'amusement_park',
       'bowling_centre', 'cinema', 'golf_course', 'ice_skating_rink', 'museum',
       'nightlife', 'sports_centre', 'hospital', 'industrial_zone',
       'police_station', 'clothing_store', 'consumer_electronics_store',
       'convenience_store', 'department_store', 'grocery_store',
       'home_specialty_store', 'office_supply_services_store',
       'petrol_gasoline_station', 'sporting_goods_store', 'airport',
       'bus_station', 'train_station', 'hotel'],
      dtype='object')

In [27]:
y_predict_train=model_r_b.predict(x_train)
y_predict_test=model_r_b.predict(x_test)

In [28]:
from sklearn import metrics
from sklearn.metrics import r2_score
print('mean Absolute error_of_train: ', metrics.mean_absolute_error(y_train,y_predict_train))
print('mean Absolute error_of_test: ', metrics.mean_absolute_error(y_test,y_predict_test))
print('mean squared error_of_train: ', metrics.mean_squared_error(y_train,y_predict_train))
print('mean squared error_of_test: ' , metrics.mean_squared_error(y_test,y_predict_test))
print('root mean Absolute error_of_train: ', np.sqrt(metrics.mean_squared_error(y_train,y_predict_train)))
print('root mean Absolute error_of_test: ', np.sqrt(metrics.mean_squared_error(y_test,y_predict_test)))
print("r2_on_train: ", r2_score(y_train,y_predict_train))
print("r2_on_test:  ", r2_score(y_test,y_predict_test))

mean Absolute error_of_train:  6.105775092852261
mean Absolute error_of_test:  12.762308566759407
mean squared error_of_train:  106.55483494561001
mean squared error_of_test:  396.5271344219429
root mean Absolute error_of_train:  10.32254014017916
root mean Absolute error_of_test:  19.91298908807874
r2_on_train:  0.7979568325223665
r2_on_test:   0.32697506844078705

In [37]:
df_loca_for_prediction.reset_index()['t_name'].unique()

array(['Bengaluru', 'Delhi', 'Gurugram', 'Kolkata', 'Mumbai'],
      dtype=object)

In [38]:
df_loca_for_prediction=df_loca_for_prediction.iloc[:,:-1]

In [41]:
df_loca_for_prediction.columns

Index(['green_space_density', 'public_infrastructure_index',
       'transportation_hubs', 'total_digital_consumers', 'pop_density_per_sqm',
       'building_density_per_sqm', 'luxery_percentage', 'auto_dealership',
       'auto_service_maintenance', 'motorcycle_dealership', 'truck_dealership',
       'government_office', 'higher_education', 'library', 'amusement_park',
       'bowling_centre', 'cinema', 'golf_course', 'ice_skating_rink', 'museum',
       'nightlife', 'sports_centre', 'hospital', 'industrial_zone',
       'police_station', 'clothing_store', 'consumer_electronics_store',
       'convenience_store', 'department_store', 'grocery_store',
       'home_specialty_store', 'office_supply_services_store',
       'petrol_gasoline_station', 'sporting_goods_store', 'airport',
       'bus_station', 'train_station', 'hotel'],
      dtype='object')

In [299]:
print(df_loca_for_prediction.shape)
df_loca_for_prediction.head(2)

(592, 38)

                            green_space_density  public_infrastructure_index  \
t_name    locality
Bengaluru Adakamaranahalli               0.0700                        1.075
          Adiganahalli                   0.0275                        2.190

                            transportation_hubs  total_digital_consumers  \
t_name    locality
Bengaluru Adakamaranahalli                 0.00                    87.00
          Adiganahalli                     0.25                  1600.75

                            pop_density_per_sqm  building_density_per_sqm  \
t_name    locality
Bengaluru Adakamaranahalli             0.002355                  0.000369
          Adiganahalli                 0.001860                  0.000330

                            luxery_percentage  auto_dealership  \
t_name    locality
Bengaluru Adakamaranahalli           0.322497              0.0
          Adiganahalli               0.467711              0.0

                            auto_service_maintenance  motorcycle_dealership  \
t_name    locality
Bengaluru Adakamaranahalli                       0.0                    0.0
          Adiganahalli                           0.5                    0.0

                            ...  department_store  grocery_store  \
t_name    locality          ...
Bengaluru Adakamaranahalli  ...               0.0           0.00
          Adiganahalli      ...               0.0           0.75

                            home_specialty_store  \
t_name    locality
Bengaluru Adakamaranahalli                  0.00
          Adiganahalli                      0.25

                            office_supply_services_store  \
t_name    locality
Bengaluru Adakamaranahalli                           0.0
          Adiganahalli                               0.0

                            petrol_gasoline_station  sporting_goods_store  \
t_name    locality
Bengaluru Adakamaranahalli                      0.0                   0.0
          Adiganahalli                          0.0                   0.0

                            airport  bus_station  train_station  hotel
t_name    locality
Bengaluru Adakamaranahalli      0.0          0.0           0.00    0.0
          Adiganahalli          0.0          0.0           0.25    1.5

[2 rows x 38 columns]

In [300]:
df_loca_for_prediction=df_loca_for_prediction.dropna()
print(df_loca_for_prediction.shape)
df_loca_for_prediction.head(2)

(580, 38)

                            green_space_density  public_infrastructure_index  \
t_name    locality
Bengaluru Adakamaranahalli               0.0700                        1.075
          Adiganahalli                   0.0275                        2.190

                            transportation_hubs  total_digital_consumers  \
t_name    locality
Bengaluru Adakamaranahalli                 0.00                    87.00
          Adiganahalli                     0.25                  1600.75

                            pop_density_per_sqm  building_density_per_sqm  \
t_name    locality
Bengaluru Adakamaranahalli             0.002355                  0.000369
          Adiganahalli                 0.001860                  0.000330

                            luxery_percentage  auto_dealership  \
t_name    locality
Bengaluru Adakamaranahalli           0.322497              0.0
          Adiganahalli               0.467711              0.0

                            auto_service_maintenance  motorcycle_dealership  \
t_name    locality
Bengaluru Adakamaranahalli                       0.0                    0.0
          Adiganahalli                           0.5                    0.0

                            ...  department_store  grocery_store  \
t_name    locality          ...
Bengaluru Adakamaranahalli  ...               0.0           0.00
          Adiganahalli      ...               0.0           0.75

                            home_specialty_store  \
t_name    locality
Bengaluru Adakamaranahalli                  0.00
          Adiganahalli                      0.25

                            office_supply_services_store  \
t_name    locality
Bengaluru Adakamaranahalli                           0.0
          Adiganahalli                               0.0

                            petrol_gasoline_station  sporting_goods_store  \
t_name    locality
Bengaluru Adakamaranahalli                      0.0                   0.0
          Adiganahalli                          0.0                   0.0

                            airport  bus_station  train_station  hotel
t_name    locality
Bengaluru Adakamaranahalli      0.0          0.0           0.00    0.0
          Adiganahalli          0.0          0.0           0.25    1.5

[2 rows x 38 columns]

In [301]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
predict_scale=sc.fit_transform(df_loca_for_prediction)

In [302]:
new_data_predict=model_r_b.predict(predict_scale)

In [303]:
df_loca_for_prediction['average_monthly_residential_rental_price']=new_data_predict

In [304]:
df_loca_train_and_test["prediction"]="old"
df_loca_for_prediction['prediction']="yes"

C:\Users\chemi\AppData\Local\Temp\ipykernel_19744\2057699694.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_loca_train_and_test["prediction"]="old"

In [305]:
df_loca_train_and_test

                                green_space_density  \
t_name    locality
Bengaluru Aanchepalya Village              0.090000
          Aavalahalli                      0.013333
          Abbigere                         0.223333
          Adarsh Palm Retreat              0.000000
          Adde Vishwanathapura             0.030000
...                                             ...
Mumbai    Vile Parle East                  0.004047
          Vile Parle West                  0.003480
          Wadala                           0.024497
          Worli                            0.006298
          kandiwali East                   0.013491

                                public_infrastructure_index  \
t_name    locality
Bengaluru Aanchepalya Village                     18.430000
          Aavalahalli                             10.331111
          Abbigere                                 2.350000
          Adarsh Palm Retreat                     12.276667
          Adde Vishwanathapura                     3.180000
...                                                     ...
Mumbai    Vile Parle East                          7.286000
          Vile Parle West                         13.665000
          Wadala                                  11.003333
          Worli                                   13.735714
          kandiwali East                           9.601667

                                transportation_hubs  total_digital_consumers  \
t_name    locality
Bengaluru Aanchepalya Village              3.000000             18086.000000
          Aavalahalli                      0.111111              1273.111111
          Abbigere                         0.000000              4620.000000
          Adarsh Palm Retreat              2.666667              5085.333333
          Adde Vishwanathapura             0.000000               977.000000
...                                             ...                      ...
Mumbai    Vile Parle East                  8.866667             17228.066667
          Vile Parle West                 16.000000             17678.500000
          Wadala                           4.500000             17210.333333
          Worli                            3.857143             18054.428571
          kandiwali East                   4.500000             18271.333333

                                pop_density_per_sqm  building_density_per_sqm  \
t_name    locality
Bengaluru Aanchepalya Village              0.005798                  0.001151
          Aavalahalli                      0.001309                  0.000123
          Abbigere                         0.007311                  0.001419
          Adarsh Palm Retreat              0.006444                  0.001446
          Adde Vishwanathapura             0.003118                  0.000175
...                                             ...                       ...
Mumbai    Vile Parle East                  0.029464                  0.000641
          Vile Parle West                  0.059851                  0.001301
          Wadala                           0.037207                  0.000152
          Worli                            0.044387                  0.000498
          kandiwali East                   0.077735                  0.000700

                                luxery_percentage  auto_dealership  \
t_name    locality
Bengaluru Aanchepalya Village            0.563758         0.000000
          Aavalahalli                    0.421013         0.333333
          Abbigere                       0.341669         0.000000
          Adarsh Palm Retreat            0.389965         0.333333
          Adde Vishwanathapura           0.131367         0.000000
...                                           ...              ...
Mumbai    Vile Parle East                0.402751         0.133333
          Vile Parle West                0.469677         1.000000
          Wadala                         0.487969         0.000000
          Worli                          0.523847         2.857143
          kandiwali East                 0.568189         0.166667

                                auto_service_maintenance  \
t_name    locality
Bengaluru Aanchepalya Village                   1.000000
          Aavalahalli                           0.444444
          Abbigere                              0.333333
          Adarsh Palm Retreat                   4.333333
          Adde Vishwanathapura                  0.000000
...                                                  ...
Mumbai    Vile Parle East                       3.533333
          Vile Parle West                       7.500000
          Wadala                                2.166667
          Worli                                13.428571
          kandiwali East                        6.750000

                                motorcycle_dealership  ...  \
t_name    locality                                     ...
Bengaluru Aanchepalya Village                0.000000  ...
          Aavalahalli                        0.000000  ...
          Abbigere                           0.000000  ...
          Adarsh Palm Retreat                0.666667  ...
          Adde Vishwanathapura               0.000000  ...
...                                               ...  ...
Mumbai    Vile Parle East                    0.200000  ...
          Vile Parle West                    0.500000  ...
          Wadala                             0.000000  ...
          Worli                              1.142857  ...
          kandiwali East                     0.416667  ...

                                home_specialty_store  \
t_name    locality
Bengaluru Aanchepalya Village               1.000000
          Aavalahalli                       0.222222
          Abbigere                          0.000000
          Adarsh Palm Retreat               3.666667
          Adde Vishwanathapura              0.000000
...                                              ...
Mumbai    Vile Parle East                   2.733333
          Vile Parle West                  16.500000
          Wadala                            3.166667
          Worli                            16.142857
          kandiwali East                   10.916667

                                office_supply_services_store  \
t_name    locality
Bengaluru Aanchepalya Village                       0.000000
          Aavalahalli                               0.111111
          Abbigere                                  0.000000
          Adarsh Palm Retreat                       0.666667
          Adde Vishwanathapura                      0.000000
...                                                      ...
Mumbai    Vile Parle East                           3.400000
          Vile Parle West                           4.500000
          Wadala                                    1.666667
          Worli                                    11.000000
          kandiwali East                            5.000000

                                petrol_gasoline_station  sporting_goods_store  \
t_name    locality
Bengaluru Aanchepalya Village                  0.000000              0.000000
          Aavalahalli                          0.111111              0.111111
          Abbigere                             0.333333              0.000000
          Adarsh Palm Retreat                  0.333333              0.000000
          Adde Vishwanathapura                 0.000000              0.000000
...                                                 ...                   ...
Mumbai    Vile Parle East                      0.200000              0.200000
          Vile Parle West                      2.500000              9.500000
          Wadala                               0.500000              1.166667
          Worli                                1.142857              8.428571
          kandiwali East                       0.083333              1.333333

                                 airport  bus_station  train_station  \
t_name    locality
Bengaluru Aanchepalya Village   0.000000     2.000000       0.000000
          Aavalahalli           0.000000     0.000000       0.000000
          Abbigere              0.000000     0.000000       0.000000
          Adarsh Palm Retreat   0.000000     0.000000       0.000000
          Adde Vishwanathapura  0.000000     0.000000       0.000000
...                                  ...          ...            ...
Mumbai    Vile Parle East       0.466667     0.000000       0.000000
          Vile Parle West       0.000000     0.000000       5.000000
          Wadala                0.000000     0.666667       0.833333
          Worli                 0.000000     0.285714       0.000000
          kandiwali East        0.000000     0.333333       0.000000

                                   hotel  \
t_name    locality
Bengaluru Aanchepalya Village   1.000000
          Aavalahalli           0.000000
          Abbigere              0.000000
          Adarsh Palm Retreat   1.333333
          Adde Vishwanathapura  0.000000
...                                  ...
Mumbai    Vile Parle East       4.666667
          Vile Parle West       4.500000
          Wadala                0.500000
          Worli                 1.857143
          kandiwali East        0.750000

                                average_monthly_residential_rental_price  \
t_name    locality
Bengaluru Aanchepalya Village                                  27.650000
          Aavalahalli                                          13.694000
          Abbigere                                             10.975000
          Adarsh Palm Retreat                                  27.200000
          Adde Vishwanathapura                                 25.220000
...                                                                  ...
Mumbai    Vile Parle East                                      80.394037
          Vile Parle West                                      97.823249
          Wadala                                               72.473459
          Worli                                               111.436195
          kandiwali East                                       40.579091

                                prediction
t_name    locality
Bengaluru Aanchepalya Village          old
          Aavalahalli                  old
          Abbigere                     old
          Adarsh Palm Retreat          old
          Adde Vishwanathapura         old
...                                    ...
Mumbai    Vile Parle East              old
          Vile Parle West              old
          Wadala                       old
          Worli                        old
          kandiwali East               old

[915 rows x 40 columns]

In [306]:
df_loca_for_prediction

                                     green_space_density  \
t_name    locality
Bengaluru Adakamaranahalli                      0.070000
          Adiganahalli                          0.027500
          Adur                                  0.115000
          Aivarakhandapura                      0.360000
          Bandebommasandra                      0.080000
...                                                  ...
Mumbai    Mumbai Trans Harbour Link             0.000000
          Namnetum Street                       0.002320
          Rajiv Gandhi Sea Link                 0.000000
          Turbhe                                0.009382
          Vesava                                0.059252

                                     public_infrastructure_index  \
t_name    locality
Bengaluru Adakamaranahalli                                 1.075
          Adiganahalli                                     2.190
          Adur                                             2.230
          Aivarakhandapura                                 0.580
          Bandebommasandra                                 0.590
...                                                          ...
Mumbai    Mumbai Trans Harbour Link                        0.000
          Namnetum Street                                  5.770
          Rajiv Gandhi Sea Link                            4.870
          Turbhe                                           0.000
          Vesava                                           0.000

                                     transportation_hubs  \
t_name    locality
Bengaluru Adakamaranahalli                          0.00
          Adiganahalli                              0.25
          Adur                                      0.00
          Aivarakhandapura                          0.00
          Bandebommasandra                          0.00
...                                                  ...
Mumbai    Mumbai Trans Harbour Link                 0.00
          Namnetum Street                           1.00
          Rajiv Gandhi Sea Link                     0.00
          Turbhe                                    0.00
          Vesava                                    0.00

                                     total_digital_consumers  \
t_name    locality
Bengaluru Adakamaranahalli                             87.00
          Adiganahalli                               1600.75
          Adur                                        855.75
          Aivarakhandapura                           3504.00
          Bandebommasandra                            848.00
...                                                      ...
Mumbai    Mumbai Trans Harbour Link                  4273.00
          Namnetum Street                            9525.00
          Rajiv Gandhi Sea Link                      5023.00
          Turbhe                                     3942.00
          Vesava                                     4877.00

                                     pop_density_per_sqm  \
t_name    locality
Bengaluru Adakamaranahalli                      0.002355
          Adiganahalli                          0.001860
          Adur                                  0.000195
          Aivarakhandapura                      0.002981
          Bandebommasandra                      0.000128
...                                                  ...
Mumbai    Mumbai Trans Harbour Link             0.005524
          Namnetum Street                       0.003068
          Rajiv Gandhi Sea Link                 0.074363
          Turbhe                                0.001100
          Vesava                                0.007425

                                     building_density_per_sqm  \
t_name    locality
Bengaluru Adakamaranahalli                           0.000369
          Adiganahalli                               0.000330
          Adur                                       0.000128
          Aivarakhandapura                           0.000368
          Bandebommasandra                           0.000421
...                                                       ...
Mumbai    Mumbai Trans Harbour Link                  0.000001
          Namnetum Street                            0.000095
          Rajiv Gandhi Sea Link                      0.001872
          Turbhe                                     0.000000
          Vesava                                     0.000163

                                     luxery_percentage  auto_dealership  \
t_name    locality
Bengaluru Adakamaranahalli                    0.322497              0.0
          Adiganahalli                        0.467711              0.0
          Adur                                0.364327              0.0
          Aivarakhandapura                    0.416667              0.0
          Bandebommasandra                    0.238991              0.0
...                                                ...              ...
Mumbai    Mumbai Trans Harbour Link           0.379630              0.0
          Namnetum Street                     0.579950              0.0
          Rajiv Gandhi Sea Link               0.345597              0.0
          Turbhe                              0.033333              0.0
          Vesava                              0.577586              0.0

                                     auto_service_maintenance  \
t_name    locality
Bengaluru Adakamaranahalli                                0.0
          Adiganahalli                                    0.5
          Adur                                            0.0
          Aivarakhandapura                                0.0
          Bandebommasandra                                0.0
...                                                       ...
Mumbai    Mumbai Trans Harbour Link                       0.0
          Namnetum Street                                 0.0
          Rajiv Gandhi Sea Link                           0.0
          Turbhe                                          0.0
          Vesava                                          0.0

                                     motorcycle_dealership  ...  \
t_name    locality                                          ...
Bengaluru Adakamaranahalli                             0.0  ...
          Adiganahalli                                 0.0  ...
          Adur                                         0.0  ...
          Aivarakhandapura                             0.0  ...
          Bandebommasandra                             0.0  ...
...                                                    ...  ...
Mumbai    Mumbai Trans Harbour Link                    0.0  ...
          Namnetum Street                              0.0  ...
          Rajiv Gandhi Sea Link                        0.0  ...
          Turbhe                                       0.0  ...
          Vesava                                       0.0  ...

                                     home_specialty_store  \
t_name    locality
Bengaluru Adakamaranahalli                           0.00
          Adiganahalli                               0.25
          Adur                                       0.00
          Aivarakhandapura                           0.00
          Bandebommasandra                           0.00
...                                                   ...
Mumbai    Mumbai Trans Harbour Link                  0.00
          Namnetum Street                            0.00
          Rajiv Gandhi Sea Link                      0.00
          Turbhe                                     0.00
          Vesava                                     0.00

                                     office_supply_services_store  \
t_name    locality
Bengaluru Adakamaranahalli                                    0.0
          Adiganahalli                                        0.0
          Adur                                                0.0
          Aivarakhandapura                                    0.0
          Bandebommasandra                                    0.0
...                                                           ...
Mumbai    Mumbai Trans Harbour Link                           0.0
          Namnetum Street                                     2.0
          Rajiv Gandhi Sea Link                               0.0
          Turbhe                                              0.0
          Vesava                                              0.0

                                     petrol_gasoline_station  \
t_name    locality
Bengaluru Adakamaranahalli                               0.0
          Adiganahalli                                   0.0
          Adur                                           0.0
          Aivarakhandapura                               0.0
          Bandebommasandra                               0.0
...                                                      ...
Mumbai    Mumbai Trans Harbour Link                      0.0
          Namnetum Street                                1.0
          Rajiv Gandhi Sea Link                          0.0
          Turbhe                                         0.0
          Vesava                                         0.0

                                     sporting_goods_store  airport  \
t_name    locality
Bengaluru Adakamaranahalli                            0.0      0.0
          Adiganahalli                                0.0      0.0
          Adur                                        0.0      0.0
          Aivarakhandapura                            0.0      0.0
          Bandebommasandra                            0.0      0.0
...                                                   ...      ...
Mumbai    Mumbai Trans Harbour Link                   0.0      0.0
          Namnetum Street                             1.0      0.0
          Rajiv Gandhi Sea Link                       0.0      0.0
          Turbhe                                      0.0      0.0
          Vesava                                      0.0      0.0

                                     bus_station  train_station  hotel  \
t_name    locality
Bengaluru Adakamaranahalli                   0.0           0.00    0.0
          Adiganahalli                       0.0           0.25    1.5
          Adur                               0.0           0.00    0.0
          Aivarakhandapura                   0.0           0.00    0.0
          Bandebommasandra                   0.0           0.00    0.0
...                                          ...            ...    ...
Mumbai    Mumbai Trans Harbour Link          0.0           0.00    0.0
          Namnetum Street                    0.0           0.00   17.0
          Rajiv Gandhi Sea Link              0.0           0.00    0.0
          Turbhe                             0.0           0.00    2.0
          Vesava                             0.0           0.00    0.0

                                     average_monthly_residential_rental_price  \
t_name    locality
Bengaluru Adakamaranahalli                                          24.402895
          Adiganahalli                                              35.229014
          Adur                                                      26.124765
          Aivarakhandapura                                          26.402135
          Bandebommasandra                                          24.677635
...                                                                       ...
Mumbai    Mumbai Trans Harbour Link                                 47.821097
          Namnetum Street                                           65.734745
          Rajiv Gandhi Sea Link                                     32.179506
          Turbhe                                                    51.919306
          Vesava                                                    32.850992

                                     prediction
t_name    locality
Bengaluru Adakamaranahalli                  yes
          Adiganahalli                      yes
          Adur                              yes
          Aivarakhandapura                  yes
          Bandebommasandra                  yes
...                                         ...
Mumbai    Mumbai Trans Harbour Link         yes
          Namnetum Street                   yes
          Rajiv Gandhi Sea Link             yes
          Turbhe                            yes
          Vesava                            yes

[580 rows x 40 columns]

In [307]:
df_loc_final=pd.concat([df_loca_train_and_test,df_loca_for_prediction])

In [309]:
df_loc_final.to_csv(r'D:\Sociometrik\rent prediction\check.csv')

In [343]:
df_loc_final.rename(columns={'average_monthly_residential_rental_price':'locality_rental_price'},inplace=True)

In [393]:
df_me=df_loc_final[['locality_rental_price','prediction']]

In [394]:
df_me=df_me.reset_index()
df_me

         t_name                   locality  locality_rental_price prediction
0     Bengaluru        Aanchepalya Village              27.650000        old
1     Bengaluru                Aavalahalli              13.694000        old
2     Bengaluru                   Abbigere              10.975000        old
3     Bengaluru        Adarsh Palm Retreat              27.200000        old
4     Bengaluru       Adde Vishwanathapura              25.220000        old
...         ...                        ...                    ...        ...
1490     Mumbai  Mumbai Trans Harbour Link              47.821097        yes
1491     Mumbai            Namnetum Street              65.734745        yes
1492     Mumbai      Rajiv Gandhi Sea Link              32.179506        yes
1493     Mumbai                     Turbhe              51.919306        yes
1494     Mumbai                     Vesava              32.850992        yes

[1495 rows x 4 columns]

In [395]:
df_merged = df.merge(df_me,on=['t_name','locality'],how='left')

In [367]:
df_merged.to_csv(r'D:\Sociometrik\rent prediction\check_1.csv')

In [400]:
df_merged[(df_merged['average_monthly_residential_rental_price'].isnull())& (df_merged['prediction']=='old')]

Empty DataFrame
Columns: [hexid08, t_name, locality, green_space_density, public_infrastructure_index, transportation_hubs, total_digital_consumers, pop_density_per_sqm, building_density_per_sqm, luxery_percentage, auto_dealership, auto_service_maintenance, motorcycle_dealership, truck_dealership, government_office, higher_education, library, amusement_park, bowling_centre, cinema, golf_course, ice_skating_rink, museum, nightlife, sports_centre, hospital, industrial_zone, police_station, clothing_store, consumer_electronics_store, convenience_store, department_store, grocery_store, home_specialty_store, office_supply_services_store, petrol_gasoline_station, sporting_goods_store, airport, bus_station, train_station, hotel, average_monthly_residential_rental_price, locality_rental_price, prediction]
Index: []

[0 rows x 44 columns]

In [398]:
for i in df_merged[(df_merged['average_monthly_residential_rental_price'].isnull())& (df_merged['prediction']=='old')].index:
    print(df_merged['average_monthly_residential_rental_price'][i],'---',df_merged['locality_rental_price'][i])
    df_merged['average_monthly_residential_rental_price'][i]=df_merged['locality_rental_price'][i]

nan --- 16.33971292
nan --- 12.109266043333333
nan --- 12.109266043333333
nan --- 7.96504271
nan --- 22.89989742775
nan --- 22.89989742775
nan --- 22.89989742775
nan --- 12.968627415
nan --- 22.89989742775
nan --- 7.96504271
nan --- 15.00295864577778
nan --- 22.89989742775
nan --- 15.062740733333333
nan --- 39.39393939
nan --- 15.062740733333333
nan --- 15.00295864577778
nan --- 15.00295864577778
nan --- 15.062740733333333
nan --- 15.062740733333333
nan --- 24.99799926
nan --- 23.77626358
nan --- 41.664035090999995
nan --- 41.664035090999995
nan --- 10.389784948500001
nan --- 33.0935979255
nan --- 41.664035090999995
nan --- 41.664035090999995
nan --- 11.14130435
nan --- 41.664035090999995
nan --- 41.664035090999995
nan --- 41.664035090999995
nan --- 19.966320316666668
nan --- 15.0
nan --- 14.917259598333333
nan --- 12.972923235
nan --- 17.879740556666665
nan --- 33.5396266605
nan --- 16.623094974333334
nan --- 17.879740556666665
nan --- 17.879740556666665
nan --- 17.879740556666665
nan --- 17.879740556666665
nan --- 17.879740556666665
nan --- 17.29032258
nan --- 17.83142736
nan --- 20.1011378
nan --- 25.0993516
nan --- 41.664035090999995
nan --- 39.39393939
nan --- 15.00295864577778
nan --- 39.39393939
nan --- 27.387233285
nan --- 19.931251645
nan --- 15.062740733333333
nan --- 25.0993516
nan --- 26.570870663333334
nan --- 15.00295864577778
nan --- 39.39393939
nan --- 17.60848212
nan --- 17.60848212
nan --- 12.109266043333333
nan --- 10.18744906
nan --- 10.18744906
nan --- 15.062740733333333
nan --- 15.062740733333333
nan --- 15.062740733333333
nan --- 15.062740733333333
nan --- 25.0993516
nan --- 20.25
nan --- 20.25
nan --- 20.25
nan --- 20.25
nan --- 20.25
nan --- 20.25
nan --- 22.41301900925
nan --- 91.66666667
nan --- 91.66666667
nan --- 20.25
nan --- 22.613406434
nan --- 91.66666667
nan --- 22.41301900925
nan --- 22.41301900925
nan --- 22.613406434
nan --- 28.73469388
nan --- 28.73469388
nan --- 65.78183920216664
nan --- 65.78183920216664
nan --- 25.292558523333337
nan --- 25.292558523333337
nan --- 21.96176822
nan --- 21.96176822
nan --- 21.96176822
nan --- 21.96176822
nan --- 21.96176822
nan --- 21.96176822
nan --- 21.96176822
nan --- 21.96176822
nan --- 21.96176822
nan --- 21.96176822
nan --- 21.96176822
nan --- 21.96176822
nan --- 21.96176822
nan --- 21.96176822
nan --- 21.96176822
nan --- 21.96176822
nan --- 21.96176822
nan --- 27.62317141666667
nan --- 27.62317141666667
nan --- 24.07659852333333
nan --- 22.41301900925
nan --- 24.07659852333333
nan --- 29.21412301
nan --- 91.66666667
nan --- 17.145479823333336
nan --- 17.145479823333336
nan --- 17.145479823333336
nan --- 22.613406434
nan --- 22.41301900925
nan --- 22.613406434
nan --- 22.41301900925
nan --- 17.145479823333336
nan --- 27.62317141666667
nan --- 27.62317141666667
nan --- 27.62317141666667
nan --- 27.62317141666667
nan --- 14.78864353
nan --- 27.62317141666667
nan --- 27.62317141666667
nan --- 27.62317141666667
nan --- 27.62317141666667
nan --- 17.145479823333336
nan --- 17.145479823333336
nan --- 27.62317141666667
nan --- 17.145479823333336
nan --- 28.276563245
nan --- 28.276563245
nan --- 29.57403131
nan --- 25.292558523333337
nan --- 22.41301900925
nan --- 22.41301900925
nan --- 22.41301900925
nan --- 25.292558523333337
nan --- 65.78183920216664
nan --- 65.78183920216664
nan --- 29.57403131
nan --- 22.41301900925
nan --- 22.41301900925
nan --- 42.14624238
nan --- 16.05256987
nan --- 16.05256987
nan --- 91.66666667
nan --- 91.66666667
nan --- 91.66666667
nan --- 91.66666667
nan --- 35.830492625
nan --- 21.96176822
nan --- 16.05256987
nan --- 16.05256987
nan --- 17.145479823333336
nan --- 16.05256987
nan --- 16.05256987
nan --- 17.145479823333336
nan --- 17.145479823333336
nan --- 40.45260242966665
nan --- 45.19318855
nan --- 40.45260242966665
nan --- 40.45260242966665
nan --- 83.33333333
nan --- 27.129647468625002
nan --- 24.637790629999998
nan --- 27.129647468625002
nan --- 19.32121743
nan --- 19.54484712
nan --- 27.129647468625002
nan --- 19.54484712
nan --- 19.381277975
nan --- 27.129647468625002
nan --- 25.292558523333337
nan --- 27.129647468625002
nan --- 25.292558523333337
nan --- 27.129647468625002
nan --- 27.129647468625002
nan --- 27.129647468625002
nan --- 27.129647468625002
nan --- 27.129647468625002
nan --- 27.129647468625002
nan --- 39.981087692
nan --- 19.54484712
nan --- 50.30119746499999
nan --- 25.292558523333337
nan --- 25.292558523333337
nan --- 25.292558523333337
nan --- 25.292558523333337
nan --- 24.811983490625
nan --- 24.811983490625
nan --- 18.88888889
nan --- 18.88888889
nan --- 18.88888889
nan --- 24.811983490625
nan --- 24.811983490625
nan --- 24.811983490625
nan --- 1.0
nan --- 24.811983490625
nan --- 14.08736191
nan --- 24.811983490625
nan --- 18.88888889
nan --- 1.0
nan --- 18.88888889
nan --- 24.811983490625
nan --- 18.88888889
nan --- 18.88888889
nan --- 24.811983490625
nan --- 24.811983490625
nan --- 24.811983490625
nan --- 24.811983490625
nan --- 24.811983490625
nan --- 24.811983490625
nan --- 24.811983490625
nan --- 24.811983490625
nan --- 24.811983490625
nan --- 18.88888889
nan --- 18.88888889
nan --- 18.88888889
nan --- 18.469328703333332
nan --- 18.88888889
nan --- 24.26470588
nan --- 24.26470588
nan --- 18.469328703333332
nan --- 119.96153845999994
nan --- 18.469328703333332
nan --- 18.88888889
nan --- 14.78864353
nan --- 14.78864353
nan --- 18.88888889
nan --- 18.88888889
nan --- 18.88888889
nan --- 22.98865171
nan --- 64.458787765
nan --- 27.62317141666667
nan --- 24.26470588
nan --- 24.26470588
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.88888889
nan --- 18.88888889
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.88888889
nan --- 18.88888889
nan --- 18.88888889
nan --- 18.88888889
nan --- 18.88888889
nan --- 18.88888889
nan --- 10.429175464
nan --- 10.429175464
nan --- 14.08736191
nan --- 13.0585054
nan --- 18.378850443333334
nan --- 13.46375144
nan --- 24.811983490625
nan --- 24.811983490625
nan --- 13.46375144
nan --- 36.66666667
nan --- 36.66666667
nan --- 14.78864353
nan --- 14.78864353
nan --- 14.78864353
nan --- 17.145479823333336
nan --- 33.180126307500004
nan --- 17.145479823333336
nan --- 33.180126307500004
nan --- 22.5
nan --- 22.5
nan --- 1.0
nan --- 1.0
nan --- 18.88888889
nan --- 18.88888889
nan --- 25.504886293333332
nan --- 23.48934863
nan --- 24.811983490625
nan --- 15.695061303333333
nan --- 6.730769231
nan --- 24.811983490625
nan --- 24.811983490625
nan --- 6.730769231
nan --- 24.811983490625
nan --- 24.811983490625
nan --- 11.890101175
nan --- 11.890101175
nan --- 13.93939394
nan --- 13.93939394
nan --- 13.93939394
nan --- 14.7114159225
nan --- 15.695061303333333
nan --- 14.7114159225
nan --- 24.46114577
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 19.009226812
nan --- 16.63974418766667
nan --- 29.19958582875
nan --- 10.0
nan --- 13.27682604
nan --- 10.0
nan --- 13.27682604
nan --- 13.27682604
nan --- 13.27682604
nan --- 13.27682604
nan --- 13.27682604
nan --- 62.5
nan --- 62.5
nan --- 24.811983490625
nan --- 13.27682604
nan --- 13.27682604
nan --- 11.11111111
nan --- 10.0
nan --- 10.0
nan --- 10.0
nan --- 11.11111111
nan --- 15.695061303333333
nan --- 11.11111111
nan --- 119.96153845999994
nan --- 48.88888889
nan --- 63.42015855
nan --- 63.42015855
nan --- 24.5613548175
nan --- 119.96153845999994
nan --- 48.88888889
nan --- 48.88888889
nan --- 63.42015855
nan --- 24.0
nan --- 53.8862782
nan --- 36.418053315
nan --- 36.418053315
nan --- 24.5613548175
nan --- 34.32912432
nan --- 24.5613548175
nan --- 100.0
nan --- 100.0
nan --- 24.0
nan --- 21.59025523
nan --- 18.601211173333333
nan --- 19.61038961
nan --- 26.797779875
nan --- 26.797779875
nan --- 26.797779875
nan --- 19.61038961
nan --- 26.797779875
nan --- 32.76404494
nan --- 32.76404494
nan --- 24.888855145
nan --- 32.76404494
nan --- 24.888855145
nan --- 37.24137931
nan --- 37.24137931
nan --- 39.62324107
nan --- 39.62324107
nan --- 86.64743589499997
nan --- 100.0
nan --- 39.039757505000004
nan --- 100.0
nan --- 34.12887828
nan --- 100.0
nan --- 100.0
nan --- 100.0
nan --- 64.458787765
nan --- 39.039757505000004
nan --- 64.458787765
nan --- 56.04140063
nan --- 42.021641005
nan --- 33.49287282428572
nan --- 97.19522355
nan --- 119.96153845999994
nan --- 24.888855145
nan --- 56.319033876000006
nan --- 36.873462785
nan --- 31.569957346666666
nan --- 31.569957346666666
nan --- 95.69505494499998
nan --- 34.375
nan --- 20.47141302
nan --- 28.631396705
nan --- 20.47141302
nan --- 28.631396705
nan --- 28.631396705
nan --- 28.631396705
nan --- 68.42105263
nan --- 22.89537087
nan --- 39.66507845476189
nan --- 39.66507845476189
nan --- 39.66507845476189
nan --- 39.66507845476189
nan --- 39.66507845476189
nan --- 39.66507845476189
nan --- 39.66507845476189
nan --- 39.66507845476189
nan --- 39.66507845476189
nan --- 24.5613548175
nan --- 21.75241886
nan --- 39.66507845476189
nan --- 39.66507845476189
nan --- 39.66507845476189
nan --- 36.873462785
nan --- 39.66507845476189
nan --- 39.66507845476189
nan --- 39.66507845476189
nan --- 39.66507845476189
nan --- 36.873462785
nan --- 39.66507845476189
nan --- 36.873462785
nan --- 24.0
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 24.0
nan --- 24.0
nan --- 24.0
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 24.0
nan --- 24.0
nan --- 100.0
nan --- 24.0
nan --- 29.98543402
nan --- 18.469328703333332
nan --- 28.14779027
nan --- 29.98543402
nan --- 29.828397795
nan --- 29.828397795
nan --- 29.828397795
nan --- 29.828397795
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.469328703333332
nan --- 18.51699109
nan --- 33.38321707666666
nan --- 15.50575409
nan --- 28.70664766
nan --- 28.70664766
nan --- 24.682285306666667
nan --- 22.85714286
nan --- 14.79850802
nan --- 16.12903226
nan --- 30.256833325000002
nan --- 25.68622165
nan --- 16.12903226
nan --- 16.12903226
nan --- 29.86883376
nan --- 21.21342048
nan --- 39.85093232
nan --- 38.38174274
nan --- 33.65760657
nan --- 34.64799842
nan --- 27.11271082
nan --- 31.100363865
nan --- 39.85093232
nan --- 14.136513386666666
nan --- 14.136513386666666
nan --- 14.136513386666666
nan --- 14.136513386666666
nan --- 14.136513386666666
nan --- 14.136513386666666
nan --- 14.64630726
nan --- 14.136513386666666
nan --- 16.219899165
nan --- 16.219899165
nan --- 16.219899165
nan --- 16.219899165
nan --- 16.219899165
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 22.96819788
nan --- 22.96819788
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 22.96819788
nan --- 52.220376378999944
nan --- 22.96819788
nan --- 22.96819788
nan --- 52.220376378999944
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 14.595337626666668
nan --- 8.955223881
nan --- 22.68307328
nan --- 16.33619948
nan --- 22.68307328
nan --- 18.73341003
nan --- 16.12903226
nan --- 14.98731106
nan --- 14.98731106
nan --- 15.0862069
nan --- 14.771384306666667
nan --- 14.771384306666667
nan --- 13.50665821
nan --- 13.50665821
nan --- 13.50665821
nan --- 13.50665821
nan --- 31.621146365
nan --- 33.82811884
nan --- 17.85714286
nan --- 33.03472614
nan --- 25.504886293333332
nan --- 37.689135559499974
nan --- 25.504886293333332
nan --- 18.39045288
nan --- 15.613652295
nan --- 13.364173359999999
nan --- 15.613652295
nan --- 16.33619948
nan --- 11.53324288
nan --- 16.33619948
nan --- 14.136513386666666
nan --- 14.136513386666666
nan --- 18.99613913
nan --- 14.136513386666666
nan --- 18.99613913
nan --- 14.64630726
nan --- 14.64630726
nan --- 14.64630726
nan --- 14.64630726
nan --- 14.136513386666666
nan --- 13.364173359999999
nan --- 14.93131397
nan --- 13.364173359999999
nan --- 13.364173359999999
nan --- 13.364173359999999
nan --- 31.45366959
nan --- 13.50665821
nan --- 14.93131397
nan --- 13.56488944
nan --- 16.839308235
nan --- 16.839308235
nan --- 16.25
nan --- 16.25
nan --- 16.25
nan --- 16.25
nan --- 16.25
nan --- 9.230769231
nan --- 9.230769231
nan --- 10.78431373
nan --- 16.25
nan --- 16.25
nan --- 16.25
nan --- 16.839308235
nan --- 16.839308235
nan --- 16.839308235
nan --- 13.51655629
nan --- 13.51655629
nan --- 13.51655629
nan --- 13.51655629
nan --- 13.51655629
nan --- 16.839308235
nan --- 16.839308235
nan --- 16.839308235
nan --- 16.839308235
nan --- 16.839308235
nan --- 16.839308235
nan --- 16.839308235
nan --- 16.839308235
nan --- 13.51655629
nan --- 16.839308235
nan --- 16.839308235
nan --- 16.839308235
nan --- 16.839308235
nan --- 16.839308235
nan --- 16.839308235
nan --- 48.0
nan --- 48.0
nan --- 25.625920469999997
nan --- 25.625920469999997
nan --- 25.625920469999997
nan --- 25.625920469999997
nan --- 48.0
nan --- 25.625920469999997
nan --- 48.0
nan --- 10.78431373
nan --- 10.78431373
nan --- 10.78431373
nan --- 10.78431373
nan --- 13.51655629
nan --- 13.93939394
nan --- 18.152173915
nan --- 13.93939394
nan --- 13.93939394
nan --- 13.93939394
nan --- 13.93939394
nan --- 13.93939394
nan --- 13.93939394
nan --- 13.93939394
nan --- 13.93939394
nan --- 13.93939394
nan --- 13.93939394
nan --- 18.62244898
nan --- 18.62244898
nan --- 18.62244898
nan --- 18.62244898
nan --- 18.62244898
nan --- 18.62244898
nan --- 18.62244898
nan --- 12.5
nan --- 12.5
nan --- 18.62244898
nan --- 11.11111111
nan --- 18.62244898
nan --- 12.5
nan --- 18.62244898
nan --- 85.71428571
nan --- 85.71428571
nan --- 85.71428571
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 22.53521127
nan --- 22.53521127
nan --- 15.89123559
nan --- 22.53521127
nan --- 19.64578779
nan --- 19.64578779
nan --- 22.53521127
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 19.64578779
nan --- 29.0409961205
nan --- 32.26583022666667
nan --- 29.0409961205
nan --- 32.26583022666667
nan --- 11.66666667
nan --- 11.66666667
nan --- 11.66666667
nan --- 11.66666667
nan --- 20.04008016
nan --- 28.631396705
nan --- 28.631396705
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 33.883539469999995
nan --- 11.66666667
nan --- 33.883539469999995
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 15.377104376666665
nan --- 15.89123559
nan --- 15.764151705
nan --- 17.61904762
nan --- 40.25157233
nan --- 15.89123559
nan --- 15.89123559
nan --- 16.63974418766667
nan --- 24.46808511
nan --- 16.63974418766667
nan --- 16.63974418766667
nan --- 15.764151705
nan --- 15.764151705
nan --- 20.48040455
nan --- 20.48040455
nan --- 18.152173915
nan --- 18.152173915
nan --- 20.48040455
nan --- 20.48040455
nan --- 18.152173915
nan --- 15.89123559
nan --- 15.89123559
nan --- 20.48040455
nan --- 15.89123559
nan --- 20.48040455
nan --- 20.48040455
nan --- 18.152173915
nan --- 18.152173915
nan --- 30.37910474
nan --- 90.34221501499997
nan --- 20.04008016
nan --- 20.04008016
nan --- 22.53521127
nan --- 22.53521127
nan --- 30.043499045
nan --- 90.34221501499997
nan --- 90.34221501499997
nan --- 30.098387334999998
nan --- 30.098387334999998
nan --- 17.61904762
nan --- 11.66666667
nan --- 21.5
nan --- 21.5
nan --- 11.66666667
nan --- 29.0409961205
nan --- 11.66666667
nan --- 11.66666667
nan --- 16.839308235
nan --- 18.636363635000002
nan --- 18.636363635000002
nan --- 18.636363635000002
nan --- 18.636363635000002
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 11.66666667
nan --- 29.0409961205
nan --- 11.66666667
nan --- 21.5
nan --- 21.5
nan --- 16.839308235
nan --- 16.839308235
nan --- 11.66666667
nan --- 16.839308235
nan --- 16.839308235
nan --- 51.85185185
nan --- 21.5
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 33.883539469999995
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 12.30769231
nan --- 29.0409961205
nan --- 12.30769231
nan --- 12.30769231
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 29.0409961205
nan --- 51.85185185
nan --- 18.636363635000002
nan --- 20.48040455
nan --- 20.48040455
nan --- 20.48040455
nan --- 20.48040455
nan --- 20.48040455
nan --- 20.48040455
nan --- 20.48040455
nan --- 20.48040455
nan --- 51.85185185
nan --- 18.636363635000002
nan --- 51.85185185
nan --- 51.85185185
nan --- 51.85185185
nan --- 51.85185185
nan --- 21.1035457188
nan --- 32.34323432
nan --- 21.1035457188
nan --- 21.1035457188
nan --- 13.82978723
nan --- 21.1035457188
nan --- 39.66507845476189
nan --- 10.6334699
nan --- 73.47229465499997
nan --- 73.47229465499997
nan --- 18.479485886
nan --- 67.48852517499998
nan --- 22.83333333
nan --- 67.48852517499998
nan --- 22.83333333
nan --- 73.47229465499997
nan --- 67.48852517499998
nan --- 73.47229465499997
nan --- 29.410990826666666
nan --- 67.48852517499998
nan --- 73.47229465499997
nan --- 39.66507845476189
nan --- 67.48852517499998
nan --- 25.479327105
nan --- 18.479485886
nan --- 18.479485886
nan --- 67.48852517499998
nan --- 18.479485886
nan --- 25.479327105
nan --- 25.479327105
nan --- 95.91826922999996
nan --- 52.297593
nan --- 13.82978723
nan --- 53.56301607999998
nan --- 73.47229465499997
nan --- 73.47229465499997
nan --- 73.47229465499997
nan --- 20.76502732
nan --- 73.47229465499997
nan --- 73.47229465499997
nan --- 48.0
nan --- 48.0
nan --- 48.0
nan --- 48.0
nan --- 48.0
nan --- 18.479485886
nan --- 10.0
nan --- 10.0
nan --- 18.479485886
nan --- 18.479485886
nan --- 10.0
nan --- 39.1872352525
nan --- 33.883539469999995
nan --- 33.883539469999995
nan --- 33.883539469999995
nan --- 18.479485886
nan --- 18.479485886
nan --- 18.479485886
nan --- 18.479485886
nan --- 18.479485886
nan --- 33.883539469999995
nan --- 33.883539469999995
nan --- 33.883539469999995
nan --- 29.21412301
nan --- 29.21412301
nan --- 14.64010728
nan --- 14.64010728
nan --- 12.51360174
nan --- 12.308631206666666
nan --- 12.51360174
nan --- 12.308631206666666
nan --- 14.98731106
nan --- 12.308631206666666
nan --- 14.64010728
nan --- 12.308631206666666
nan --- 29.21412301
nan --- 29.21412301
nan --- 29.21412301
nan --- 29.21412301
nan --- 21.59367397
nan --- 13.22799786
nan --- 13.22799786
nan --- 13.826153606666665
nan --- 15.030176786666667
nan --- 15.030176786666667
nan --- 14.84325016
nan --- 21.59367397
nan --- 14.84325016
nan --- 21.59367397
nan --- 13.22799786
nan --- 15.030176786666667
nan --- 29.21412301
nan --- 16.900630675000002
nan --- 16.219899165
nan --- 16.219899165
nan --- 16.900630675000002
nan --- 16.219899165
nan --- 16.900630675000002
nan --- 16.900630675000002
nan --- 11.06138107
nan --- 11.06138107
nan --- 11.06138107
nan --- 18.99613913
nan --- 13.41317365
nan --- 13.41317365
nan --- 12.04488462
nan --- 15.030176786666667
nan --- 15.030176786666667
nan --- 10.3671072
nan --- 52.220376378999944
nan --- 52.220376378999944
nan --- 11.06138107
nan --- 52.220376378999944
nan --- 15.030176786666667
nan --- 13.41317365
nan --- 12.286666666666667
nan --- 12.76
nan --- 11.0
nan --- 12.76
nan --- 12.76
nan --- 8.33
nan --- 8.33
nan --- 11.0
nan --- 11.25
nan --- 11.25
nan --- 16.25
nan --- 11.25
nan --- 11.335
nan --- 25.0
nan --- 11.335
nan --- 11.335
nan --- 11.335
nan --- 11.335
nan --- 11.335
nan --- 11.335

C:\Users\chemi\AppData\Local\Temp\ipykernel_19744\3623348866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged['average_monthly_residential_rental_price'][i]=df_merged['locality_rental_price'][i]

nan --- 11.979999999999999
nan --- 14.766666666666666
nan --- 15.22
nan --- 13.33
nan --- 13.33
nan --- 13.33
nan --- 18.605
nan --- 14.766666666666666
nan --- 13.65
nan --- 15.65
nan --- 15.65
nan --- 12.02
nan --- 13.65
nan --- 12.02
nan --- 12.02
nan --- 14.287
nan --- 15.65
nan --- 14.287
nan --- 13.65
nan --- 14.13
nan --- 13.65
nan --- 12.02
nan --- 13.65
nan --- 13.65
nan --- 13.660000000000002
nan --- 14.13
nan --- 13.33
nan --- 13.33
nan --- 13.33
nan --- 13.33
nan --- 13.33
nan --- 12.07
nan --- 13.33
nan --- 13.33
nan --- 13.33
nan --- 13.33
nan --- 13.33
nan --- 13.643333333333333
nan --- 36.84
nan --- 36.84
nan --- 12.07
nan --- 36.84
nan --- 13.33
nan --- 13.33
nan --- 13.33
nan --- 13.203333333333333
nan --- 23.233
nan --- 23.233
nan --- 16.818571428571428
nan --- 13.578
nan --- 16.818571428571428
nan --- 16.818571428571428
nan --- 20.65
nan --- 12.286666666666667
nan --- 12.286666666666667
nan --- 12.286666666666667
nan --- 11.0
nan --- 11.0
nan --- 25.0
nan --- 7.75
nan --- 7.75
nan --- 12.286666666666667
nan --- 10.865
nan --- 51.768
nan --- 51.768
nan --- 51.768
nan --- 7.75
nan --- 10.865
nan --- 12.52
nan --- 21.826666666666664
nan --- 16.818571428571428
nan --- 16.818571428571428
nan --- 16.818571428571428
nan --- 12.933333333333332
nan --- 12.933333333333332
nan --- 12.933333333333332
nan --- 12.155000000000001
nan --- 15.356666666666667
nan --- 21.826666666666664
nan --- 12.155000000000001
nan --- 16.093333333333334
nan --- 22.2785
nan --- 15.433333333333332
nan --- 33.2
nan --- 11.72
nan --- 11.72
nan --- 25.249333333333336
nan --- 10.17
nan --- 10.64
nan --- 16.818571428571428
nan --- 11.72
nan --- 16.818571428571428
nan --- 16.818571428571428
nan --- 11.39
nan --- 7.75
nan --- 11.72
nan --- 20.15
nan --- 20.539142857142856
nan --- 16.956
nan --- 13.740000000000002
nan --- 19.695
nan --- 14.287
nan --- 14.287
nan --- 14.287
nan --- 19.695
nan --- 51.768
nan --- 14.287
nan --- 16.956
nan --- 16.5
nan --- 16.956
nan --- 14.287
nan --- 16.5
nan --- 19.695
nan --- 19.695
nan --- 16.5
nan --- 38.446
nan --- 16.093333333333334
nan --- 38.446
nan --- 34.995000000000005
nan --- 21.285
nan --- 21.285
nan --- 25.634999999999998
nan --- 7.26
nan --- 7.26
nan --- 11.4
nan --- 18.22
nan --- 18.22
nan --- 18.22
nan --- 18.22
nan --- 18.22
nan --- 18.22
nan --- 14.02
nan --- 18.22
nan --- 14.02
nan --- 18.22
nan --- 14.02
nan --- 12.5
nan --- 13.69
nan --- 13.69
nan --- 12.94
nan --- 12.94
nan --- 12.94
nan --- 12.94
nan --- 12.94
nan --- 17.26
nan --- 10.81
nan --- 15.56
nan --- 15.56
nan --- 17.26
nan --- 13.69
nan --- 8.37
nan --- 13.69
nan --- 14.559999999999999
nan --- 12.94
nan --- 12.94
nan --- 12.94
nan --- 27.29
nan --- 17.26
nan --- 13.33
nan --- 13.33
nan --- 13.33
nan --- 15.27
nan --- 15.27
nan --- 51.768
nan --- 51.768
nan --- 15.27
nan --- 15.27
nan --- 24.0
nan --- 51.768
nan --- 51.768
nan --- 17.865000000000002
nan --- 20.996666666666666
nan --- 15.225555555555555
nan --- 16.357999999999997
nan --- 17.865000000000002
nan --- 20.996666666666666
nan --- 14.06
nan --- 16.76
nan --- 14.06
nan --- 15.225555555555555
nan --- 12.31
nan --- 14.06
nan --- 17.865000000000002
nan --- 20.996666666666666
nan --- 15.225555555555555
nan --- 20.669999999999998
nan --- 20.996666666666666
nan --- 20.996666666666666
nan --- 15.225555555555555
nan --- 15.225555555555555
nan --- 15.225555555555555
nan --- 15.225555555555555
nan --- 25.249333333333336
nan --- 8.61
nan --- 25.645
nan --- 7.6
nan --- 10.975
nan --- 30.0
nan --- 18.834999999999997
nan --- 12.38
nan --- 13.21
nan --- 10.81
nan --- 51.768
nan --- 14.98
nan --- 15.225555555555555
nan --- 13.21
nan --- 18.3
nan --- 15.225555555555555
nan --- 10.81
nan --- 15.56
nan --- 17.73
nan --- 10.81
nan --- 15.225555555555555
nan --- 15.225555555555555
nan --- 15.225555555555555
nan --- 15.225555555555555
nan --- 15.225555555555555
nan --- 18.75
nan --- 10.81
nan --- 127.90305575999999
nan --- 127.90305575999999
nan --- 75.79377576
nan --- 75.79377576
nan --- 72.28915663
nan --- 127.90305575999999
nan --- 127.90305575999999
nan --- 112.91975016499998
nan --- 112.91975016499998
nan --- 112.91975016499998
nan --- 112.91975016499998
nan --- 112.91975016499998
nan --- 112.91975016499998
nan --- 112.91975016499998
nan --- 112.91975016499998
nan --- 112.91975016499998
nan --- 73.68421053
nan --- 73.68421053
nan --- 73.68421053
nan --- 83.48166607
nan --- 112.91975016499998
nan --- 112.91975016499998
nan --- 73.68421053
nan --- 73.68421053
nan --- 129.6502404933333
nan --- 129.6502404933333
nan --- 135.0135685
nan --- 135.0135685
nan --- 94.19498207000001
nan --- 94.19498207000001
nan --- 94.19498207000001
nan --- 85.55880528076922
nan --- 85.55880528076922
nan --- 85.55880528076922
nan --- 80.394036605
nan --- 80.394036605
nan --- 94.19498207000001
nan --- 80.394036605
nan --- 94.19498207000001
nan --- 94.19498207000001
nan --- 54.29004555191667
nan --- 21.07777445
nan --- 21.07777445
nan --- 99.07075825999999
nan --- 75.79377576
nan --- 80.70388563
nan --- 129.6502404933333
nan --- 66.58954214666666
nan --- 66.58954214666666
nan --- 111.43619450799997
nan --- 111.43619450799997
nan --- 80.021253685
nan --- 63.127692656666675
nan --- 94.1467436575
nan --- 94.1467436575
nan --- 129.6502404933333
nan --- 134.1169303
nan --- 129.6502404933333
nan --- 129.6502404933333
nan --- 80.394036605
nan --- 80.394036605
nan --- 80.394036605
nan --- 118.32079493499998
nan --- 50.13607764333333
nan --- 94.1467436575
nan --- 68.43868534
nan --- 68.43868534
nan --- 62.308125805
nan --- 80.70388563
nan --- 94.1467436575
nan --- 62.308125805
nan --- 42.0020156075
nan --- 32.891105360000005
nan --- 94.1467436575
nan --- 64.67473781333334
nan --- 64.67473781333334
nan --- 64.67473781333334
nan --- 64.67473781333334
nan --- 73.65076745
nan --- 73.65076745
nan --- 73.65076745
nan --- 73.65076745
nan --- 64.67473781333334
nan --- 73.65076745
nan --- 64.67473781333334
nan --- 30.90909091
nan --- 30.90909091
nan --- 30.90909091
nan --- 30.90909091
nan --- 30.90909091
nan --- 27.161659515
nan --- 27.161659515
nan --- 27.161659515
nan --- 30.90909091
nan --- 30.90909091
nan --- 27.161659515
nan --- 30.37974684
nan --- 30.37974684
nan --- 30.37974684
nan --- 30.90909091
nan --- 30.90909091
nan --- 30.90909091
nan --- 68.43868534
nan --- 30.90909091
nan --- 30.90909091
nan --- 30.90909091
nan --- 72.47345858666667
nan --- 72.47345858666667
nan --- 73.65076745
nan --- 68.43868534
nan --- 55.478039225714284
nan --- 68.43868534
nan --- 55.478039225714284
nan --- 55.478039225714284
nan --- 72.47345858666667
nan --- 50.89058524
nan --- 50.89058524
nan --- 30.90909091
nan --- 30.90909091
nan --- 30.90909091
nan --- 30.90909091
nan --- 30.90909091
nan --- 55.478039225714284
nan --- 30.90909091
nan --- 55.478039225714284
nan --- 30.90909091
nan --- 30.90909091
nan --- 30.90909091
nan --- 31.61222339
nan --- 31.61222339
nan --- 31.61222339
nan --- 31.61222339
nan --- 31.61222339
nan --- 45.78234675071428
nan --- 38.074250219
nan --- 45.78234675071428
nan --- 38.074250219
nan --- 46.488600661999996
nan --- 50.54945055
nan --- 32.46753247
nan --- 32.46753247
nan --- 32.46753247
nan --- 38.074250219
nan --- 38.074250219
nan --- 38.074250219
nan --- 45.78234675071428
nan --- 45.78234675071428
nan --- 46.488600661999996
nan --- 46.488600661999996
nan --- 46.488600661999996
nan --- 32.46753247
nan --- 32.46753247
nan --- 32.46753247
nan --- 33.92380343666667
nan --- 33.92380343666667
nan --- 33.92380343666667
nan --- 33.92380343666667
nan --- 37.737830296
nan --- 31.61222339
nan --- 31.61222339
nan --- 46.488600661999996
nan --- 37.737830296
nan --- 50.54945055
nan --- 50.54945055
nan --- 51.92554367083333
nan --- 51.92554367083333
nan --- 53.095741915
nan --- 85.55880528076922
nan --- 34.646254455
nan --- 34.646254455
nan --- 34.646254455
nan --- 53.095741915
nan --- 45.78234675071428
nan --- 51.92554367083333
nan --- 57.939707848333335
nan --- 51.92554367083333
nan --- 51.92554367083333
nan --- 51.92554367083333
nan --- 51.92554367083333
nan --- 51.92554367083333
nan --- 51.92554367083333
nan --- 67.3931785325
nan --- 67.3931785325
nan --- 31.61222339
nan --- 34.646254455
nan --- 31.61222339
nan --- 21.07777445
nan --- 21.07777445
nan --- 21.07777445
nan --- 21.07777445
nan --- 21.07777445
nan --- 21.07777445
nan --- 21.07777445
nan --- 21.07777445
nan --- 45.78234675071428
nan --- 45.78234675071428
nan --- 21.07777445
nan --- 45.78234675071428
nan --- 21.07777445
nan --- 85.55880528076922
nan --- 85.55880528076922
nan --- 85.55880528076922
nan --- 21.07777445
nan --- 21.07777445
nan --- 21.07777445
nan --- 21.07777445
nan --- 45.78234675071428
nan --- 31.61222339
nan --- 44.632523707999994
nan --- 44.632523707999994
nan --- 44.632523707999994
nan --- 31.61222339
nan --- 31.61222339
nan --- 40.579091231
nan --- 40.579091231
nan --- 68.78332092333333
nan --- 68.78332092333333
nan --- 68.78332092333333
nan --- 68.78332092333333
nan --- 83.84955823666667
nan --- 83.84955823666667
nan --- 40.0558342775
nan --- 38.54286391625
nan --- 37.22929074
nan --- 37.22929074
nan --- 83.84955823666667
nan --- 56.75754776
nan --- 39.061608272499996
nan --- 80.394036605
nan --- 54.29004555191667
nan --- 51.92554367083333
nan --- 51.92554367083333
nan --- 51.92554367083333
nan --- 51.92554367083333
nan --- 51.92554367083333
nan --- 51.92554367083333
nan --- 51.92554367083333
nan --- 57.939707848333335
nan --- 57.939707848333335
nan --- 54.29004555191667
nan --- 54.29004555191667
nan --- 51.92554367083333
nan --- 83.84955823666667
nan --- 40.51282051
nan --- 83.84955823666667
nan --- 83.84955823666667
nan --- 80.394036605
nan --- 80.394036605
nan --- 80.394036605
nan --- 32.891105360000005
nan --- 80.394036605
nan --- 83.84955823666667
nan --- 83.84955823666667
nan --- 83.84955823666667
nan --- 83.84955823666667
nan --- 39.061608272499996
nan --- 39.061608272499996
nan --- 39.061608272499996
nan --- 39.799600276
nan --- 39.799600276
nan --- 39.061608272499996
nan --- 39.799600276
nan --- 39.799600276
nan --- 39.061608272499996
nan --- 39.061608272499996
nan --- 39.061608272499996
nan --- 38.54286391625
nan --- 31.61222339
nan --- 31.61222339
nan --- 31.61222339
nan --- 38.54286391625
nan --- 38.54286391625
nan --- 38.54286391625
nan --- 31.61222339
nan --- 31.61222339
nan --- 31.61222339
nan --- 31.61222339
nan --- 31.61222339
nan --- 27.161659515
nan --- 27.161659515
nan --- 27.161659515
nan --- 37.5
nan --- 40.68767908
nan --- 34.41558442
nan --- 42.0020156075
nan --- 55.478039225714284
nan --- 68.78332092333333
nan --- 54.46808511
nan --- 54.46808511
nan --- 98.17349121999999
nan --- 34.41558442
nan --- 98.17349121999999
nan --- 27.161659515
nan --- 55.478039225714284
nan --- 98.17349121999999
nan --- 55.478039225714284
nan --- 55.478039225714284
nan --- 68.78332092333333
nan --- 68.78332092333333
nan --- 34.41558442
nan --- 12.5
nan --- 24.53
nan --- 12.5
nan --- 11.25
nan --- 11.25
nan --- 11.25
nan --- 12.34
nan --- 11.25
nan --- 11.25
nan --- 14.153333333333334
nan --- 14.153333333333334
nan --- 14.62
nan --- 24.211666666666666
nan --- 24.211666666666666
nan --- 24.211666666666666
nan --- 24.211666666666666
nan --- 24.211666666666666
nan --- 33.644999999999996
nan --- 34.2636
nan --- 24.211666666666666
nan --- 21.24
nan --- 21.24
nan --- 24.53
nan --- 24.53
nan --- 21.24
nan --- 21.24
nan --- 21.24
nan --- 27.21
nan --- 21.24
nan --- 27.21
nan --- 21.24
nan --- 24.53
nan --- 24.53
nan --- 24.53
nan --- 51.768
nan --- 11.35
nan --- 51.768
nan --- 20.0
nan --- 51.768
nan --- 11.43
nan --- 11.43
nan --- 11.43
nan --- 11.43
nan --- 30.16
nan --- 30.16
nan --- 30.16
nan --- 10.0
nan --- 30.16
nan --- 10.0
nan --- 19.198333333333334
nan --- 24.211666666666666
nan --- 24.211666666666666
nan --- 24.211666666666666
nan --- 18.345764705882353
nan --- 18.345764705882353
nan --- 18.345764705882353
nan --- 51.768
nan --- 11.43
nan --- 14.48
nan --- 12.34
nan --- 24.211666666666666
nan --- 24.211666666666666
nan --- 19.198333333333334
nan --- 18.345764705882353
nan --- 11.43
nan --- 19.198333333333334
nan --- 14.62
nan --- 14.62
nan --- 14.62
nan --- 13.54
nan --- 14.47
nan --- 14.47
nan --- 16.35
nan --- 16.35
nan --- 10.58
nan --- 10.58
nan --- 10.58
nan --- 10.58
nan --- 14.55
nan --- 16.35
nan --- 16.35
nan --- 11.54
nan --- 10.33
nan --- 14.47
nan --- 14.47
nan --- 10.33
nan --- 11.54
nan --- 11.54
nan --- 8.89
nan --- 13.780000000000001
nan --- 19.224999999999998
nan --- 15.656666666666666
nan --- 24.573333333333334
nan --- 21.354000000000003
nan --- 23.115
nan --- 19.224999999999998
nan --- 19.224999999999998
nan --- 19.224999999999998
nan --- 19.224999999999998
nan --- 23.473333333333333
nan --- 11.53
nan --- 11.53
nan --- 24.573333333333334
nan --- 17.57
nan --- 17.206666666666667
nan --- 22.00257142857143
nan --- 28.352666666666668
nan --- 34.2636
nan --- 27.8
nan --- 20.815
nan --- 34.2636
nan --- 27.8
nan --- 47.74
nan --- 27.8
nan --- 23.46666666666667
nan --- 25.18
nan --- 27.8
nan --- 47.74
nan --- 34.2636
nan --- 29.55
nan --- 34.2636
nan --- 27.2
nan --- 24.573333333333334
nan --- 34.2636
nan --- 34.2636
nan --- 24.573333333333334
nan --- 24.573333333333334
nan --- 34.2636
nan --- 22.14875
nan --- 34.2636
nan --- 34.2636
nan --- 17.84
nan --- 26.47
nan --- 47.74
nan --- 47.74
nan --- 18.087
nan --- 18.087
nan --- 18.087
nan --- 7.26
nan --- 28.32
nan --- 7.26
nan --- 12.31
nan --- 18.087
nan --- 11.53
nan --- 11.53
nan --- 28.32
nan --- 18.087
nan --- 13.306666666666667
nan --- 13.306666666666667
nan --- 13.306666666666667
nan --- 12.43
nan --- 12.76
nan --- 7.26
nan --- 13.64
nan --- 12.43
nan --- 13.306666666666667
nan --- 18.087
nan --- 18.087
nan --- 25.0
nan --- 51.768
nan --- 51.768
nan --- 51.768
nan --- 12.38
nan --- 18.22
nan --- 11.77
nan --- 18.22
nan --- 18.22
nan --- 13.73
nan --- 23.473333333333333
nan --- 13.203333333333333
nan --- 16.835
nan --- 16.835
nan --- 16.835
nan --- 14.02
nan --- 28.32
nan --- 11.53
nan --- 16.835
nan --- 28.32
nan --- 31.31
nan --- 12.15
nan --- 14.81
nan --- 25.266000000000002
nan --- 12.15
nan --- 25.266000000000002
nan --- 12.15
nan --- 27.21
nan --- 27.2
nan --- 16.19666666666667
nan --- 17.55
nan --- 15.27
nan --- 17.55
nan --- 15.27
nan --- 14.836666666666666
nan --- 17.55
nan --- 12.15
nan --- 18.087
nan --- 18.087
nan --- 14.65
nan --- 20.765
nan --- 12.38
nan --- 12.38
nan --- 12.38
nan --- 12.9
nan --- 12.38
nan --- 12.38
nan --- 12.9
nan --- 12.16
nan --- 13.693999999999999
nan --- 21.74
nan --- 17.19
nan --- 30.16
nan --- 30.16
nan --- 21.74
nan --- 25.45288888888889
nan --- 25.45288888888889
nan --- 13.73
nan --- 20.72
nan --- 25.45288888888889
nan --- 25.45288888888889
nan --- 20.55
nan --- 20.55
nan --- 20.55
nan --- 51.768
nan --- 19.25
nan --- 51.768
nan --- 11.96
nan --- 13.73
nan --- 19.1
nan --- 24.68
nan --- 18.44
nan --- 15.96
nan --- 20.669999999999998
nan --- 15.96
nan --- 18.44
nan --- 28.965000000000003
nan --- 15.96
nan --- 23.6636
nan --- 27.34
nan --- 27.34
nan --- 27.34
nan --- 27.34
nan --- 27.34
nan --- 43.294
nan --- 27.34
nan --- 13.33
nan --- 13.78
nan --- 14.07
nan --- 8.46
nan --- 8.46
nan --- 17.355
nan --- 11.979999999999999
nan --- 43.294
nan --- 30.0
nan --- 15.36
nan --- 17.355
nan --- 16.13
nan --- 27.29
nan --- 17.73
nan --- 15.56
nan --- 16.67
nan --- 11.979999999999999
nan --- 11.979999999999999
nan --- 11.979999999999999
nan --- 43.294
nan --- 43.294
nan --- 11.8
nan --- 51.768
nan --- 18.3
nan --- 17.05
nan --- 43.294
nan --- 12.94
nan --- 27.29
nan --- 43.294
nan --- 43.294
nan --- 20.869999999999997
nan --- 20.869999999999997
nan --- 18.345764705882353
nan --- 18.345764705882353
nan --- 18.345764705882353
nan --- 18.345764705882353
nan --- 16.785
nan --- 16.785
nan --- 24.211666666666666
nan --- 22.14875
nan --- 35.43
nan --- 22.71666666666667
nan --- 47.74
nan --- 21.3275
nan --- 20.68
nan --- 20.68
nan --- 10.75
nan --- 20.68
nan --- 14.15
nan --- 12.38
nan --- 12.87
nan --- 12.87
nan --- 12.87
nan --- 13.693999999999999
nan --- 12.16
nan --- 13.693999999999999
nan --- 13.693999999999999
nan --- 17.19
nan --- 13.64
nan --- 18.087
nan --- 25.0
nan --- 14.65
nan --- 25.0
nan --- 25.0
nan --- 25.0
nan --- 25.0
nan --- 12.88

In [399]:
df_merged[df_merged['average_monthly_residential_rental_price'].isnull()]

,hexid08,t_name,locality,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,...,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price,locality_rental_price,prediction
5,883cf28967fffff,Kolkata,Belgachia,0.307185,4.03,5,3899,0.021658,0.002213,0.210287,...,0,3,0,0,1,1,0,NaN,29.551999,yes
15,883cf2c017fffff,Kolkata,Maheshtala,0.937926,0.00,0,6494,0.001638,0.001138,0.322581,...,0,0,0,0,0,0,0,NaN,22.645518,yes
16,883cf2c021fffff,Kolkata,Khagramuri,0.924247,0.00,0,7640,0.001635,0.000687,NaN,...,0,0,0,0,0,0,0,NaN,22.698264,yes
17,883cf2c023fffff,Kolkata,Nahazari,0.856617,0.00,0,9469,0.002108,0.001337,0.291667,...,0,0,0,0,0,0,0,NaN,21.598440,yes
18,883cf2c027fffff,Kolkata,Khagramuri,0.908145,0.00,0,5494,0.000509,0.001147,0.433333,...,0,0,0,0,0,0,0,NaN,22.698264,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5707,88618935a5fffff,Bengaluru,Harohalli,0.000000,0.00,0,801,0.000178,0.000083,0.183908,...,0,0,0,0,0,0,0,NaN,28.484577,yes
5708,88618935a7fffff,Bengaluru,Chokkasandra,0.000000,0.00,0,793,0.000537,0.000243,0.132275,...,0,0,0,0,0,0,0,NaN,35.776566,yes
5709,88618935abfffff,Bengaluru,Kaggalipura,0.060000,2.12,0,622,0.000245,0.000108,0.250000,...,0,0,0,0,0,0,0,NaN,30.000429,yes
5710,88618935adfffff,Bengaluru,Kaggalipura,0.010000,9.25,0,811,0.000505,0.000162,0.393939,...,0,0,0,0,0,0,0,NaN,30.000429,yes
5719,88618935d7fffff,Bengaluru,Heelalige,0.040000,3.91,0,449,0.003792,0.000455,0.379845,...,0,0,0,0,0,0,0,NaN,26.492822,yes

In [468]:
df_merged.to_csv(r'D:\Sociometrik\rent prediction\check_2.csv')

In [492]:
df_merged

,hexid08,t_name,locality,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,...,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price,locality_rental_price,prediction
0,883cf28945fffff,Kolkata,Sinthi,0.086059,6.84,5,3982,0.056038,0.004971,0.244236,...,0,0,0,0,1,0,0,13.491124,13.491124,old
1,883cf28949fffff,Kolkata,Baranagar,0.169749,4.10,0,3725,0.037358,0.004139,0.309732,...,0,0,0,0,0,0,0,10.000000,12.109266,old
2,883cf2894dfffff,Kolkata,Baranagar,0.311278,0.37,0,3403,0.030660,0.003579,0.469274,...,0,0,0,0,0,0,0,10.575139,12.109266,old
3,883cf28961fffff,Kolkata,Paikpara,0.232866,11.60,0,4111,0.028392,0.003431,0.341649,...,3,0,1,0,0,0,0,22.123577,21.333435,old
4,883cf28965fffff,Kolkata,Tala,0.149823,13.25,5,4157,0.029187,0.001848,0.277745,...,0,0,0,0,2,2,1,16.339713,16.339713,old
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5715,88618935b9fffff,Bengaluru,Gulimangala,0.070000,0.59,0,673,0.000576,0.000144,0.357143,...,0,0,0,0,0,0,0,25.000000,25.000000,old
5716,88618935bbfffff,Bengaluru,Gulimangala,0.130000,1.42,0,719,0.000872,0.000160,0.250000,...,0,0,0,0,0,0,0,25.000000,25.000000,old
5717,88618935bdfffff,Bengaluru,Gulimangala,0.180000,0.40,0,644,0.000934,0.000280,0.215470,...,0,0,0,0,0,0,0,25.000000,25.000000,old
5718,88618935d3fffff,Bengaluru,Bommasandra Village,0.050000,0.00,0,409,0.005783,0.000334,0.409326,...,0,0,0,0,0,0,0,12.880000,12.880000,old
5719,88618935d7fffff,Bengaluru,Heelalige,0.040000,3.91,0,449,0.003792,0.000455,0.379845,...,0,0,0,0,0,0,0,NaN,26.492822,yes

In [435]:
for i in df_merged['t_name'].unique():
    print(i)
    for j in df_merged[df_merged['t_name']==i]['locality'].unique():
        print(j)
        if df_merged[(df_merged['t_name']==i)& (df_merged['locality']==j)]['hexid08'].count()==2:
            print(df_merged[(df_merged['t_name']==i)& (df_merged['locality']==j)]['average_monthly_residential_rental_price'])

Kolkata
Sinthi
Baranagar
Paikpara
3    21.333435
7    21.333435
Name: locality_rental_price, dtype: float64
Tala
4    16.339713
8    16.339713
Name: locality_rental_price, dtype: float64
Belgachia
Satpukur
Sarsuna
Maheshtala
Khagramuri
Nahazari
Khanberia
Rasapunja
Chandigarh
Joka
Nabapally
29    10.481083
37    10.481083
Name: locality_rental_price, dtype: float64
Paschim Barisha
Paschim Putiary
Thakurpukur
Purba Barisha
Hanspukuria
Chak Rajumolla
44    24.090409
79    24.090409
Name: locality_rental_price, dtype: float64
Banagram
Kalua
Chatterjee Para
Subhas Nagar
Behala
Barisha
58     11.5422
248    11.5422
Name: locality_rental_price, dtype: float64
Bagpota
64    20.668292
69    20.668292
Name: locality_rental_price, dtype: float64
Kalagachhia
Dakshin Kazirhat
Bhasa
72    24.537149
81    24.537149
Name: locality_rental_price, dtype: float64
Uttar Kazirhat
Bagi
Amgachhi
Uttar Gauripur
82     24.125455
307    24.125455
Name: locality_rental_price, dtype: float64
Khariberia
Angarbaria
Naoabad
Garden Reach
Alipore
Taratala
100    8.246154
278    8.246154
Name: locality_rental_price, dtype: float64
Bangasree Palli
Kanchantala
106    22.525094
107    22.525094
Name: locality_rental_price, dtype: float64
Metiabruz
East Kolkata Township
112    23.776264
116    23.776264
Name: locality_rental_price, dtype: float64
Haltu
Adarsha Nagar
114    24.997999
115    24.997999
Name: locality_rental_price, dtype: float64
Dhapa
Chowbaga
119    22.071658
137    22.071658
Name: locality_rental_price, dtype: float64
Mukundapur
Pancha Sayar
Santoshpur
Tiljala
Uttar Panchanna Gram
128    11.141304
136    11.141304
Name: locality_rental_price, dtype: float64
Kasba
Topsia
Garfa
141    15.762582
143    15.762582
Name: locality_rental_price, dtype: float64
Dhakuria
Brahmapur
148    15.0
152    15.0
Name: locality_rental_price, dtype: float64
Kamdahari
Bansdroni
Garia
Patuli
154    17.590064
156    17.590064
Name: locality_rental_price, dtype: float64
New Tollygunge
Netaji Nagar
Aurobindo Park
Ashok Nagar
Regent Park
Baghajatin
Ganguli Bagan
Jadavpur
168    17.955451
254    17.955451
Name: locality_rental_price, dtype: float64
Bijoygarh
Krishnanagar
Rania
Panchpota
174    25.896775
176    25.896775
Name: locality_rental_price, dtype: float64
Khurigochhi
Dihi
Nayabad
Kantipota
Raja Bazar
Beliaghata
Tangra
Baithakkhana
Bow Bazaar
Kankurgachi
189    19.465812
193    19.465812
Name: locality_rental_price, dtype: float64
Ghose Bagan
Beniapukur
Ballygunge
Entally
198    25.158518
199    25.158518
Name: locality_rental_price, dtype: float64
Park Street Area
Jorasanko
Machuabazar
209    17.290323
217    17.290323
Name: locality_rental_price, dtype: float64
B B D Bagh
210    20.101138
226    20.101138
Name: locality_rental_price, dtype: float64
College Square
Jorabagan
212    24.60357
213    24.60357
Name: locality_rental_price, dtype: float64
Kolkata
Bagmari
215    32.629406
218    32.629406
Name: locality_rental_price, dtype: float64
Ultadanga
216    17.831427
220    17.831427
Name: locality_rental_price, dtype: float64
Shyambazar
219    21.678544
322    21.678544
Name: locality_rental_price, dtype: float64
Maniktala
Maidan
222    44.451305
224    44.451305
Name: locality_rental_price, dtype: float64
Taltala
223    33.315239
225    33.315239
Name: locality_rental_price, dtype: float64
Bow Barracks
Hastings
Chetla
232    29.870026
238    29.870026
Name: locality_rental_price, dtype: float64
Kalighat
233    31.327617
237    31.327617
Name: locality_rental_price, dtype: float64
New Alipore
234    20.827808
275    20.827808
Name: locality_rental_price, dtype: float64
Tollygunge
Golf Green
Jodhpur Park
Mominpur
Kidderpore
Bhawanipur
Elgin
Chak Balaibag
281    23.482993
284    23.482993
Name: locality_rental_price, dtype: float64
Ramkantapur
Kasthamahal
283    26.01879
308    26.01879
Name: locality_rental_price, dtype: float64
Jhanjhra
Raghabpur
Debipur
Cheyari
Hogalkuria
Danga
Karimpur Kismat
Karimpur
Raghudebpur
Rammakhaler Chak
297    23.867485
304    23.867485
Name: locality_rental_price, dtype: float64
Magurkhali
Kulerdari
Bakeswar
Majerdari
Krishnarampur
306    22.402027
310    22.402027
Name: locality_rental_price, dtype: float64
Raghunathpur
Dingelpota
Joyenpur
Satchashipara
Bagbazar
Beniatola
Char Jadubati
324    22.850827
325    22.850827
Name: locality_rental_price, dtype: float64
Dhuilya
Badartala
Rajabagan
Delhi
Sat Bari
Asola
Sainik Farm
DLF Farms
Chhattarpur
Radhey Mohan Drive
385    25.814842
389    25.814842
Name: locality_rental_price, dtype: float64
Fatehpur Beri
Chandan Hola
Juanapur
Sangam Vihar
Tughlakabad
Lal Kuan
Dera Mandi
Bhatti Kalan
Mandi
Vasant Kunj
Mehrauli
Lado Sarai
457    42.146242
544    42.146242
Name: locality_rental_price, dtype: float64
Qila Rai Pithora
Qutab Institutional Area
Ghitorni
Sultanpur
Rangpuri
Jawaharlal Nehru University
Rajokri
Pushp Vihar
Dakshinpuri
499    28.414933
501    28.414933
Name: locality_rental_price, dtype: float64
Jahapanah Forests
Alaknanda
Govindpuri
Chittaranjan
Kalkaji
Greater Kailash
Khanpur
Begumpur
Sheikh Sarai
Malviya Nagar
528    34.344061
529    34.344061
Name: locality_rental_price, dtype: float64
Sarvapriya Vihar
Panchsheel Park
Sarvodaya Enclave
Chirag Dilli
Siri Fort
Saket
Aya Nagar
Mithapur
Molarband
595    83.333333
602    83.333333
Name: locality_rental_price, dtype: float64
Badarpur
Basantpur
Trilokpuri
Vasundhara Enclave
606    19.493544
610    19.493544
Name: locality_rental_price, dtype: float64
Kondli
Gharoli
609     19.321217
2688    19.321217
Name: locality_rental_price, dtype: float64
Okhla
Sarita Vihar
Madanpur Khadar
Pul Pehlad Pur
Okhla Industrial Area
Jasola Vihar
Mangar
Paota
Dwarka
Indira Gandhi International Airport
Raj Nagar
678    19.806446
926    19.806446
Name: locality_rental_price, dtype: float64
Pushpanjali Farms
Bijwasan
Pochanpur
Dhulsiras
Kakrola
Qutab Pur
Mehram Nagar
714    32.776656
715    32.776656
Name: locality_rental_price, dtype: float64
Delhi Cantonment
Shankar Vihar
Subroto Park
722    119.961538
726    119.961538
Name: locality_rental_price, dtype: float64
Mahipalpur
Vasant Vihar
Sector 23
Raghu Pur
791    26.639298
792    26.639298
Name: locality_rental_price, dtype: float64
Badhosra
Bajghera
796    26.654776
981    26.654776
Name: locality_rental_price, dtype: float64
Nanak Heri
797     26.214836
2976    26.214836
Name: locality_rental_price, dtype: float64
Kapas Hera Estate
Palam Farms
Kapashera
841    17.172786
843    17.172786
Name: locality_rental_price, dtype: float64
Samalka
Mansi Street
Dindar Pur
Uttam Nagar
Matiala
Nawada
Goela Khurd
Taj Pur Khurd
876    20.727743
969    20.727743
Name: locality_rental_price, dtype: float64
Nangli Sakrawati
Roshan Pura
Dichaon Kalan
Bapraula
Sitapuri
Janakpuri
Mahavir Enclave
Dabri
Bindapur
915    24.461146
956    24.461146
Name: locality_rental_price, dtype: float64
Hari Nagar
Mayapuri
Fateh Nagar
Palam Village
Sadh Nagar
Palam Extension
Nasirpur
Sagar Pur
Hastsal
Vikaspuri
Tilak Nagar
944    24.295866
949    24.295866
Name: locality_rental_price, dtype: float64
Ashok Nagar
945     27.412595
2510    27.412595
Name: locality_rental_price, dtype: float64
Madhu Vihar
Rewla Kham Pur
Chhawala
Kangan Heri
Pindwala Khurd
Jhatikra
Pindwala Kalan
Paprawat
Daulat Pur
997     24.528705
1002    24.528705
Name: locality_rental_price, dtype: float64
Asalat Pur Khawad
HC Mathur Lane
IP Estate
Central Secretariat
1688 Barracks
Connaught Place
Barakhamba
1008    119.961538
1041    119.961538
Name: locality_rental_price, dtype: float64
Vikram Nagar
1010    49.118483
1011    49.118483
Name: locality_rental_price, dtype: float64
Chandni Chowk
Raj Ghat
Mandi House
Lodhi Estate
1017    119.961538
1020    119.961538
Name: locality_rental_price, dtype: float64
India Gate
Jor Bagh
1019    92.324215
1111    92.324215
Name: locality_rental_price, dtype: float64
Delhi Race Club
Pragati Maidan
Sant Nagar
National Zoological Park
1027    97.195224
1181    97.195224
Name: locality_rental_price, dtype: float64
Gole Market
Central Ridge Reserve Forest
Rajinder Nagar
Jhandewalan
Paharganj
1040    34.329124
1044    34.329124
Name: locality_rental_price, dtype: float64
President's Estate
1045    35.885927
1049    35.885927
Name: locality_rental_price, dtype: float64
Chanakyapuri
Rakab Ganj
Mandawali
Patparganj
Laxmi Nagar
Preet Vihar
Shakarpur
Gazipur
Mayur Vihar
Nangli
Pandav Nagar
Dallupura
Geeta Colony
Anand Vihar
Swasthya Vihar
Krishna Nagar
Shahdara
Yamuna Bank
Sarojini Nagar
RK Puram
Safdarjung Enclave
Netaji Nagar
BK Dutt Colony
Lodi Colony
Kidwai Nagar
South Extension I
Satya Sadan
1110    39.530391
1137    39.530391
Name: locality_rental_price, dtype: float64
Laxmi Bai Nagar
Hauz Khas
Katwaria Sarai
Munirka
1119    27.545004
1144    27.545004
Name: locality_rental_price, dtype: float64
Gulmohar Park
Sadiq Nagar
Ansari Nagar West
South Extension II
Green Park
South Moti Bagh
1127    34.128878
1133    34.128878
Name: locality_rental_price, dtype: float64
Shanti Niketan
Dhaula Kuan
Sunlight Colony
New Friends Colony
Sri Niwaspuri
1150    30.953398
1167    30.953398
Name: locality_rental_price, dtype: float64
Sidhartha Nagar
Sarai Kale Khan
Jal Vihar
Chack Chil
Sector 14A
Friends Colony West
Nehru Place
East of Kailash
1166    36.786146
1168    36.786146
Name: locality_rental_price, dtype: float64
Pragati Vihar
Nizamuddin East
Jangpura
Golf Links
Delhi - Meerut Expressway
1183    28.839746
1187    28.839746
Name: locality_rental_price, dtype: float64
Baba Banda Singh Bahadur Setu
1184    119.961538
1186    119.961538
Name: locality_rental_price, dtype: float64
Lajpat Nagar
Defence Colony
Andrews Ganj
Shastri Nagar
Gulabi Bagh
Anand Parbat
1199    68.421053
1240    68.421053
Name: locality_rental_price, dtype: float64
Sarai Rohilla
1200    34.375
1222    34.375
Name: locality_rental_price, dtype: float64
Daya Basti
Kamla Nagar
Civil Lines
Subzi Mandi
1206    84.433574
1223    84.433574
Name: locality_rental_price, dtype: float64
Roop Nagar
Delhi university Area
Shakti Nagar
Karol Bagh
Patel Nagar
Sadar Bazaar
Tri Nagar
Ashok Vihar
Priyadarshani Vihar
Gujranwala Tw
Karam Pura
1243    22.895371
1245    22.895371
Name: locality_rental_price, dtype: float64
Inderlok
Kotqali
Dariya Ganj
Khyber Pass
Khazoori Khas
1283    20.765027
2834    20.765027
Name: locality_rental_price, dtype: float64
Kashmere Gate
Mori Gate
Inder Puri
Pusa
New Rajinder Nagar
Kirti Nagar
Nariana
1314    39.31944
1316    39.31944
Name: locality_rental_price, dtype: float64
Rajouri Garden
1317    28.14779
2509    28.14779
Name: locality_rental_price, dtype: float64
Shadipur
Sahoti
Ladrawan
Pahladpur
Qutab Garh
Nizampur Khurd
Karhouli
Bazid Pur Thakran
Darya Pur Kalan
Nangal Thakran
Ochandi
Bawana
Mungesh Pur
Ferozepur Bangar
Hareoli
Katewara
Jat Khor
Barahi
Kanonda
Jakhauda
Bamnoli
Asoda Todran
Kulasi
1739    24.794962
1740    24.794962
Name: locality_rental_price, dtype: float64
Asauda Sewan
Chatesar
1747    24.375556
1751    24.375556
Name: locality_rental_price, dtype: float64
Jonti
Salahpur Majra
Sultan Pur Majra
Garhi Rindhala
Nizam Pur Rashid Pur
Lad Pur
Khairpur
Punjab Khor
Mukandpur
1777    25.487258
1780    25.487258
Name: locality_rental_price, dtype: float64
Saidpur
Pipli
Jataula
Rampur
Kundal
Thana Kalan
Gopalpur
Mamoor Pur
Bazidpur Saboli

Kundli
Narela Mandi
Tikri Khurd
Kureni
1823    28.094749
1824    28.094749
Name: locality_rental_price, dtype: float64
Bankner
Singhu
Singhola
Shafiabad Pana Paposhian
Munirpur
Nathupur
Lam Pur
Khatkar
Janti Kalan
Dahesra
Mawi Kalan Khader
1861    30.207934
2730    30.207934
Name: locality_rental_price, dtype: float64
Sankrandh Khader
Baqipur
1863    28.543797
1864    28.543797
Name: locality_rental_price, dtype: float64
Taj Pur Kalan
1866    23.834322
1950    23.834322
Name: locality_rental_price, dtype: float64
Palla
Kulakpur
1872    29.907632
2862    29.907632
Name: locality_rental_price, dtype: float64
Sersa
Nangal Kalan
Jakhauli
Manoli
Hansapur
Sanoth
Bhor Garh
Holambi Khurd
Holambi Kalan
Ghoga
Bankauli
Kham Pur
1944    28.783571
1974    28.783571
Name: locality_rental_price, dtype: float64
Hamid Pur
Sunger Pur Delhi
Ali Pur
Zind Pur
Shah Pur Garhi
Janti Khurd
1973    30.530052
1977    30.530052
Name: locality_rental_price, dtype: float64
Akbarpur Barota
Jagdishpur
Chhatera Bahadurpur
Jatheri
Kheri Mana Jat
Bidhnauli
Ladpur
Malha Majra
Abbaspur
Patla
Badh Khalsa
Seoli
Rasoi
Badh Malak
Pritampura
Nahri
Halalpur
Katlupur
Nahra
Jhinjauli
Barkatabad
Lowa Kalan
Jharoda Kalan
Balaur
Shidipur
Kair
Mundhela Khurd
Isarheri
Soldha
Nuna Majra
Lawa Khurd
Sarai Aurangabad
Neel Wal
Hiran Kudna
Bakkarwala
Jafarpur Kalan
Haibatpur
Tikri Kalan
Baqar Garh
Mundhela Kalan
Gubhana
Isa Pur
Qazi Pur
Samas Pur Khalsa
Luksar
Gangarwa
2197    29.602295
2342    29.602295
Name: locality_rental_price, dtype: float64
Majri
Mitraon
Surera
Khera Dabar
Khera
Kharkhari Nahar
2230    25.828008
2234    25.828008
Name: locality_rental_price, dtype: float64
Jaffar Pur Kalan
Kasar
Tandaheri
Kherka Musalman
Sankhol
Mandothi
Daboda Kalan
Modern Industrial Estate Part-A
Mahavir Park
Shahpur
Desalpur
Bupania
Zardakpur
Rohini
Budh Vihar
Sultanpuri
Mangolpuri
Nangloi
Baljit Vihar
Prem Nagar
2391    31.005152
2485    31.005152
Name: locality_rental_price, dtype: float64
Madanpur Dabas
2393    21.143781
2630    21.143781
Name: locality_rental_price, dtype: float64
Agar Nagar
Shalimar Bagh
Pitampura
Jahangirpuri
Adarsh Nagar
Shakurpur
Azadpur
Bhalswa
Ranhola
Nilothi
Kamruddin Nagar
2449    26.35194
2450    26.35194
Name: locality_rental_price, dtype: float64
Nihal Vihar
Paschim Vihar
Nikhil Vihar
2454    40.251572
2471    40.251572
Name: locality_rental_price, dtype: float64
Razapur Khurd
2461    24.468085
2465    24.468085
Name: locality_rental_price, dtype: float64
Mundka
Ranhola Extesion
2487    21.482836
2489    21.482836
Name: locality_rental_price, dtype: float64
Tilangpur Kotla
Punjabi Bagh
Tagore Garden Extension
Shakurbasti
Subhash Nagar
Vishnu Garden
Ramesh Nagar
2515    34.466676
2518    34.466676
Name: locality_rental_price, dtype: float64
Mansarover Garden
Sudershan Park
Moti Nagar
Bali Nagar
Sultan Pur Dabas
Puth Khurd
Karala
Chand Pur
Kanjhawala
Khera Kalan
Khera Khurd
Nangli Puna
Budhpur
Siraspur
Iradat Nagar
Rani Khera
2625    22.594439
2647    22.594439
Name: locality_rental_price, dtype: float64
Gheora
Mubarakpur Dabas
Madanpur Dabas VILLAGE
2631    21.950534
2635    21.950534
Name: locality_rental_price, dtype: float64
Saoda
2649    24.134189
2661    24.134189
Name: locality_rental_price, dtype: float64
Mandauri
Rohad
Dilshad Garden
Jhilmil Colony
2692    32.343234
2710    32.343234
Name: locality_rental_price, dtype: float64
Vivek Vihar
Gokalpuri
Saboli
2705    33.588861
2830    33.588861
Name: locality_rental_price, dtype: float64
Village Mandoli
Mavikala
Sankrod
Delhi-Sahranpur-Dehradun Expressway
Hasanpur Masoori
Delhi Eastern Peripheral Expressway
Khurrampur
Katha
2733    31.567433
2734    31.567433
Name: locality_rental_price, dtype: float64
Harampur
Lutfulapur Navada
Agraula
2753    10.63347
2754    10.63347
Name: locality_rental_price, dtype: float64
Milk Bamla
Sonia Vihar
Ilaichipur
2759    22.540932
2762    22.540932
Name: locality_rental_price, dtype: float64
Panchayara
2763    27.059991
2848    27.059991
Name: locality_rental_price, dtype: float64
Mirpur Hindu
Salem Pur Majra Burari
Madaul
Burari
Wazirabad
Gopalpur Village
GTB Nagar
2787    51.497576
2789    51.497576
Name: locality_rental_price, dtype: float64
Timarpur
Mukherjee Nagar
Sadatpur Musalmanan
Mukundpur
Model Tw
Karawal Nagar
Johripur
2821    52.297593
2828    52.297593
Name: locality_rental_price, dtype: float64
Mustafabad
Sadatpur
Tigi Pur
Jhangola
Subhanpur
Noorpur Muzbida
Allipur
2849   NaN
2888   NaN
Name: locality_rental_price, dtype: float64
Akbar Pur Majra
2853    24.435527
2855    24.435527
Name: locality_rental_price, dtype: float64
Mohd. Pur Ramzan Pur
Nanu
Hajipur
2872    25.204889
2879    25.204889
Name: locality_rental_price, dtype: float64
Hazipur Viran
Abdullapur
Kadipur
Ibrahimpur
Ibrahim Pur
Mukhmel Pur
Bodh Pur Bija Pur
Hiranki
Garhi Khasru
2924    27.184948
2925    27.184948
Name: locality_rental_price, dtype: float64
Mankrola
Iqbalpur
Kaliawas
Deorala
2939    29.256287
2960    29.256287
Name: locality_rental_price, dtype: float64
Jhanjrola
Badsa
Raota
Ghalib Pur
2961    27.233979
3069    27.233979
Name: locality_rental_price, dtype: float64
Goman Hera
Shikar Pur
Lohat
Dever Khana
Dhansa
Munda Khera
Daryapur
Badli
Lagarpur
Darya Pur Khurd
3086    25.094326
3090    25.094326
Name: locality_rental_price, dtype: float64
Ujwa
Kharkhari Rond
Hasan Pur
3092    25.605263
3093    25.605263
Name: locality_rental_price, dtype: float64
Hansnagar
Jhuljhuli
Jainpur
3101    25.445712
3103    25.445712
Name: locality_rental_price, dtype: float64
Malik Pur Zer-Najafgarh
3108    26.200598
3118    26.200598
Name: locality_rental_price, dtype: float64
Surhera
Sarang Pur
3115    26.015558
3119    26.015558
Name: locality_rental_price, dtype: float64
Mubarikpur
3120   NaN
3122   NaN
Name: locality_rental_price, dtype: float64
Asmayalpur
3123    25.448738
3124    25.448738
Name: locality_rental_price, dtype: float64
Mahmoodpur Majra
Pelhpa
3208    27.459304
3209    27.459304
Name: locality_rental_price, dtype: float64
Gurugram
Bandhwari
Gual Pahari
425     26.811923
1394    26.811923
Name: locality_rental_price, dtype: float64
Sector 54
Sector 26
574    35.152024
578    35.152024
Name: locality_rental_price, dtype: float64
Sector 24
Sector 42
Sector 26A
590     45.193189
1570    45.193189
Name: locality_rental_price, dtype: float64
Kadarpur
Rethoj
Sector 110
Palam Vihar
Palam Vihar Extensio
Sector 110A
Sector 109
769    16.332554
810    16.332554
Name: locality_rental_price, dtype: float64
Sector 23
Ashok Vihar Phase II
Sector 5
Sector 6
780     16.74351
1527    16.74351
Name: locality_rental_price, dtype: float64
Sector 3
Sector 3A
783     20.659478
1550    20.659478
Name: locality_rental_price, dtype: float64
Nangli Umarpur
Sector 23A
Babupur
Sector 113
798    17.340289
800    17.340289
Name: locality_rental_price, dtype: float64
Sector 111
Sector 112
Sector 106
Sector 103
Sector 105
Sector 20
814    28.939945
818    28.939945
Name: locality_rental_price, dtype: float64
Rajokri
Sector 25
Udyog Vihar Phase V
Sector 18
Sector 22
853    23.489349
859    23.489349
Name: locality_rental_price, dtype: float64
Sector 19
Sector 21
Sector 72
Sector 48
Sector 71
1336    18.516991
1340    18.516991
Name: locality_rental_price, dtype: float64
Sector 50
Sector 49
Sector 47
1345    22.022109
1372    22.022109
Name: locality_rental_price, dtype: float64
Sector 51
Sector 70A
1348    15.505754
1354    15.505754
Name: locality_rental_price, dtype: float64
Nurpur Jharsa
1349    23.220102
1351    23.220102
Name: locality_rental_price, dtype: float64
Palra
Badshahpur
Sector 69
1353    23.816174
1361    23.816174
Name: locality_rental_price, dtype: float64
Sector 66
Sector 68
Sector 67
Sector 74
1362    25.769581
1364    25.769581
Name: locality_rental_price, dtype: float64
Sector 73
1365    22.857143
1381    22.857143
Name: locality_rental_price, dtype: float64
Sector 34
Sector 35
1368    11.533243
1619    11.533243
Name: locality_rental_price, dtype: float64
Sector 33
Sector 38
Sector 75
Sector 70
Sector 74A
1380    30.321324
1621    30.321324
Name: locality_rental_price, dtype: float64
Sector 75A
Sector 61
1383    29.868834
1385    29.868834
Name: locality_rental_price, dtype: float64
Sector 58
1384    33.436406
1395    33.436406
Name: locality_rental_price, dtype: float64
Sector 59
1386    33.657607
1405    33.657607
Name: locality_rental_price, dtype: float64
Sector 56
Sector 62
Balola
Ghata Kanagarpur
Sector 63
1400    38.381743
1425    38.381743
Name: locality_rental_price, dtype: float64
Sector 60
1401    34.647998
1407    34.647998
Name: locality_rental_price, dtype: float64
Sector 57
Sector 52
Sector 53
Sector 55
Sector 52A
1421    26.196896
1586    26.196896
Name: locality_rental_price, dtype: float64
Sector 65
Sakatpur
Gairatpurbas
Shikohpur
Tikli
Aklimpur
1437    27.882788
1441    27.882788
Name: locality_rental_price, dtype: float64
Navrangpur
Kheri Daula
Darbaripur
Bhondsi
Sahjawas
Dhumaspur
1502    23.941377
1505    23.941377
Name: locality_rental_price, dtype: float64
Medawas
Sector 64
1506    40.785241
1507    40.785241
Name: locality_rental_price, dtype: float64
Sector 10
Sector 37C
Sector 9B
1519    8.955224
1521    8.955224
Name: locality_rental_price, dtype: float64
Sector 9
1520    17.472414
1552    17.472414
Name: locality_rental_price, dtype: float64
Sector 7
Sector 12
1523    19.903042
1596    19.903042
Name: locality_rental_price, dtype: float64
Sector 8
Sector 4
Sector 37
Sector 36
Sector 36B
Sector 10A
Sector 11
1541    20.63003
1610    20.63003
Name: locality_rental_price, dtype: float64
Sector 102
Sector 100
1544    49.6396
1545    49.6396
Name: locality_rental_price, dtype: float64
Sector 99
1548    15.086207
3020    15.086207
Name: locality_rental_price, dtype: float64
Sector 104
Sector 37D
Harsaru
Sector 41
1562    33.507396
1565    33.507396
Name: locality_rental_price, dtype: float64
Sector 29
Sector 40
Sector 16
1566    36.605492
1593    36.605492
Name: locality_rental_price, dtype: float64
Sector 30
Sector 28
DLF Phase IV
Sector 27
Sector 46
1576    27.525914
1578    27.525914
Name: locality_rental_price, dtype: float64
Sector 45
Sector 39
1580    20.636729
1582    20.636729
Name: locality_rental_price, dtype: float64
Sector 43
Sector 13
1590    33.034726
1595    33.034726
Name: locality_rental_price, dtype: float64
Sector 14
1591    17.857143
1592    17.857143
Name: locality_rental_price, dtype: float64
Sector 17
1599    18.390453
1603    18.390453
Name: locality_rental_price, dtype: float64
Sector 15
1604    22.685417
1609    22.685417
Name: locality_rental_price, dtype: float64
Sector 31
Sector 32
Civil Lines
Sihi
Sikanderpur Badha
Hayatpur
Badha
Sector 84
Sector 36A
1624    31.45367
1648    31.45367
Name: locality_rental_price, dtype: float64
Lakhnola
Harsaru Part
Nawada Fatehpur
1652    13.564889
1656    13.564889
Name: locality_rental_price, dtype: float64
Naharpur Kasan
Kankrola
Sultanpur
Budhera
Daulatabad
Dharampur
Kharki Majra Dhankot
2978    24.596732
2988    24.596732
Name: locality_rental_price, dtype: float64
Dhankot
Dhankot Part
Sadhrana
Sayyad Mohamadpur
2997    23.768859
3005    23.768859
Name: locality_rental_price, dtype: float64
Khetawas
Garhi Harsaru
Gopalpur
Gopalpur Part
Wazirpur
Hamirpur
Manesar
Khoh
3126    22.944957
3140    22.944957
Name: locality_rental_price, dtype: float64
Kasan
Bhang Rola
Dhorka
Basharia
3147    26.919218
3160    26.919218
Name: locality_rental_price, dtype: float64
Meoka
Baskushla
3159    10.367107
3163    10.367107
Name: locality_rental_price, dtype: float64
Patli Hajipur
Dhanawas
Bengaluru
Kadabagere
Chikkellur
Ramohalli
Seshagiripura
Yelachaguppe
Maragondanahalli
Krishnasagara
Yalachaguppe Ramapura
Channenahalli
Kommaghatta
Sulikere
Bheemanakuppe
Maligondanahalli
3232    11.0
3236    11.0
Name: locality_rental_price, dtype: float64
Kenchanapura
Gaudhalli
Dasanapura
Adakamaranahalli
3248    24.402895
3260    24.402895
Name: locality_rental_price, dtype: float64
Kammasandra
Kadaranahalli
Harokyathanahalli
Lakshmipura
Byandahalli
Madanayakahalli

3259    27.285781
3660    27.285781
Name: locality_rental_price, dtype: float64
Dombarahalli
3261    16.25
3648    16.25
Name: locality_rental_price, dtype: float64
Siddanahosahalli
Alur
Vaddarahalli
Narasipura
3266    27.214968
3271    27.214968
Name: locality_rental_price, dtype: float64
Mathahalli
3267    24.508654
3272    24.508654
Name: locality_rental_price, dtype: float64
Bilijaji
Kuduragere
Soladevanahalli
Thammenahalli Village
Kuduregere
Hanumantha Sagara
3285    10.17
3662    10.17
Name: locality_rental_price, dtype: float64
Hurali Chikkanahalli
Torenagasandra
3289    26.114057
3291    26.114057
Name: locality_rental_price, dtype: float64
Tharabanahalli
Agara
Badamanavarthekaval
Chinnakurchi
Gonipura
3303    25.876569
3343    25.876569
Name: locality_rental_price, dtype: float64
Vasanthanahalli
Devagere
3315    25.496591
3316    25.496591
Name: locality_rental_price, dtype: float64
Gudimavu
Gangasandra
3319    25.6076
3320    25.6076
Name: locality_rental_price, dtype: float64
Uttari
3322    27.039522
3323    27.039522
Name: locality_rental_price, dtype: float64
Kaggalipura
Kanmanike
3337    28.720789
3338    28.720789
Name: locality_rental_price, dtype: float64
Kumbalagodu Gollahalli
Thagachaguppe
Kariyana Palya
3345    18.09
3347    18.09
Name: locality_rental_price, dtype: float64
Srinivaspura
Thurahalli
Hemmigepura
Somapura
3356    8.33
3358    8.33
Name: locality_rental_price, dtype: float64
Varahasandra
RR Nagar
Sunkalpalya
3366    14.0
3367    14.0
Name: locality_rental_price, dtype: float64
Mailasandra
3369    16.79
3769    16.79
Name: locality_rental_price, dtype: float64
Kodipalya
Lingadheeranahalli
Pavamanapura
Talaghattapura
3377    14.885
3379    14.885
Name: locality_rental_price, dtype: float64
Nagegowdanapalya
3378    15.22
3385    15.22
Name: locality_rental_price, dtype: float64
Banashankari
Subramanyapura
Kodipur
Kambipura
Challegatta
Kumbalgodu
Kumbalagodu
Kumbalagudu State Forest
Kommaghatta - Krishnasagara
Kengeri Satellite Town
Venkatapura
Doddabele
Kengeri
O.B.Chudahalli
3442    25.330943
3478    25.330943
Name: locality_rental_price, dtype: float64
Kannaikana Agrahara
Lal Bahadur Shastri Nagar
Vakil Garden City
3457    21.505
3465    21.505
Name: locality_rental_price, dtype: float64
Jyotipuram
Uttarahalli -Manavarthekaval
Uttarahalli Manavarthekaval
Bilwaradahalli
Bhoothanahalli
Gulakamale
3477    29.401554
3482    29.401554
Name: locality_rental_price, dtype: float64
Gollahalli
Anjanapura Twp
Kebbattanahalli
Hegganahalli
Nagarbhavi
Sunkadakatte
Basaweshwara Nagar
Tunganagara
Kaveri Nagar
3505    14.51
3511    14.51
Name: locality_rental_price, dtype: float64
Peenya
Laggere
Byraveshwara Industrial Estate
Ragavendra Nagar
Vinayaka Nagar
State Bank of India Colony
3517    13.855
3570    13.855
Name: locality_rental_price, dtype: float64
Vijayanagar
Basaveshwar Nagar
Kamaksipalya
Annapurneshwari Nagar
Maruthi Nagar
Nandini Layout
3536    17.51
3629    17.51
Name: locality_rental_price, dtype: float64
Nagapura
Bapagrama
3540    22.967184
3543    22.967184
Name: locality_rental_price, dtype: float64
Chikka Gollarahatti
Kamath Layout
Kadabagere Cross
Gangondanahalli
KG Lakkenahalli
Bylkonehalli
Bharat Nagar
3568    12.005
3574    12.005
Name: locality_rental_price, dtype: float64
Kodigehalli
Vishveshwaraya Nagar
Seegehalli
3575    23.886791
3578    23.886791
Name: locality_rental_price, dtype: float64
Kannahalli
Lingadeeranhalli
3582    12.52
3588    12.52
Name: locality_rental_price, dtype: float64
Kachohalli
Andrahalli
Gollarapalya Hosahalli
Jalahalli
HMT Estate
Mathikere
Yeshwanthpur
T. Dasarahalli
3599    20.15
3684    20.15
Name: locality_rental_price, dtype: float64
Jalahalli East
Vidyaranyapura
Jalahalli West
Abbigere
RMV Extension Stage 2
Sanjaynagar
Doddabommasandra
Kempe Gowda Nagar
Devinagar
Chikkabidarakallu
3638    33.2
3639    33.2
Name: locality_rental_price, dtype: float64
Bagalakunte
Aanchepalya Village
Doddabidarakull
Rukmini Nagar
Madavara
KGSrikantapura
Thirumalapura
Sidedahalli
3652    10.89
3658    10.89
Name: locality_rental_price, dtype: float64
Totadaguddadahalli
Nagasandra
3669    17.92
3685    17.92
Name: locality_rental_price, dtype: float64
Kariobanahalli
MEI Employees Housing Colony
Nayanda Halli
Gnana Bharathi
Padarayana Pura
3701    34.889
3707    34.889
Name: locality_rental_price, dtype: float64
Kempapura Agrahara
Azad Nagar
Guddadahalli
Chandra Layout
Deepanjali Nagar
Banagirinagara
Thyagaraja Nagar
Banashankari Stage Ii
3719    12.175
3721    12.175
Name: locality_rental_price, dtype: float64
Chikkalasandra
Hosakerehalli
Mahantara Layout
Gavipuram Extension
Shankarapura
3731    17.16
3735    17.16
Name: locality_rental_price, dtype: float64
Chamrajpet
Basavanagudi
Nagdevanahalli
3736    13.365
3742    13.365
Name: locality_rental_price, dtype: float64
Sir M Vishweshwaraiah Layout 4th Block
Jnana Ganga Nagar
Kengeri Satellite Tw
Mallathahalli
Manganahalli
Ullal Uppanagar
3759    14.825
3763    14.825
Name: locality_rental_price, dtype: float64
Sampangiram Nagar
Srirampura
3786    25.255
3790    25.255
Name: locality_rental_price, dtype: float64
Malleshwaram
Gandhi Nagar
3789    23.155
3814    23.155
Name: locality_rental_price, dtype: float64
Sheshadripuram
Rajaji Nagar
Armane Nagar
Ganganagar
3805    18.89
5439    18.89
Name: locality_rental_price, dtype: float64
Mahalakshmi Layout
3807    34.827995
3809    34.827995
Name: locality_rental_price, dtype: float64
Sampangi Rama Nagar
Vasanth Nagar
Ashok Nagar
Shivaji Nagar
Subhash Nagar
3820    11.89
3823    11.89
Name: locality_rental_price, dtype: float64
Binnipete
Majestic
New Tharagupet
Cottonpete
Chickpet
Jayamahal
Benson Town
Hulimangala
Koppa
3835    11.4
3843    11.4
Name: locality_rental_price, dtype: float64
Bingipur
Nanjapura
Begihalli
Nallasandra
3840    25.466025
3842    25.466025
Name: locality_rental_price, dtype: float64
Ramasandra
Byrappanahalli
3844    35.467921
3849    35.467921
Name: locality_rental_price, dtype: float64
Bannerughatta
Ragihalli Forest
Mantapa
Settigere
Gadenahalli
3863    12.5
3865    12.5
Name: locality_rental_price, dtype: float64
Doddajala
Meenakunte
Byanahalli
Chikkajala
3876    17.3
4108    17.3
Name: locality_rental_price, dtype: float64
Channahalli
Bagalur
Meesaganahalli
3881    26.691106
3894    26.691106
Name: locality_rental_price, dtype: float64
Huttanahalli
Hosahalli
Hunasamaranahalli
Billamaranahalli
Sathnur Village
Maranaikara Halli
Maranayakanahalli
3896    8.37
3898    8.37
Name: locality_rental_price, dtype: float64
Vidya Nagar
Marenahalli
Sathnur
Jagalatti
Madappanahalli
Avalahalli
Krishnarajapura
Singanayakanahalli
Mutkad Halli
3921    27.081417
3922    27.081417
Name: locality_rental_price, dtype: float64
Mylappanahalli
Shivakote
3924    27.642257
3951    27.642257
Name: locality_rental_price, dtype: float64
Adde Vishwanathapura
Rajanukunte
Ittagallpura
Central Reserve Police Force Area
Lingarajapura
Kondashetti Halli
Jarakbandekaval
Honnenahalli
3944    24.0
3945    24.0
Name: locality_rental_price, dtype: float64
Adiganahalli
Nagadasanahalli
Madhugirihalli
3952    25.774734
4039    25.774734
Name: locality_rental_price, dtype: float64
Hesaraghatta
Aivarakhandapura
Tarahunase
Thimmasandra
Yelahanka
Yelahanka New Town
Vignana Kendra
Dodda Bettahalli
CRPF Area
3982    16.76
3984    16.76
Name: locality_rental_price, dtype: float64
Anantapura
3986    12.31
3994    12.31
Name: locality_rental_price, dtype: float64
Kempanahalli
Ramagondanahalli
Veerasagara
Jakkuru
Sahakara Nagar
4006    20.27
5427    20.27
Name: locality_rental_price, dtype: float64
Kempegowda Nagar
Nehru Nagar
Kalathammanahalli
Somashetti Halli
4020    24.44
4053    24.44
Name: locality_rental_price, dtype: float64
Ganigarahalli
4021    8.61
4029    8.61
Name: locality_rental_price, dtype: float64
Guniagrahara
Chikkabanavara
Sasiveghatta
Kempapura
Kumbarahalli
4026    24.404813
4042    24.404813
Name: locality_rental_price, dtype: float64
Mavallipura
4030    28.452673
4036    28.452673
Name: locality_rental_price, dtype: float64
Kasagattapura
4037    7.6
4041    7.6
Name: locality_rental_price, dtype: float64
Varadharaja Nagar
Chikka Bettahalli
Singapura
Batarayanapura Muncipality
Shamarajpura
4058    9.99
4063    9.99
Name: locality_rental_price, dtype: float64
Madi Agrahara
Vaderahalli
Nellukunte
Kodigenahalli
Bettahalasur
4067    26.454042
4091    26.454042
Name: locality_rental_price, dtype: float64
Sugatta
4068    25.085371
4069    25.085371
Name: locality_rental_price, dtype: float64
Gantiganahalli
4071    14.98
4073    14.98
Name: locality_rental_price, dtype: float64
Muddanahalli
Harohalli
Papanahalli
4079    31.21503
4081    31.21503
Name: locality_rental_price, dtype: float64
Chokkanahalli
Lakshmisagara
Kattigenahalli
Sonnapanahalli
4107    18.75
4109    18.75
Name: locality_rental_price, dtype: float64
Central Telecom Society
Muthasandra
Chikkanekkundi
Kotur
Madhura Nagar
Varthur
Hosahalli  Tipsandra
Vartur

Thimmadahalli
Thirumalashettyhally
Sorahunase
Whitefield
Gonighattapura
Janthagondanahalli
Belakere
Neriga
Kathriguppe
4762    27.330413
4958    27.330413
Name: locality_rental_price, dtype: float64
Nekkundi Dommasandra
4763    29.481002
4764    29.481002
Name: locality_rental_price, dtype: float64
Muthkur
Bylahalli
Yedagondahalli
4773    28.278411
4965    28.278411
Name: locality_rental_price, dtype: float64
Kadubeesanahalli
Bellandur
Panathur
Bhoganhalli
Brookefield
Marathahalli
Chinnapanna Halli
Munnekollal
Gunjur
Chikka Bellandur
4813    26.787776
4814    26.787776
Name: locality_rental_price, dtype: float64
Kacharakanahalli
Samethanahalli
4824    11.35
4834    11.35
Name: locality_rental_price, dtype: float64
Naduvathi
4826    28.152749
4848    28.152749
Name: locality_rental_price, dtype: float64
Doddadunnasandra
Bhodanahosahalli
4828    20.0
4855    20.0
Name: locality_rental_price, dtype: float64
Koralur
Kodihalli
Hunasehalli
Bisanahalli
Appajipura
Mallasandra
Bhaktharahalli
Kanekallu
Devalapura
Hemmandahalli
Naganayakanakote
Kadugodi
Krishnarajapuram
Hoodi
4869    17.445
5587    17.445
Name: locality_rental_price, dtype: float64
Belatur
4873    32.003223
4874    32.003223
Name: locality_rental_price, dtype: float64
Chikkabana Halli
4876    33.113362
5671    33.113362
Name: locality_rental_price, dtype: float64
Kurudusonnenahalli
Chansandra
4887    51.768
4888    51.768
Name: locality_rental_price, dtype: float64
Nagondanahalli
4891    14.48
4892    14.48
Name: locality_rental_price, dtype: float64
Volagerekallahalli
Kugur
Kuthaganahalli
Ittangur
Thigala Chowdadenahalli
Dommasandra
Chikkavaderapura
Sulikunte
Kodathi
Chokkasandra
Ramnaikanahalli
4936    28.96648
4938    28.96648
Name: locality_rental_price, dtype: float64
Heggondahalli
4937    14.55
4945    14.55
Name: locality_rental_price, dtype: float64
Kachamaranahalli
Mulluru
Yamare
Chambenahalli
Kommasandra
Anugondahalli
4963    8.89
4964    8.89
Name: locality_rental_price, dtype: float64
Hongasandra
Begur
Arekere
Hulimavu
BDA Layout BTM 4th Satge
Bommanahalli
Akshayanagar
Devarachikkana Halli
HSR Layout
Jakkasandra
Mangammanapalya
BTM Layout
Bilekahalli
Singasandra
Basapura
Parappana Agrahara
Vittasandra
Mylasandra
Somasundarapalya
Muneshwara Nagar
Harlur
JP Nagar
Anjanadri Layout
Kumaraswamy Layout
Konanakunte
BMC Layout
5022    17.57
5027    17.57
Name: locality_rental_price, dtype: float64
Bikasipura
Jayanagar
Kanakanagar
Uttarahalli Hobli
Bendre Nagar
Kalena Agrahara
Gottigere
Panduranga Nagar
5057    19.145
5061    19.145
Name: locality_rental_price, dtype: float64
Challagatta
HAL
Koramangala
Agram
Jyothi Nagar
Jeevanbheemanagar
Kaggadasapura
New Tippasandra
Murugeshpalya
5082    25.43
5090    25.43
Name: locality_rental_price, dtype: float64
Vimanapura
5083    18.355
5108    18.355
Name: locality_rental_price, dtype: float64
Domlur
5087    25.18
5629    25.18
Name: locality_rental_price, dtype: float64
Adarsh Palm Retreat
Kaikondrahalli
5095    29.55
5273    29.55
Name: locality_rental_price, dtype: float64
Eastwood Twp
Kodbisanhalli
Wilson Garden
5112    18.505
5115    18.505
Name: locality_rental_price, dtype: float64
Hombegowda Nagar
5113    39.354
5117    39.354
Name: locality_rental_price, dtype: float64
Sadduguntepalya
Adugodi
Tata Silk Farm
Mohammedan Block
Neelasandra
Langford Gardens
Shanti Nagar
5131    26.47
5139    26.47
Name: locality_rental_price, dtype: float64
Victoria Layout
Doddamavalli
Parvathipuram
Sampangi Rama Nagara
Nagarathpete
Mavalli
5137    17.84
5138    17.84
Name: locality_rental_price, dtype: float64
Jaya Nagar
Ejipura
5154    22.41
5158    22.41
Name: locality_rental_price, dtype: float64
Electronic City
Bettadasanapura
Chikkathoguru
5176    12.31
5184    12.31
Name: locality_rental_price, dtype: float64
Rayasandra
Bommasandra Industrial Area
Thirupalya
Vabasandra
Yarandahalli
Ananth Nagar
Gulimangala
Hommadevanahalli
Hullahalli
Pillaganahalli
5219    11.77
5235    11.77
Name: locality_rental_price, dtype: float64
Kalkere
Tejaswini Nagar
Ckikkakammana halli
Piliganahalli
Basavanapura
5234    31.994
5236    31.994
Name: locality_rental_price, dtype: float64
Sakalawara
5238    27.34076
5246    27.34076
Name: locality_rental_price, dtype: float64
Hullukasavanahalli
5242    27.521148
5250    27.521148
Name: locality_rental_price, dtype: float64
Laxmipura
5245    26.537037
5247    26.537037
Name: locality_rental_price, dtype: float64
Mylsandra Dinne
Chikkanayakanahalli
5258    26.796294
5262    26.796294
Name: locality_rental_price, dtype: float64
Halanayakanahalli
Chikkakannalli
5260    31.31
5276    31.31
Name: locality_rental_price, dtype: float64
Choodasandra
Hadosiddapura
5264    14.81
5301    14.81
Name: locality_rental_price, dtype: float64
Doddakannali
5272    43.535055
5278    43.535055
Name: locality_rental_price, dtype: float64
Kasavanahalli
5279    23.925
5281    23.925
Name: locality_rental_price, dtype: float64
Gattahalli
Chikkanagamangala
Kattugollahalli
5307    33.304064
5309    33.304064
Name: locality_rental_price, dtype: float64
Mandur
Bommenahalli
Lagumenahalli
Guttahalli
Goravigere
Dodda Amanikere
5323    32.260803
5338    32.260803
Name: locality_rental_price, dtype: float64
Doddagattiganabbe
Khajisonenahalii
5326    32.67224
5332    32.67224
Name: locality_rental_price, dtype: float64
Bidare Agraha
Sannatammanahalli
Aavalahalli
Kannamangala
Huskur
5333    26.125262
5706    26.125262
Name: locality_rental_price, dtype: float64
Nimbekaipura
Bendiganahalli
Poojena Agrahara
5339    26.4985
5340    26.4985
Name: locality_rental_price, dtype: float64
Chikkagattiganabbe
5341    25.412936
5342    25.412936
Name: locality_rental_price, dtype: float64
Hoskote  Amnikere
5346    37.772402
5348    37.772402
Name: locality_rental_price, dtype: float64
Ganagalu
Horamavu
Bileshivali
Byrathi
5357    20.72
5379    20.72
Name: locality_rental_price, dtype: float64
Hennur Gardens
5361    21.25
5365    21.25
Name: locality_rental_price, dtype: float64
HBR Layout
Kalyan Nagar
Dodda Gubbi
Kyalasona Halli
5369    15.875
5373    15.875
Name: locality_rental_price, dtype: float64
Narayanapura
Kothanur
5376    19.25
5380    19.25
Name: locality_rental_price, dtype: float64
Bhairati
5381    11.8
5524    11.8
Name: locality_rental_price, dtype: float64
NRI Layout
K. C. Krishna Reddy Layout
5384    25.615
5647    25.615
Name: locality_rental_price, dtype: float64
K Channasandra
5385    11.96
5401    11.96
Name: locality_rental_price, dtype: float64
Ramamurthy Nagar
Varanasi
5388    14.15
5651    14.15
Name: locality_rental_price, dtype: float64
Rampura
Anagalapura
5399    14.07
5487    14.07
Name: locality_rental_price, dtype: float64
Huvina Ane
5400    25.799065
5649    25.799065
Name: locality_rental_price, dtype: float64
Nagavara
Hebbal Kempapura
5404    19.435
5406    19.435
Name: locality_rental_price, dtype: float64
Dasarahalli
5405    17.02
5422    17.02
Name: locality_rental_price, dtype: float64
Hebbal
Manayata Tech Park
Sanjeevini Nagar
Thanisandra
Amrutahalli
CQAL Layout
5424    36.129
5425    36.129
Name: locality_rental_price, dtype: float64
Byatarayanapura
5426    16.39
5430    16.39
Name: locality_rental_price, dtype: float64
Kaval Bairasandra
Kadugondanahalli
RT Nagar
5438    39.974
5443    39.974
Name: locality_rental_price, dtype: float64
Devara Jeevanahalli
5442    13.675
5612    13.675
Name: locality_rental_price, dtype: float64
Sinthan Nagar
Yerappanahalli
Chikkasandra
5458    13.78
5478    13.78
Name: locality_rental_price, dtype: float64
Nadagowdagollahalli
Kannuru
Donnenahalli
5462    26.727689
5473    26.727689
Name: locality_rental_price, dtype: float64
Dasanayakanahalli
Gundur
Kada Agrahara
Bandebommasandra
5483    24.677635
5486    24.677635
Name: locality_rental_price, dtype: float64
Marasandra
Agrahara Badavane
Agrahara
5499    15.36
5503    15.36
Name: locality_rental_price, dtype: float64
Kogilu
Sampigehalli
5505    16.13
5528    16.13
Name: locality_rental_price, dtype: float64
Mittaganahalli
5510    16.67
5535    16.67
Name: locality_rental_price, dtype: float64
Katgenahalli
Chikka Gubbi
R.K. Hegde Nagar
5527    17.05
5532    17.05
Name: locality_rental_price, dtype: float64
Ramkrishna Hegade Nagar
Tirumanahalli
Kadusonnappanahalli
Mahadevapura
C V Raman Nagar
Battarahalli
Dooravani Nagar
Kartik Nagar
Mahadevpura Industrial Estate
Sarvagnanagar
5590    18.945
5594    18.945
Name: locality_rental_price, dtype: float64
Cox Town
Maruthi Sevanagar
Ulsoor
Pulikeshi Nagar
5599    22.715
5616    22.715
Name: locality_rental_price, dtype: float64
Sivanchetti Gardens
5602    39.985
5603    39.985
Name: locality_rental_price, dtype: float64
Banaswadi
5608    15.545
5635    15.545
Name: locality_rental_price, dtype: float64
Ramaswamipalya
Richards Town
Cooke Town
Lingarajapuram
Indiranagar
Jogupalya
5625    43.65
5626    43.65
Name: locality_rental_price, dtype: float64
Bennigana Halli
Kasturi Nagar
Hirandahalli
Kithaganur Village
5644    10.75
5652    10.75
Name: locality_rental_price, dtype: float64
Hallehalli
5646    13.24
5650    13.24
Name: locality_rental_price, dtype: float64
Kithiganur

Byappanahalli
Bidarahalli
Adur
Hosabasavanapura
5674    14.19
5679    14.19
Name: locality_rental_price, dtype: float64
Medahalli
Cheemasandra
Bommasandra Village
5689    12.88
5718    12.88
Name: locality_rental_price, dtype: float64
Singena Agrahara
5693    36.31836
5694    36.31836
Name: locality_rental_price, dtype: float64
Narayanaghatta
Gottamaranahalli
Ramasagara
5697    31.714067
5704    31.714067
Name: locality_rental_price, dtype: float64
Heelalige
5702    26.492822
5719    26.492822
Name: locality_rental_price, dtype: float64
Mumbai
Malabar Hill
Cumballa Hill
4114    134.087505
4129    134.087505
Name: locality_rental_price, dtype: float64
Tardeo
Girgaon
4120    72.564561
4122    72.564561
Name: locality_rental_price, dtype: float64
Gamdevi
4121    72.289157
4123    72.289157
Name: locality_rental_price, dtype: float64
Kalbadevi
4124    99.568804
4299    99.568804
Name: locality_rental_price, dtype: float64
Mumbai Central
Kamathipura
Madanpura
Colaba
Cuffe Parade
4137    137.726293
4139    137.726293
Name: locality_rental_price, dtype: float64
Fort
Namnetum Street
Marine Lines
Churchgate
4153    83.481666
4155    83.481666
Name: locality_rental_price, dtype: float64
Bandra West
Pali Hill
Khar Danda
Juhu
Andheri West
Jogeshwari West
Vile Parle West
4185    97.823249
4188    97.823249
Name: locality_rental_price, dtype: float64
Vile Parle East
Jogeshwari East
Andheri East
Madh
Prabhadevi
Worli
Dadar West
Parel
Mahim
Matunga West
4215    89.157849
4235    89.157849
Name: locality_rental_price, dtype: float64
Rajiv Gandhi Sea Link
Dadar East
Lower Parel
Mahalakshmi
Matunga
Bandra East
Santacruz East
Khar West
4248    134.11693
4265    134.11693
Name: locality_rental_price, dtype: float64
Santacruz West
Khar East
Sion
Dharavi
Kurla East
Kasbe Bandra
Kurla West
Sakinaka
Mahul
4288    31.903637
4368    31.903637
Name: locality_rental_price, dtype: float64
Mazgaon
Angriya Water Terminal
4293    51.161933
4315    51.161933
Name: locality_rental_price, dtype: float64
Umerkhadi
Bhuleshwar
Nagpada
Masjid Bandar
Sewri
Mumbai Trans Harbour Link
Byculla East
Jacob Circle
Byculla West
Fort Street
Najale
Trombay
Mankhurd
Anushakti Nagar
Turbhe
Wadala
Chembur East
Antop Hill
Sanjay Gandhi National Park
Kandiwali West
Malad West
Borivali West
Uttan
Gorai
Manori
Dahisar West
Dahisar East
Goregaon East
Goregaon West
Malad East
kandiwali East
Marve
Vesava
Goma Galli
Malwani
4537    26.78774
4538    26.78774
Name: locality_rental_price, dtype: float64
Borivali East
Vikhroli East
Kanjurmarg East
Vikhroli West
Powai
Bhandup East
Bhandup West
Mulund East
Asalpha
4621    40.512821
4625    40.512821
Name: locality_rental_price, dtype: float64
Ghatkopar West
Mulund West
Ramabai Ambedkar Nagar
4681    37.5
4683    37.5
Name: locality_rental_price, dtype: float64
Ghatkopar East
Chedda Nagar
4685    40.687679
4686    40.687679
Name: locality_rental_price, dtype: float64
Govandi
Mankur
Vidyavihar
Govandi East

In [453]:
for t_name, locality in df_merged.groupby(['t_name', 'locality']):
    if locality.shape[0] == 2:
        print(t_name, locality['average_monthly_residential_rental_price'])

('Bengaluru', 'Adakamaranahalli') 3248   NaN
3260   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Agrahara') 5499    15.36
5503    15.36
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Anagalapura') 5399    14.07
5487    14.07
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Anantapura') 3986    12.31
3994    12.31
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Anugondahalli') 4963    8.89
4964    8.89
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'BMC Layout') 5022    17.57
5027    17.57
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Banashankari Stage Ii') 3719    13.65
3721    10.70
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Banaswadi') 5608    13.04
5635    18.05
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Bandebommasandra') 5483   NaN
5486   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Bapagrama') 3540   NaN
3543   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Basavanapura') 5234    51.768
5236    12.220
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Belatur') 4873   NaN
4874   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Bettahalasur') 4067   NaN
4091   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Bhairati') 5381    11.8
5524    11.8
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Bharat Nagar') 3568    11.90
3574    12.11
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Bhodanahosahalli') 4828    20.0
4855    20.0
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Bommasandra Village') 5689    12.88
5718    12.88
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Byatarayanapura') 5426    15.00
5430    17.78
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Byrappanahalli') 3844   NaN
3849   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Byrathi') 5357    20.72
5379    20.72
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'CQAL Layout') 5424    20.490
5425    51.768
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'CRPF Area') 3982    16.76
3984    16.76
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Chansandra') 4887    51.768
4888    51.768
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Chikka Bellandur') 4813   NaN
4814   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Chikkabana Halli') 4876   NaN
5671   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Chikkabidarakallu') 3638    33.2
3639    33.2
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Chikkagattiganabbe') 5341   NaN
5342   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Chikkajala') 3876    12.9
4108    21.7
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Chikkakannalli') 5260    31.31
5276    31.31
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Chikkanayakanahalli') 5258   NaN
5262   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Chikkasandra') 5458    13.78
5478    13.78
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Chikkathoguru') 5176    12.31
5184    12.31
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Dasarahalli') 5405    16.44
5422    17.60
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Devagere') 3315   NaN
3316   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Devara Jeevanahalli') 5442    12.09
5612    15.26
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Dodda Amanikere') 5323   NaN
5338   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Doddakannali') 5272   NaN
5278   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Dombarahalli') 3261    16.25
3648    16.25
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Domlur') 5087    25.18
5629    25.18
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Donnenahalli') 5462   NaN
5473   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Ejipura') 5154    12.00
5158    32.82
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Gadenahalli') 3863    12.5
3865    12.5
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Gandhi Nagar') 3789    24.68
3814    21.63
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Ganganagar') 3805    20.61
5439    17.17
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Gangasandra') 3319   NaN
3320   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Ganigarahalli') 4021    8.61
4029    8.61
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Gantiganahalli') 4071    14.98
4073    14.98
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Gonipura') 3303   NaN
3343   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Gulakamale') 3477   NaN
3482   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Hadosiddapura') 5264    14.81
5301    14.81
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Hallehalli') 5646    11.52
5650    14.96
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Hanumantha Sagara') 3285    10.17
3662    10.17
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Hebbal Kempapura') 5404    22.37
5406    16.50
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Heelalige') 5702   NaN
5719   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Heggondahalli') 4937    14.55
4945    14.55
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Hennur Gardens') 5361    22.5
5365    20.0
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Hombegowda Nagar') 5113    51.768
5117    26.940
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Honnenahalli') 3944    24.0
3945    24.0
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Hoodi') 4869     9.13
5587    25.76
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Hosabasavanapura') 5674    13.64
5679    14.74
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Hoskote  Amnikere') 5346   NaN
5348   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Hullukasavanahalli') 5242   NaN
5250   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Huskur') 5333   NaN
5706   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Huvina Ane') 5400   NaN
5649   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Jogupalya') 5625    35.72
5626    51.58
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'K Channasandra') 5385    11.96
5401    11.96
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'K. C. Krishna Reddy Layout') 5384    12.74
5647    38.49
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Kaikondrahalli') 5095    29.55
5273    29.55
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Kanmanike') 3337   NaN
3338   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Kariyana Palya') 3345    16.18
3347    20.00
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Kasagattapura') 4037    7.6
4041    7.6
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Kasavanahalli') 5279    21.90
5281    25.95
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Kathriguppe') 4762   NaN
4958   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Kattugollahalli') 5307   NaN
5309   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Kaveri Nagar') 3505    13.74
3511    15.28
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Khajisonenahalii') 5326   NaN
5332   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Kithaganur Village') 5644    10.75
5652    10.75
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Koppa') 3835    11.4
3843    11.4
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Kothanur') 5376    19.25
5380    19.25
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Kumbarahalli') 4026   NaN
4042   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Kyalasona Halli') 5369    15.35
5373    16.40
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Laxmipura') 5245   NaN
5247   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Lingadeeranhalli') 3582    12.52
3588    12.52
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Madanayakahalli') 3259   NaN
3660   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Madhugirihalli') 3952   NaN
4039   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Mahalakshmi Layout') 3807   NaN
3809   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Mailasandra') 3369    16.79
3769    16.79
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Maligondanahalli') 3232    11.0
3236    11.0
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Maranayakanahalli') 3896    8.37
3898    8.37
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Mathahalli') 3267   NaN
3272   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Mavalli') 5137    17.84
5138    17.84
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Mavallipura') 4030   NaN
4036   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Meesaganahalli') 3881   NaN
3894   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Mittaganahalli') 5510    16.67
5535    16.67
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Murugeshpalya') 5082    26.25
5090    24.61
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Mutkad Halli') 3921   NaN
3922   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Naduvathi') 4826   NaN
4848   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Nagasandra') 3669    21.12
3685    14.72
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Nagdevanahalli') 3736    13.70
3742    13.03
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Nagegowdanapalya') 3378    15.22
3385    15.22
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Nagondanahalli') 4891    14.48
4892    14.48
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Nallasandra') 3840   NaN
3842   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Nandini Layout') 3536    18.40
3629    16.62
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Narasipura') 3266   NaN
3271   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Nekkundi Dommasandra') 4763   NaN
4764   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'O.B.Chudahalli') 3442   NaN
3478   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Padarayana Pura') 3701    18.010
3707    51.768
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Panduranga Nagar') 5057    20.23
5061    18.06
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Papanahalli') 4079   NaN
4081   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Pillaganahalli') 5219    11.77
5235    11.77
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Poojena Agrahara') 5339   NaN
5340   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Pulikeshi Nagar') 5599    16.85
5616    28.58
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'R.K. Hegde Nagar') 5527    17.05
5532    17.05
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'RT Nagar') 5438    28.180
5443    51.768
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Ramasagara') 5697   NaN
5704   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Ramnaikanahalli') 4936   NaN
4938   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Sahakara Nagar') 4006    15.54
5427    25.00
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Sakalawara') 5238   NaN
5246   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Samethanahalli') 4824    11.35
4834    11.35
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Sampigehalli') 5505    16.13
5528    16.13
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Sarvagnanagar') 5590    17.04
5594    20.85
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Seegehalli') 3575   NaN
3578   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Shamarajpura') 4058    10.91
4063     9.07
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Shankarapura') 3731    13.60
3735    20.72
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Shanti Nagar') 5131    26.47
5139    26.47
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Shivakote') 3924   NaN
3951   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Sidedahalli') 3652     9.81
3658    11.97
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Singena Agrahara') 5693   NaN
5694   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Sivanchetti Gardens') 5602    49.57
5603    30.40
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Somapura') 3356    8.33
3358    8.33
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Somashetti Halli') 4020     9.05
4053    39.83
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Sonnapanahalli') 4107    18.75
4109    18.75
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Srirampura') 3786    29.31
3790    21.20
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'State Bank of India Colony') 3517    18.33
3570     9.38
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Subhash Nagar') 3820    16.00
3823     7.78
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Sugatta') 4068   NaN
4069   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Sunkalpalya') 3366    14.0
3367    14.0
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'T. Dasarahalli') 3599    20.15
3684    20.15
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Talaghattapura') 3377    14.74
3379    15.03
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Torenagasandra') 3289   NaN
3291   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Ullal Uppanagar') 3759    15.91
3763    13.74
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Uttari') 3322   NaN
3323   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Vakil Garden City') 3457    23.58
3465    19.43
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Varanasi') 5388    14.15
5651    14.15
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Vimanapura') 5083    15.46
5108    21.25
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Wilson Garden') 5112    18.53
5115    18.48
Name: average_monthly_residential_rental_price, dtype: float64
('Bengaluru', 'Yedagondahalli') 4773   NaN
4965   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Agraula') 2753    10.63347
2754    10.63347
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Akbar Pur Majra') 2853   NaN
2855   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Allipur') 2849   NaN
2888   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Anand Parbat') 1199    68.421053
1240    68.421053
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Ashok Nagar') 945     29.14213
2510    25.68306
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Asmayalpur') 3123   NaN
3124   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Baba Banda Singh Bahadur Setu') 1184    119.961538
1186    119.961538
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Bajghera') 796   NaN
981   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Baqipur') 1863   NaN
1864   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Barakhamba') 1008    119.961538
1041    119.961538
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Bindapur') 915    24.461146
956    24.461146
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Chatesar') 1747   NaN
1751   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Dakshinpuri') 499    23.373984
501    33.455882
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Darya Pur Khurd') 3086   NaN
3090   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Daulat Pur') 997    NaN
1002   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Delhi - Meerut Expressway') 1183   NaN
1187   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Deorala') 2939   NaN
2960   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'East of Kailash') 1166    33.731553
1168    39.840740
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'GTB Nagar') 2787    56.250000
2789    46.745152
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Gangarwa') 2197   NaN
2342   NaN
Name: average_monthly_residential_rental_price, dtype: float64
('Delhi', 'Garhi Khasru') 2924   NaN
2925   NaN

In [484]:
check=pd.read_csv(r"D:\Sociometrik\rent prediction\check_2 - Copy.csv")

In [491]:
a=check[(check['count_at_once']==25)&(check['locality']=='Badli')]['average_score'].sum()
check[(check['count_at_once']==25)&(check['locality']=='Badli')]

#check[(check['count_at_once']==25)&(check['locality']=='Badli')]['average_monthly_residential_rental_price'].apply(lambda x:)

,hexid08,t_name,locality,count_oneby one,count_at_once,average_monthly_residential_rental_price,locality_rental_price,prediction,green_space_density,building_density_per_sqm,...,convenience_store,department_store,grocery_store,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station
3074,883da1c645fffff,Delhi,Badli,1,25,NaN,24.594221,yes,0.068150,0.000034,...,0,0,0,0,0,1,0,0,0,0
3082,883da1c65dfffff,Delhi,Badli,2,25,NaN,24.594221,yes,0.014585,0.000099,...,0,0,0,0,0,2,0,0,0,0
3180,883da1d481fffff,Delhi,Badli,3,25,NaN,24.594221,yes,0.005314,0.000076,...,0,0,0,0,0,0,0,0,0,0
3181,883da1d483fffff,Delhi,Badli,4,25,NaN,24.594221,yes,0.027812,0.000017,...,0,0,0,0,0,0,0,0,0,0
3182,883da1d485fffff,Delhi,Badli,5,25,NaN,24.594221,yes,0.005314,0.000061,...,0,0,0,0,0,0,0,0,0,0
3183,883da1d487fffff,Delhi,Badli,6,25,NaN,24.594221,yes,0.051668,0.000051,...,0,0,0,0,0,0,0,0,0,0
3184,883da1d489fffff,Delhi,Badli,7,25,NaN,24.594221,yes,0.011193,0.000077,...,0,0,0,0,0,0,0,0,0,0
3185,883da1d48bfffff,Delhi,Badli,8,25,NaN,24.594221,yes,0.011645,0.000016,...,0,0,0,0,0,0,0,0,0,0
3186,883da1d48dfffff,Delhi,Badli,9,25,NaN,24.594221,yes,0.000113,0.000088,...,0,0,0,0,0,0,0,0,0,0
3189,883da1d495fffff,Delhi,Badli,10,25,NaN,24.594221,yes,0.160770,0.000021,...,0,0,0,0,0,0,0,0,0,0
3192,883da1d4a1fffff,Delhi,Badli,11,25,NaN,24.594221,yes,0.224535,0.001275,...,0,0,0,0,0,0,0,0,0,0
3193,883da1d4a3fffff,Delhi,Badli,12,25,NaN,24.594221,yes,0.110119,0.001006,...,0,0,0,0,0,0,0,0,0,0
3194,883da1d4a5fffff,Delhi,Badli,13,25,NaN,24.594221,yes,0.039231,0.000041,...,0,0,0,0,0,0,0,0,0,0
3195,883da1d4a7fffff,Delhi,Badli,14,25,NaN,24.594221,yes,0.111702,0.000243,...,0,0,0,0,0,0,0,0,0,0
3196,883da1d4a9fffff,Delhi,Badli,15,25,NaN,24.594221,yes,0.066026,0.000208,...,0,0,0,0,0,0,0,0,0,0
3197,883da1d4abfffff,Delhi,Badli,16,25,NaN,24.594221,yes,0.191974,0.001034,...,0,0,0,0,0,0,0,0,0,0
3198,883da1d4adfffff,Delhi,Badli,17,25,NaN,24.594221,yes,0.067383,0.000097,...,0,0,0,0,0,0,0,0,0,0
3199,883da1d4b5fffff,Delhi,Badli,18,25,NaN,24.594221,yes,0.035953,0.000068,...,0,0,0,0,0,0,0,0,0,0
3200,883da1d4b7fffff,Delhi,Badli,19,25,NaN,24.594221,yes,0.066252,0.000034,...,0,0,0,0,0,0,0,0,0,0
3201,883da1d4b9fffff,Delhi,Badli,20,25,NaN,24.594221,yes,0.033126,0.000056,...,0,0,0,0,0,0,0,0,0,0
3202,883da1d4bdfffff,Delhi,Badli,21,25,NaN,24.594221,yes,0.063087,0.000111,...,0,0,0,0,0,0,0,0,0,0
3203,883da1d4d5fffff,Delhi,Badli,22,25,NaN,24.594221,yes,0.001583,0.000039,...,0,0,0,0,0,0,0,0,0,0
3205,883da1d4e3fffff,Delhi,Badli,23,25,NaN,24.594221,yes,0.000000,0.000118,...,0,0,0,0,0,0,0,0,0,0
3207,883da1d591fffff,Delhi,Badli,24,25,NaN,24.594221,yes,0.000792,0.000023,...,0,0,0,0,0,0,0,0,0,0
3210,883da1d5d3fffff,Delhi,Badli,25,25,NaN,24.594221,yes,0.000226,0.000097,...,0,0,0,0,0,0,0,0,0,0

# On hexgrid level

In [326]:
df_for_hex=df.set_index(['hexid08','t_name','locality'])
df_for_hex

,,locality,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,auto_dealership,auto_service_maintenance,...,grocery_store,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price
hexid08,t_name,,,,,,,,,,,,,,,,,,,,,
883cf28945fffff,Kolkata,Sinthi,0.086059,6.84,5,3982,0.056038,0.004971,0.244236,0,3,...,45,5,0,0,0,0,1,0,0,13.491124
883cf28949fffff,Kolkata,Baranagar,0.169749,4.10,0,3725,0.037358,0.004139,0.309732,0,0,...,0,1,0,0,0,0,0,0,0,10.000000
883cf2894dfffff,Kolkata,Baranagar,0.311278,0.37,0,3403,0.030660,0.003579,0.469274,0,2,...,18,1,0,0,0,0,0,0,0,10.575139
883cf28961fffff,Kolkata,Paikpara,0.232866,11.60,0,4111,0.028392,0.003431,0.341649,0,2,...,12,1,3,0,1,0,0,0,0,22.123577
883cf28965fffff,Kolkata,Tala,0.149823,13.25,5,4157,0.029187,0.001848,0.277745,0,5,...,0,0,0,0,0,0,2,2,1,16.339713
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88618935b9fffff,Bengaluru,Gulimangala,0.070000,0.59,0,673,0.000576,0.000144,0.357143,0,0,...,0,0,0,0,0,0,0,0,0,NaN
88618935bbfffff,Bengaluru,Gulimangala,0.130000,1.42,0,719,0.000872,0.000160,0.250000,0,0,...,0,0,0,0,0,0,0,0,0,NaN
88618935bdfffff,Bengaluru,Gulimangala,0.180000,0.40,0,644,0.000934,0.000280,0.215470,0,0,...,0,0,0,0,0,0,0,0,0,NaN
88618935d3fffff,Bengaluru,Bommasandra Village,0.050000,0.00,0,409,0.005783,0.000334,0.409326,0,0,...,0,0,0,0,0,0,0,0,0,NaN
88618935d7fffff,Bengaluru,Heelalige,0.040000,3.91,0,449,0.003792,0.000455,0.379845,0,0,...,0,0,0,0,0,0,0,0,0,NaN

In [327]:
df_2=df.iloc[:,:]
df_2=df_2[df_2['average_monthly_residential_rental_price'].notnull()]

In [328]:
df_2

,,locality,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,auto_dealership,auto_service_maintenance,...,grocery_store,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price
hexid08,t_name,,,,,,,,,,,,,,,,,,,,,
883cf28945fffff,Kolkata,Sinthi,0.086059,6.84,5,3982,0.056038,0.004971,0.244236,0,3,...,45,5,0,0,0,0,1,0,0,13.491124
883cf28949fffff,Kolkata,Baranagar,0.169749,4.10,0,3725,0.037358,0.004139,0.309732,0,0,...,0,1,0,0,0,0,0,0,0,10.000000
883cf2894dfffff,Kolkata,Baranagar,0.311278,0.37,0,3403,0.030660,0.003579,0.469274,0,2,...,18,1,0,0,0,0,0,0,0,10.575139
883cf28961fffff,Kolkata,Paikpara,0.232866,11.60,0,4111,0.028392,0.003431,0.341649,0,2,...,12,1,3,0,1,0,0,0,0,22.123577
883cf28965fffff,Kolkata,Tala,0.149823,13.25,5,4157,0.029187,0.001848,0.277745,0,5,...,0,0,0,0,0,0,2,2,1,16.339713
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8861893591fffff,Bengaluru,Electronic City,0.180000,0.00,0,378,0.002130,0.000351,0.356000,0,0,...,0,0,0,0,0,0,0,0,0,11.330000
8861893597fffff,Bengaluru,Electronic City,0.000000,0.49,1,5383,0.006280,0.000915,0.528222,0,0,...,4,0,0,0,0,0,0,0,2,10.480000
886189359bfffff,Bengaluru,Bommasandra Industrial Area,0.110000,7.04,0,3502,0.005382,0.000516,0.376945,0,1,...,0,1,2,0,2,0,0,0,0,14.590000
88618935b1fffff,Bengaluru,Gulimangala,0.320000,0.21,0,719,0.000339,0.000198,0.289855,0,0,...,0,0,0,0,0,0,0,0,0,25.000000
88618935b7fffff,Bengaluru,Chikkanagamangala,0.210000,6.06,0,774,0.000489,0.000441,0.353659,0,0,...,0,0,0,0,0,0,0,0,0,14.650000

In [562]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2084 entries, ('883cf28945fffff', 'Kolkata') to ('88618935b7fffff', 'Bengaluru')
Data columns (total 53 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   green_space_density                       2084 non-null   float64
 1   public_infrastructure_index               2084 non-null   float64
 2   road_length                               2082 non-null   float64
 3   transportation_hubs                       2084 non-null   int64
 4   daily_avg_footfall                        2084 non-null   int64
 5   total_digital_consumers                   2084 non-null   int64
 6   pop_density_per_sqm                       2084 non-null   float64
 7   building_density_per_sqm                  2084 non-null   float64
 8   luxery_percentage                         2082 non-null   float64
 9   auto_dealership                           2084 non-null   int64
 10  auto_service_maintenance                  2084 non-null   int64
 11  motorcycle_dealership                     2084 non-null   int64
 12  truck_dealership                          2084 non-null   int64
 13  business_facility                         2084 non-null   int64
 14  government_office                         2084 non-null   int64
 15  higher_education                          2084 non-null   int64
 16  library                                   2084 non-null   int64
 17  school                                    2084 non-null   int64
 18  training_centre_institute                 2084 non-null   int64
 19  amusement_park                            2084 non-null   int64
 20  bowling_centre                            2084 non-null   int64
 21  cinema                                    2084 non-null   int64
 22  golf_course                               2084 non-null   int64
 23  ice_skating_rink                          2084 non-null   int64
 24  museum                                    2084 non-null   int64
 25  nightlife                                 2084 non-null   int64
 26  sports_centre                             2084 non-null   int64
 27  atm                                       2084 non-null   int64
 28  bank                                      2084 non-null   int64
 29  hospital                                  2084 non-null   int64
 30  medical_service                           2084 non-null   int64
 31  pharmacy                                  2084 non-null   int64
 32  industrial_zone                           2084 non-null   int64
 33  police_station                            2084 non-null   int64
 34  bar_or_pub                                2084 non-null   int64
 35  coffee_shop                               2084 non-null   int64
 36  restaurant                                2084 non-null   int64
 37  clothing_store                            2084 non-null   int64
 38  consumer_electronics_store                2084 non-null   int64
 39  convenience_store                         2084 non-null   int64
 40  department_store                          2084 non-null   int64
 41  grocery_store                             2084 non-null   int64
 42  home_improvement_hardware_store           2084 non-null   int64
 43  home_specialty_store                      2084 non-null   int64
 44  office_supply_services_store              2084 non-null   int64
 45  petrol_gasoline_station                   2084 non-null   int64
 46  shopping                                  2084 non-null   int64
 47  sporting_goods_store                      2084 non-null   int64
 48  airport                                   2084 non-null   int64
 49  bus_station                               2084 non-null   int64
 50  train_station                             2084 non-null   int64
 51  hotel                                     2084 non-null   int64
 52  average_monthly_residential_rental_price  2084 non-null   float64
dtypes: float64(7), int64(46)
memory usage: 1.1+ MB

In [563]:
df_3=df_2.dropna().reindex()

In [564]:
df_3

,,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,auto_dealership,auto_service_maintenance,motorcycle_dealership,...,grocery_store,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price
hexid08,t_name,,,,,,,,,,,,,,,,,,,,,
883cf28945fffff,Kolkata,0.086059,6.84,5,3982,0.056038,0.004971,0.244236,0,3,0,...,45,5,0,0,0,0,1,0,0,13.491124
883cf28949fffff,Kolkata,0.169749,4.10,0,3725,0.037358,0.004139,0.309732,0,0,0,...,0,1,0,0,0,0,0,0,0,10.000000
883cf2894dfffff,Kolkata,0.311278,0.37,0,3403,0.030660,0.003579,0.469274,0,2,0,...,18,1,0,0,0,0,0,0,0,10.575139
883cf28961fffff,Kolkata,0.232866,11.60,0,4111,0.028392,0.003431,0.341649,0,2,0,...,12,1,3,0,1,0,0,0,0,22.123577
883cf28965fffff,Kolkata,0.149823,13.25,5,4157,0.029187,0.001848,0.277745,0,5,0,...,0,0,0,0,0,0,2,2,1,16.339713
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8861893591fffff,Bengaluru,0.180000,0.00,0,378,0.002130,0.000351,0.356000,0,0,0,...,0,0,0,0,0,0,0,0,0,11.330000
8861893597fffff,Bengaluru,0.000000,0.49,1,5383,0.006280,0.000915,0.528222,0,0,0,...,4,0,0,0,0,0,0,0,2,10.480000
886189359bfffff,Bengaluru,0.110000,7.04,0,3502,0.005382,0.000516,0.376945,0,1,0,...,0,1,2,0,2,0,0,0,0,14.590000
88618935b1fffff,Bengaluru,0.320000,0.21,0,719,0.000339,0.000198,0.289855,0,0,0,...,0,0,0,0,0,0,0,0,0,25.000000
88618935b7fffff,Bengaluru,0.210000,6.06,0,774,0.000489,0.000441,0.353659,0,0,0,...,0,0,0,0,0,0,0,0,0,14.650000

In [231]:
# for i in df_3.columns:
#     if df_3[i].dtype == 'int64':
#         plt.figure(figsize=(5,3))
#         df_3[i].plot(kind="box")
#     elif df[i].dtype == 'float64':
#         plt.figure(figsize=(5,3))
#         df_3[i].plot(kind="box")
#     else:
#         print(f'{i} is neither an integer nor a float.')

In [515]:
from statsmodels.stats.outliers_influence import variance_inflation_factor 
X=df_3.iloc[:,:-1]
VIF=[variance_inflation_factor(X.values,i) for i in range(len(X.columns))]

In [516]:
X=pd.DataFrame({"columns_name":df_3.columns[:-1],"VIF":VIF})
X

                    columns_name       VIF
0            green_space_density  1.606525
1    public_infrastructure_index  2.625106
2            transportation_hubs  1.770407
3        total_digital_consumers  3.729195
4            pop_density_per_sqm  3.396295
5       building_density_per_sqm  2.322339
6              luxery_percentage  4.442863
7                auto_dealership  1.335974
8       auto_service_maintenance  1.742657
9          motorcycle_dealership  1.208289
10              truck_dealership  1.272374
11             government_office  1.803486
12              higher_education  1.869361
13                       library  1.563934
14                amusement_park  1.135159
15                bowling_centre  1.139727
16                        cinema  1.440064
17                   golf_course  1.016271
18              ice_skating_rink  1.112725
19                        museum  1.218153
20                     nightlife  1.749929
21                 sports_centre  2.765713
22                      hospital  1.964035
23               industrial_zone  1.076588
24                police_station  1.554332
25                clothing_store  1.845434
26    consumer_electronics_store  2.135964
27             convenience_store  1.532261
28              department_store  1.656184
29                 grocery_store  2.858278
30          home_specialty_store  2.587716
31  office_supply_services_store  2.284537
32       petrol_gasoline_station  1.629341
33          sporting_goods_store  1.768192
34                       airport  1.006003
35                   bus_station  1.303988
36                 train_station  1.231742
37                         hotel  1.555340

# Linear regression

In [523]:
x=df_3.iloc[:,:-1]
y=df_3.iloc[:,-1]

In [524]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1664, 38)
(1664,)
(416, 38)
(416,)

In [525]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [313]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [314]:
y_predict_train=model.predict(x_train)
y_predict_test=model.predict(x_test)

In [315]:
from sklearn import metrics
from sklearn.metrics import r2_score
print('mean Absolute error_of_train: ', metrics.mean_absolute_error(y_train,y_predict_train))
print('mean Absolute error_of_test: ', metrics.mean_absolute_error(y_test,y_predict_test))
print('mean squared error_of_train: ', metrics.mean_squared_error(y_train,y_predict_train))
print('mean squared error_of_test: ' , metrics.mean_squared_error(y_test,y_predict_test))
print('root mean Absolute error_of_train: ', np.sqrt(metrics.mean_squared_error(y_train,y_predict_train)))
print('root mean Absolute error_of_test: ', np.sqrt(metrics.mean_squared_error(y_test,y_predict_test)))
print("r2_on_train: ", r2_score(y_train,y_predict_train))
print("r2_on_test:  ", r2_score(y_test,y_predict_test))

mean Absolute error_of_train:  22.399214139241533
mean Absolute error_of_test:  20.53142986442124
mean squared error_of_train:  3205.8007913594
mean squared error_of_test:  1381.3191257000833
root mean Absolute error_of_train:  56.61979151638939
root mean Absolute error_of_test:  37.166101836217415
r2_on_train:  0.043890126857345724
r2_on_test:   0.0961318455325535

# Radom forest

In [426]:
from sklearn.ensemble import RandomForestRegressor
model_r=RandomForestRegressor(n_estimators=200,max_depth=1,random_state=42)

In [427]:
model_r.fit(x_train,y_train)

RandomForestRegressor(max_depth=1, n_estimators=200, random_state=42)

In [428]:
y_predict_train=model_r.predict(x_train)
y_predict_test=model_r.predict(x_test)

In [429]:
from sklearn import metrics
from sklearn.metrics import r2_score
print('mean Absolute error_of_train: ', metrics.mean_absolute_error(y_train,y_predict_train))
print('mean Absolute error_of_test: ', metrics.mean_absolute_error(y_test,y_predict_test))
print('mean squared error_of_train: ', metrics.mean_squared_error(y_train,y_predict_train))
print('mean squared error_of_test: ' , metrics.mean_squared_error(y_test,y_predict_test))
print('root mean Absolute error_of_train: ', np.sqrt(metrics.mean_squared_error(y_train,y_predict_train)))
print('root mean Absolute error_of_test: ', np.sqrt(metrics.mean_squared_error(y_test,y_predict_test)))
print("r2_on_train: ", r2_score(y_train,y_predict_train))
print("r2_on_test:  ", r2_score(y_test,y_predict_test))

mean Absolute error_of_train:  21.545822569452316
mean Absolute error_of_test:  28.39946150613369
mean squared error_of_train:  1598.3601410780286
mean squared error_of_test:  8867.05677693752
root mean Absolute error_of_train:  39.97949650856084
root mean Absolute error_of_test:  94.16505071913635
r2_on_train:  0.06528980920907657
r2_on_test:   0.003869884879611152

In [244]:
# random search

In [517]:
from sklearn.model_selection import RandomizedSearchCV
n_estimators= [int(x) for x in np.linspace(start=200,stop=3000,num=10)]
max_features=['auto','sqrt']
max_depth=[int(x) for x in np.linspace(start=10,stop=110,num=11)]
# when there is no max_depth it takes none so that the model go to its maximum extent 
max_depth.append(None)
min_samples_split = [2,5,10]
min_samples_leaf=[1,2,4]
bootstrap=[True,False]
# Create the random grid
random_grid={'n_estimators': n_estimators , 'max_features':max_features,
             'max_depth':max_depth,
             'min_samples_split':min_samples_split,'min_samples_leaf':min_samples_leaf,
            'bootstrap':bootstrap}
random_grid
rf=RandomForestRegressor(random_state=42)
# here cv is cross validation and n_jobs=-1 tell to run all trees simulteniously
rf_random=RandomizedSearchCV(estimator=rf,param_distributions=random_grid,n_iter=100,
                             scoring='neg_mean_absolute_error',cv=3,verbose=4,
                             random_state=42,n_jobs=-1,return_train_score=True)

rf2=rf_random.fit(x_train,y_train);
# by runninng below code we get  the parameter for best model
print("best parameter",rf2.best_params_)
y_pred=rf2.predict(x_test)
# Now accuracy improve
#accuracy_score(y_pred,y_test)
print("r2_on_train: ", (y_pred,y_test))
rf2.cv_results_
#importance=rf2.feature_importances_

Fitting 3 folds for each of 100 candidates, totalling 300 fits
best parameter {'n_estimators': 2866, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'max_depth': 20, 'bootstrap': False}
r2_on_train:  (array([56.69030886, 70.06242485, 26.86544803, 25.42076184, 18.34497068,
       74.62362305, 31.80274961, 24.09919888, 50.54478056, 17.01147442,
       48.6874621 , 40.31880894, 18.13660247, 32.89417436, 36.9321664 ,
       39.94823323, 45.77787695, 56.74935567, 29.92965545, 34.39441872,
       29.4059297 , 41.31747257, 34.31540759, 27.16577987, 53.46100823,
       49.9826681 , 37.06320041, 18.5549322 , 25.99147503, 33.73343412,
       36.47122459, 79.0524144 , 23.43959905, 28.56892152, 39.31777245,
       31.41487472, 23.95830807, 46.47141572, 33.86667289, 48.95394393,
       27.00010923, 28.35031272, 24.27622295, 43.63584012, 19.75309299,
       27.0781791 , 28.25444827, 25.94698072, 32.26988776, 26.53319026,
       43.65213433, 45.14016944, 27.8220635 , 45.60468541, 20.50503848,
       42.98067386, 43.55651575, 27.80466911, 23.05247123, 24.21048271,
       31.07630151, 48.56939347, 16.61980079, 58.05330853, 42.56778641,
       27.34059356, 23.81164037, 49.57381155, 27.83292066, 23.43249265,
       34.87172239, 41.94642255, 22.51426584, 18.48334437, 28.07683581,
       34.72402975, 35.21271016, 25.01504935, 22.20767126, 32.97846823,
       28.55610473, 28.62380843, 64.82061742, 24.46488725, 53.35140967,
       24.10888437, 19.20000072, 45.91287948, 26.2896376 , 49.50084604,
       19.19413742, 31.85608953, 75.86406562, 19.60965075, 39.28716896,
       57.5577529 , 55.51392174, 22.62015721, 54.85722583, 18.54644783,
       30.92012894, 35.61434331, 32.29681891, 32.53210203, 37.81317243,
       26.91446131, 26.00000677, 35.76769085, 18.78805905, 67.96173196,
       65.5132202 , 33.2721501 , 23.60787079, 20.60989558, 18.87520666,
       20.07142632, 41.42097746, 43.36064767, 20.55644608, 35.92224492,
       64.80087205, 76.97043947, 53.16239914, 23.13681471, 23.59392041,
       30.49676925, 20.44759091, 21.17359636, 14.77239877, 22.84763604,
       21.28967344, 54.46783303, 38.64756809, 26.4300702 , 39.40913947,
       36.77962045, 33.50426877, 26.08133342, 47.72770773, 29.68618098,
       29.15694839, 18.21020909, 19.99798389, 25.34098071, 27.12539113,
       21.01461385, 44.46419051, 30.495858  , 40.43791394, 77.42652861,
       32.70099583, 51.20537234, 23.20925168, 49.72273527, 50.76728393,
       46.84658006, 46.63576477, 32.80291404, 38.03464571, 53.82424453,
       26.43588679, 23.06991733, 38.98113192, 21.56993282, 25.65578734,
       35.90640025, 23.91215406, 37.12723757, 33.38811464, 20.32516269,
       53.42605958, 59.07852379, 29.03256116, 52.00113942, 26.09939936,
       26.12828091, 51.96946163, 19.83217772, 21.8610075 , 43.62420318,
       78.22700657, 29.73645194, 45.16023945, 65.61366834, 43.86893666,
       47.79705958, 47.16233587, 75.31198738, 18.06435219, 26.00863181,
       25.83289867, 21.52399481, 35.47921897, 28.76793519, 28.74571402,
       17.1958437 , 78.67705485, 38.10956127, 71.94902968, 24.54055454,
       43.31512029, 25.23544506, 32.01393879, 26.19689823, 23.3103169 ,
       17.95763343, 27.40801311, 21.9726274 , 33.61854836, 22.05995686,
       30.78202426, 61.39118961, 33.11247868, 47.53239579, 64.97242908,
       17.78765268, 20.40319702, 60.26151426, 41.29900931, 21.56560655,
       38.26537406, 31.27863271, 32.4524935 , 22.46224317, 16.00020291,
       51.63312947, 18.72217055, 20.49232413, 32.05464646, 21.35903884,
       67.0804515 , 32.13798658, 37.65197818, 40.29635038, 15.71440836,
       33.56750104, 72.82053702, 21.55526949, 20.45199671, 55.06768842,
       47.01208747, 28.61825868, 39.93305874, 41.55791841, 36.22985355,
       21.49599913, 52.04779797, 34.46058229, 19.93199547, 24.92839245,
       45.78094287, 24.90357152, 16.63207203, 18.51618118, 32.14396695,
       27.93679389, 44.25547808, 30.71305793, 34.98382248, 24.11104357,
       29.52735662, 41.65932736, 38.5532477 , 24.52180076, 25.92893565,
       26.80673297, 27.57722728, 28.20754248, 28.29513179, 56.07363708,
       38.50022877, 21.97520049, 49.30849505, 21.22086469, 52.56759441,
       23.45614552, 29.16863064, 31.09139287, 77.10069991, 22.08257307,
       20.21798078, 29.83082304, 30.48642513, 57.91925982, 27.25473005,
       18.3436985 , 78.51562899, 22.29317262, 40.58447017, 40.91441089,
       19.65377761, 22.47678638, 37.24724659, 45.8853096 , 27.70620631,
       53.38168959, 17.98400608, 35.66426731, 32.36557093, 25.98923224,
       47.49553503, 74.63463609, 68.49589152, 25.24307053, 51.26790141,
       23.24799618, 35.38756252, 35.95725744, 27.31866014, 60.0323694 ,
       42.77067009, 22.94492165, 37.43526149, 22.47656263, 28.61485551,
       27.00494351, 19.73211503, 22.86888138, 31.30439852, 25.38455965,
       38.05091273, 39.34217771, 25.05959149, 66.2901533 , 40.01010001,
       56.36971097, 25.40512667, 34.04817204, 18.68846927, 19.027844  ,
       23.51165955, 32.63931   , 25.2653701 , 57.68335803, 58.78420402,
       18.73926483, 57.28418654, 32.98376883, 43.83580306, 22.52479038,
       43.67241916, 62.31921783, 28.70497106, 20.92863209, 18.35965151,
       25.6500323 , 18.60903173, 34.2816013 , 19.06235783, 43.26792139,
       34.89854086, 31.5205471 , 37.74690384, 23.26855331, 26.57656492,
       35.19529546, 23.94094301, 19.91704219, 46.07035838, 31.77858317,
       67.41719771, 18.64773832, 43.36083085, 36.45669251, 40.04233495,
       29.87617324, 26.68090896, 34.77564167, 61.82008943, 25.7712793 ,
       50.66730533, 28.86911608, 42.58140738, 46.15296832, 26.58302644,
       40.33858505, 22.91293372, 55.48893386, 34.23756809, 30.75717738,
       52.71864474, 30.07931731, 36.84381885, 38.3043807 , 50.36702665,
       34.16020602, 49.84492371, 38.35712158]), 5075     55.224339
4735    125.000000
4271     21.200000
5831     16.060000
4217     13.700000
           ...
6153     20.850000
5234     59.154930
183      25.415218
5082     43.265306
1146     15.111111
Name: average_monthly_residential_rental_price, Length: 388, dtype: float64)

{'mean_fit_time': array([  3.78802713,  17.49707198,  11.62087623, 100.5602258 ,
         12.29008134,   7.29976288,  11.42307019,   6.39729651,
         71.53032645,  74.51663391,   9.35051386,   9.45272509,
         18.45402503,  15.08796581,   8.22918383,  90.80905573,
         30.30168899,  11.35999147,  99.7579786 ,  21.80493871,
         21.45583574,  21.82563106,  11.64628458,  70.17094827,
         18.05363957,   5.01082182, 104.46538742,   8.80742868,
         99.49328208,  11.14843321,  11.62579425,   9.17385117,
          9.76214886,   5.96745094,  15.80991864,   8.0103147 ,
         11.05626456,  35.57468255,  27.88826227,   9.76817346,
          2.35945288,   4.81934929,   6.60830188,   2.59656175,
          5.04902625,  11.89555613,  77.87275608,   3.17481558,
         12.57041939,   6.64985879, 132.56399417, 110.71462552,
         45.09743063,  47.50170175,  16.47177664,   5.30390716,
         50.0634462 ,  71.89906653,  67.62328768,  12.26567682,
          1.01130342,   2.41868718,  47.08073131,  63.99340892,
         15.38322576,  56.28883306,  74.67120393,  53.03880755,
         11.04524016, 111.5443178 ,  14.06895177,   7.62102222,
         17.34600981,  20.3813978 ,  67.77453311,   3.21912352,
         15.02919086,  21.03362711,   7.79666893,   2.55372429,
        101.48072815,  18.00131226,  29.55608257,  40.16966462,
          7.39092716,   6.01838748,   3.19698985,  13.72028732,
          6.22128701,   7.80779131,   5.16831271,  21.29099886,
          7.69242843,  15.95871846,   5.25044179,  16.29095443,
         37.71272103,   3.99544295,  18.5660669 ,  55.20085049]),
 'std_fit_time': array([1.74566152e-01, 1.41014340e-01, 6.61443545e-02, 3.55842582e+00,
        7.21343859e-02, 2.67644228e-02, 1.35769876e-01, 2.37459270e-01,
        3.45967922e-01, 1.16757005e+00, 2.83512807e-01, 7.47972516e-02,
        1.74234831e-01, 2.86742295e-01, 1.59178920e-01, 3.17679148e+00,
        1.16891130e+00, 2.63365924e-01, 4.00112815e+00, 1.93128577e-01,
        3.50090234e-01, 5.37203030e-01, 3.71784005e-01, 5.47116633e-01,
        1.64185824e-01, 3.27450470e-02, 1.25194117e+00, 7.65763054e-02,
        3.33751602e+00, 2.26940542e-01, 3.49814291e-01, 5.51597152e-02,
        3.21189954e-02, 3.45742170e-02, 9.31063446e-02, 3.11875375e-01,
        3.52572230e-01, 6.37728714e-01, 5.55321200e-01, 2.70391353e-01,
        6.35698525e-02, 8.98939471e-02, 7.33195269e-02, 6.44680388e-02,
        1.81292398e-01, 4.84305023e-02, 1.05527036e+00, 6.30239495e-02,
        7.57506913e-02, 7.81725171e-02, 1.30818458e+00, 6.49801404e+00,
        1.63491146e+00, 2.58398116e+00, 1.58365580e-01, 1.06794601e-01,
        3.75138445e-01, 5.97149396e-01, 1.22281555e+00, 9.38593946e-02,
        3.94429457e-03, 3.38288365e-02, 1.33585234e+00, 2.72310942e+00,
        3.51118669e-01, 7.30590122e-01, 1.09303663e+00, 6.61199937e-01,
        9.93261961e-02, 5.11522458e+00, 3.36558070e-01, 1.02598074e-01,
        1.30852765e-01, 1.33698524e-01, 4.13569868e-01, 3.37334615e-02,
        3.10397040e-02, 1.51283087e-01, 6.53964585e-02, 7.41372734e-03,
        2.82821994e+00, 2.79806416e-01, 4.00830972e-01, 1.93324446e+00,
        1.15684978e-01, 3.07878316e-02, 1.18515816e-01, 3.93283674e-01,
        2.16613253e-01, 1.94746926e-01, 2.76897137e-01, 2.14740625e-01,
        1.24529748e-01, 6.46784439e-02, 1.96293755e-02, 7.57994688e-01,
        1.92282416e-01, 1.08486569e-01, 9.01442500e-02, 1.96929618e-01]),
 'mean_score_time': array([0.15164638, 0.69205658, 0.44936474, 0.76407226, 0.57020084,
        0.2722524 , 0.43518821, 0.21441499, 0.5130949 , 0.59915582,
        0.10988124, 0.32186111, 0.72838211, 0.65420008, 0.3402106 ,
        0.7048707 , 0.2169563 , 0.44513694, 0.72629937, 0.25698932,
        0.74937749, 0.78599223, 0.51557716, 0.76949215, 0.62149278,
        0.15175748, 0.72084045, 0.3973976 , 0.78521419, 0.4973646 ,
        0.45505269, 0.34025709, 0.34996184, 0.26810694, 0.75435424,
        0.2984395 , 0.55274328, 0.38738759, 0.32137489, 0.42079814,
        0.03738459, 0.20200602, 0.30107379, 0.11534286, 0.0315458 ,
        0.47108452, 0.93010767, 0.12173239, 0.46069233, 0.24077686,
        0.93967621, 0.81600459, 0.35330455, 0.36606375, 0.65051468,
        0.20407947, 0.60710875, 0.78595726, 0.72823596, 0.55063049,
        0.04704269, 0.11837935, 0.37319279, 0.43937635, 0.64260419,
        0.62404092, 0.62241125, 0.58593909, 0.40045746, 0.77937325,
        0.58865293, 0.33737699, 0.72742883, 0.13612461, 0.69608585,
        0.12079008, 0.65648373, 0.87843585, 0.33483434, 0.03646167,
        0.76963695, 0.25218908, 0.38923693, 0.29815769, 0.28226821,
        0.22583508, 0.13082544, 0.61234275, 0.29341785, 0.34871562,
        0.23543398, 0.85187443, 0.32963252, 0.2148126 , 0.20935416,
        0.10696801, 0.24577665, 0.03159769, 0.77368959, 0.58290776]),
 'std_score_time': array([0.00784421, 0.04227341, 0.02919947, 0.00759498, 0.03917034,
        0.00735255, 0.048377  , 0.01470005, 0.01192108, 0.01343559,
        0.0001025 , 0.01104261, 0.01904619, 0.06236966, 0.02971705,
        0.00251782, 0.01395981, 0.01521922, 0.01257223, 0.03072938,
        0.01368596, 0.04713455, 0.0042191 , 0.01326755, 0.00689102,
        0.00727787, 0.01471717, 0.01949833, 0.01251396, 0.02655637,
        0.02229431, 0.02178973, 0.01038986, 0.00104678, 0.04070884,
        0.01273782, 0.06438707, 0.01960177, 0.02264248, 0.02199613,
        0.0049239 , 0.01077376, 0.0133768 , 0.00778065, 0.00021165,
        0.01305165, 0.03219831, 0.00521598, 0.0071514 , 0.01492228,
        0.02338875, 0.0392339 , 0.00643192, 0.01524472, 0.02408133,
        0.0127501 , 0.02662937, 0.02892557, 0.05078238, 0.02603817,
        0.00020094, 0.0121007 , 0.00529362, 0.01306135, 0.01464544,
        0.01667849, 0.01960247, 0.00763797, 0.00638453, 0.00730713,
        0.04001008, 0.03207765, 0.00709249, 0.0072459 , 0.01944364,
        0.0032527 , 0.00908397, 0.02471711, 0.00728608, 0.00735913,
        0.03294773, 0.03922189, 0.03698416, 0.00020577, 0.00291627,
        0.00678923, 0.00727175, 0.02250243, 0.00681902, 0.02164523,
        0.01293   , 0.02022294, 0.00657429, 0.01982121, 0.0148124 ,
        0.02033744, 0.03428945, 0.00048329, 0.01427803, 0.04333735]),
 'param_n_estimators': masked_array(data=[733, 5000, 2866, 5000, 3933, 1800, 2333, 1266, 2333,
                    4466, 733, 1800, 5000, 3933, 1800, 4466, 1266, 2333,
                    4466, 1266, 4466, 3933, 3400, 4466, 3400, 733, 3400,
                    2333, 5000, 2866, 2866, 1800, 1800, 1800, 4466, 1800,
                    2866, 1800, 1800, 2333, 200, 1266, 1800, 733, 200,
                    2333, 5000, 733, 2866, 1266, 4466, 5000, 2333, 2333,
                    3400, 1266, 3933, 4466, 3400, 3400, 200, 733, 2333,
                    2866, 3933, 3933, 4466, 3400, 2333, 5000, 3400, 1800,
                    4466, 733, 3933, 733, 3933, 5000, 2333, 200, 5000,
                    1266, 2333, 1800, 1800, 1266, 733, 3933, 1800, 2333,
                    1266, 5000, 1800, 1266, 1266, 733, 2333, 200, 5000,
                    5000],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[5, 5, 5, 2, 2, 5, 5, 5, 2, 5, 10, 5, 10, 5, 10, 2, 5,
                    2, 10, 5, 10, 5, 5, 2, 5, 2, 2, 5, 10, 2, 10, 2, 5, 10,
                    2, 10, 5, 2, 5, 2, 5, 10, 2, 10, 5, 2, 2, 10, 2, 2, 2,
                    10, 10, 5, 5, 2, 5, 2, 2, 10, 2, 2, 10, 10, 10, 10, 2,
                    2, 10, 10, 2, 2, 5, 5, 5, 10, 10, 5, 5, 5, 2, 10, 5,
                    10, 5, 10, 5, 2, 10, 10, 10, 5, 5, 2, 2, 10, 2, 5, 2,
                    10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_leaf': masked_array(data=[1, 1, 2, 4, 4, 4, 2, 1, 1, 4, 4, 1, 1, 2, 2, 4, 2, 1,
                    2, 1, 1, 1, 4, 2, 1, 1, 1, 2, 4, 2, 4, 2, 1, 4, 4, 2,
                    2, 1, 2, 2, 4, 2, 4, 4, 2, 1, 2, 4, 4, 2, 1, 2, 4, 4,
                    2, 4, 1, 2, 1, 2, 1, 4, 4, 2, 1, 2, 4, 2, 1, 2, 4, 4,
                    2, 1, 1, 2, 1, 1, 2, 4, 4, 2, 4, 2, 4, 1, 1, 4, 4, 2,
                    1, 4, 1, 4, 4, 2, 1, 4, 2, 2],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_max_features': masked_array(data=['sqrt', 'sqrt', 'sqrt', 'auto', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'auto', 'auto', 'auto', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'auto', 'auto', 'sqrt', 'auto', 'auto', 'sqrt',
                    'sqrt', 'sqrt', 'auto', 'sqrt', 'sqrt', 'auto', 'sqrt',
                    'auto', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'sqrt', 'auto', 'auto', 'sqrt', 'auto', 'sqrt',
                    'sqrt', 'sqrt', 'auto', 'sqrt', 'auto', 'sqrt', 'sqrt',
                    'sqrt', 'auto', 'auto', 'auto', 'auto', 'sqrt', 'sqrt',
                    'auto', 'auto', 'auto', 'sqrt', 'sqrt', 'sqrt', 'auto',
                    'auto', 'sqrt', 'auto', 'auto', 'auto', 'sqrt', 'auto',
                    'sqrt', 'sqrt', 'sqrt', 'auto', 'auto', 'sqrt', 'sqrt',
                    'sqrt', 'sqrt', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'sqrt', 'auto', 'sqrt', 'auto', 'auto', 'auto',
                    'sqrt', 'auto'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_max_depth': masked_array(data=[30, 10, 10, 30, 10, 30, 100, 60, 50, 10, 70, 90, 10,
                    10, 30, 50, 70, 20, 110, 80, 30, 70, 80, None, 80,
                    None, 40, 20, 100, 20, 20, 50, 100, 50, 90, 20, 20,
                    100, None, 60, 10, 60, 90, 90, 90, 110, 90, 80, 70,
                    110, 20, 50, 50, 30, None, 60, 10, 80, 100, 80, 50, 10,
                    80, None, 20, None, 10, 70, 80, 60, 80, 20, 60, 90, 90,
                    90, None, 100, 10, 80, 60, 100, 100, None, 70, 40, 100,
                    80, 100, 10, 110, None, 40, 40, 30, 40, 10, 100, 20,
                    40],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_bootstrap': masked_array(data=[True, True, False, False, True, False, False, False,
                    False, False, True, False, False, False, False, False,
                    False, True, False, True, False, False, True, True,
                    False, False, False, True, False, True, False, False,
                    False, True, True, False, True, True, True, True, True,
                    True, True, True, False, True, True, False, False,
                    False, False, False, False, False, False, False, True,
                    True, True, True, True, True, False, False, True, True,
                    False, True, False, False, False, False, True, False,
                    True, False, True, True, True, True, False, True, True,
                    False, False, False, True, True, True, True, True,
                    False, True, True, False, False, False, False, True,
                    True],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_estimators': 733,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'max_features': 'sqrt',
   'max_depth': 30,
   'bootstrap': True},
  {'n_estimators': 5000,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'max_features': 'sqrt',
   'max_depth': 10,
   'bootstrap': True},
  {'n_estimators': 2866,
   'min_samples_split': 5,
   'min_samples_leaf': 2,
   'max_features': 'sqrt',
   'max_depth': 10,
   'bootstrap': False},
  {'n_estimators': 5000,
   'min_samples_split': 2,
   'min_samples_leaf': 4,
   'max_features': 'auto',
   'max_depth': 30,
   'bootstrap': False},
  {'n_estimators': 3933,
   'min_samples_split': 2,
   'min_samples_leaf': 4,
   'max_features': 'sqrt',
   'max_depth': 10,
   'bootstrap': True},
  {'n_estimators': 1800,
   'min_samples_split': 5,
   'min_samples_leaf': 4,
   'max_features': 'sqrt',
   'max_depth': 30,
   'bootstrap': False},
  {'n_estimators': 2333,
   'min_samples_split': 5,
   'min_samples_leaf': 2,
   'max_features': 'sqrt',
   'max_depth': 100,
   'bootstrap': False},
  {'n_estimators': 1266,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'max_features': 'sqrt',
   'max_depth': 60,
   'bootstrap': False},
  {'n_estimators': 2333,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'max_features': 'auto',
   'max_depth': 50,
   'bootstrap': False},
  {'n_estimators': 4466,
   'min_samples_split': 5,
   'min_samples_leaf': 4,
   'max_features': 'auto',
   'max_depth': 10,
   'bootstrap': False},
  {'n_estimators': 733,
   'min_samples_split': 10,
   'min_samples_leaf': 4,
   'max_features': 'auto',
   'max_depth': 70,
   'bootstrap': True},
  {'n_estimators': 1800,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'max_features': 'sqrt',
   'max_depth': 90,
   'bootstrap': False},
  {'n_estimators': 5000,
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'max_features': 'sqrt',
   'max_depth': 10,
   'bootstrap': False},
  {'n_estimators': 3933,
   'min_samples_split': 5,
   'min_samples_leaf': 2,
   'max_features': 'sqrt',
   'max_depth': 10,
   'bootstrap': False},
  {'n_estimators': 1800,
   'min_samples_split': 10,
   'min_samples_leaf': 2,
   'max_features': 'sqrt',
   'max_depth': 30,
   'bootstrap': False},
  {'n_estimators': 4466,
   'min_samples_split': 2,
   'min_samples_leaf': 4,
   'max_features': 'auto',
   'max_depth': 50,
   'bootstrap': False},
  {'n_estimators': 1266,
   'min_samples_split': 5,
   'min_samples_leaf': 2,
   'max_features': 'auto',
   'max_depth': 70,
   'bootstrap': False},
  {'n_estimators': 2333,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'max_features': 'sqrt',
   'max_depth': 20,
   'bootstrap': True},
  {'n_estimators': 4466,
   'min_samples_split': 10,
   'min_samples_leaf': 2,
   'max_features': 'auto',
   'max_depth': 110,
   'bootstrap': False},
  {'n_estimators': 1266,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'max_features': 'auto',
   'max_depth': 80,
   'bootstrap': True},
  {'n_estimators': 4466,
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'max_features': 'sqrt',
   'max_depth': 30,
   'bootstrap': False},
  {'n_estimators': 3933,
   'min_samples_split': 5,
   'min_samples_leaf': 1,

In [526]:
from sklearn.ensemble import RandomForestRegressor
model_r_b=RandomForestRegressor(n_estimators=2886,min_samples_split=10,min_samples_leaf=4,max_features='sqrt',max_depth=20,bootstrap= False )

In [527]:
x_test.shape

(416, 38)

In [528]:
model_r_b.fit(x_train,y_train)

RandomForestRegressor(bootstrap=False, max_depth=20, max_features='sqrt',
                      min_samples_leaf=4, min_samples_split=10,
                      n_estimators=2886)

In [529]:
y_predict_train=model_r_b.predict(x_train)
y_predict_test=model_r_b.predict(x_test)

In [530]:
from sklearn import metrics
from sklearn.metrics import r2_score
print('mean Absolute error_of_train: ', metrics.mean_absolute_error(y_train,y_predict_train))
print('mean Absolute error_of_test: ', metrics.mean_absolute_error(y_test,y_predict_test))
print('mean squared error_of_train: ', metrics.mean_squared_error(y_train,y_predict_train))
print('mean squared error_of_test: ' , metrics.mean_squared_error(y_test,y_predict_test))
print('root mean Absolute error_of_train: ', np.sqrt(metrics.mean_squared_error(y_train,y_predict_train)))
print('root mean Absolute error_of_test: ', np.sqrt(metrics.mean_squared_error(y_test,y_predict_test)))
print("r2_on_train: ", r2_score(y_train,y_predict_train))
print("r2_on_test:  ", r2_score(y_test,y_predict_test))

mean Absolute error_of_train:  12.802364805471672
mean Absolute error_of_test:  19.289037898710284
mean squared error_of_train:  1601.472639785265
mean squared error_of_test:  1317.9066506219135
root mean Absolute error_of_train:  40.01840376358439
root mean Absolute error_of_test:  36.302984045694004
r2_on_train:  0.5223708826220508
r2_on_test:   0.13762588970577738

# prediction

In [531]:
df_for_predict=df[df['average_monthly_residential_rental_price'].isnull()]

In [532]:
df_for_predict.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4339 entries, ('883cf28967fffff', 'Kolkata') to ('88618935d7fffff', 'Bengaluru')
Data columns (total 53 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   green_space_density                       4339 non-null   float64
 1   public_infrastructure_index               4339 non-null   float64
 2   road_length                               4182 non-null   float64
 3   transportation_hubs                       4339 non-null   int64
 4   daily_avg_footfall                        4339 non-null   int64
 5   total_digital_consumers                   4339 non-null   int64
 6   pop_density_per_sqm                       4339 non-null   float64
 7   building_density_per_sqm                  4339 non-null   float64
 8   luxery_percentage                         3844 non-null   float64
 9   auto_dealership                           4339 non-null   int64
 10  auto_service_maintenance                  4339 non-null   int64
 11  motorcycle_dealership                     4339 non-null   int64
 12  truck_dealership                          4339 non-null   int64
 13  business_facility                         4339 non-null   int64
 14  government_office                         4339 non-null   int64
 15  higher_education                          4339 non-null   int64
 16  library                                   4339 non-null   int64
 17  school                                    4339 non-null   int64
 18  training_centre_institute                 4339 non-null   int64
 19  amusement_park                            4339 non-null   int64
 20  bowling_centre                            4339 non-null   int64
 21  cinema                                    4339 non-null   int64
 22  golf_course                               4339 non-null   int64
 23  ice_skating_rink                          4339 non-null   int64
 24  museum                                    4339 non-null   int64
 25  nightlife                                 4339 non-null   int64
 26  sports_centre                             4339 non-null   int64
 27  atm                                       4339 non-null   int64
 28  bank                                      4339 non-null   int64
 29  hospital                                  4339 non-null   int64
 30  medical_service                           4339 non-null   int64
 31  pharmacy                                  4339 non-null   int64
 32  industrial_zone                           4339 non-null   int64
 33  police_station                            4339 non-null   int64
 34  bar_or_pub                                4339 non-null   int64
 35  coffee_shop                               4339 non-null   int64
 36  restaurant                                4339 non-null   int64
 37  clothing_store                            4339 non-null   int64
 38  consumer_electronics_store                4339 non-null   int64
 39  convenience_store                         4339 non-null   int64
 40  department_store                          4339 non-null   int64
 41  grocery_store                             4339 non-null   int64
 42  home_improvement_hardware_store           4339 non-null   int64
 43  home_specialty_store                      4339 non-null   int64
 44  office_supply_services_store              4339 non-null   int64
 45  petrol_gasoline_station                   4339 non-null   int64
 46  shopping                                  4339 non-null   int64
 47  sporting_goods_store                      4339 non-null   int64
 48  airport                                   4339 non-null   int64
 49  bus_station                               4339 non-null   int64
 50  train_station                             4339 non-null   int64
 51  hotel                                     4339 non-null   int64
 52  average_monthly_residential_rental_price  0 non-null      float64
dtypes: float64(7), int64(46)
memory usage: 2.1+ MB

In [536]:
df_for_predict=df_for_predict.set_index(['hexid08','t_name'])
df_for_predict=df_for_predict.drop(columns=['shopping','medical_service','atm','bank','road_length','home_improvement_hardware_store','bar_or_pub','coffee_shop','business_facility','pharmacy','daily_avg_footfall','school','restaurant','training_centre_institute'])

In [537]:
df_for_predict=df_for_predict.iloc[:,:-1]

In [538]:
print(df_for_predict.shape)
df_for_predict.head(5)

(4339, 38)

,,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,auto_dealership,auto_service_maintenance,motorcycle_dealership,...,department_store,grocery_store,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel
hexid08,t_name,,,,,,,,,,,,,,,,,,,,,
883cf28967fffff,Kolkata,0.307185,4.03,5,3899,0.021658,0.002213,0.210287,0,2,0,...,1,1,0,0,3,0,0,1,1,0
883cf2896dfffff,Kolkata,0.121495,12.49,3,4264,0.037795,0.002368,0.317716,1,24,0,...,2,13,0,0,2,2,0,1,0,1
883cf28b21fffff,Kolkata,0.120029,6.56,0,4099,0.038877,0.004853,0.184938,0,9,0,...,1,5,6,0,3,5,0,0,0,0
883cf28b25fffff,Kolkata,0.085088,6.16,0,3991,0.042532,0.006564,0.361712,0,1,0,...,0,1,0,0,0,0,0,0,0,0
883cf2c013fffff,Kolkata,0.927586,0.00,0,9862,0.002810,0.001448,0.197183,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [539]:
df_for_predict=df_for_predict.dropna()
print(df_for_predict.shape)
df_for_predict.head(5)

(3844, 38)

,,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,auto_dealership,auto_service_maintenance,motorcycle_dealership,...,department_store,grocery_store,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel
hexid08,t_name,,,,,,,,,,,,,,,,,,,,,
883cf28967fffff,Kolkata,0.307185,4.03,5,3899,0.021658,0.002213,0.210287,0,2,0,...,1,1,0,0,3,0,0,1,1,0
883cf2896dfffff,Kolkata,0.121495,12.49,3,4264,0.037795,0.002368,0.317716,1,24,0,...,2,13,0,0,2,2,0,1,0,1
883cf28b21fffff,Kolkata,0.120029,6.56,0,4099,0.038877,0.004853,0.184938,0,9,0,...,1,5,6,0,3,5,0,0,0,0
883cf28b25fffff,Kolkata,0.085088,6.16,0,3991,0.042532,0.006564,0.361712,0,1,0,...,0,1,0,0,0,0,0,0,0,0
883cf2c013fffff,Kolkata,0.927586,0.00,0,9862,0.002810,0.001448,0.197183,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [542]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
predict_scale=sc.fit_transform(df_for_predict)

In [543]:
new_data_predict=model_r_b.predict(predict_scale)

In [544]:
new_data_predict

array([32.13914308, 33.01109047, 36.09986191, ..., 25.3880461 ,
       26.06252503, 29.60781642])

In [545]:
df_for_predict['rent']=new_data_predict
df_for_predict['predicted']="yes"

In [546]:
df_for_predict=df_for_predict.reset_index()

In [573]:
df_for_delhi_pre=df_for_predict[df_for_predict['t_name']=='Delhi']

In [574]:
df_for_delhi_pre

,hexid08,t_name,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,auto_dealership,...,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,rent,predicted
184,883da10003fffff,Delhi,0.198031,16.41,0,5755,0.000531,0.000431,0.232639,0,...,0,0,0,0,0,0,0,0,28.184289,yes
185,883da10005fffff,Delhi,0.517805,6.16,0,6383,0.000446,0.000388,0.571429,0,...,0,0,0,0,0,0,0,0,33.924530,yes
186,883da10007fffff,Delhi,0.493969,4.10,0,5371,0.000592,0.000615,0.646154,0,...,0,0,0,0,0,0,0,0,32.557243,yes
187,883da10009fffff,Delhi,0.679111,6.16,0,6100,0.000399,0.000317,0.273196,0,...,0,0,0,0,0,0,0,0,33.710574,yes
188,883da1000bfffff,Delhi,0.590127,2.05,0,5789,0.000279,0.000203,0.171429,0,...,0,0,0,0,0,0,0,0,29.632257,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2329,883da1d4e7fffff,Delhi,0.030639,1.57,0,279,0.000050,0.000109,0.428571,0,...,0,0,0,0,0,0,0,0,28.573229,yes
2330,883da1d593fffff,Delhi,0.003509,0.00,0,267,0.000000,0.000010,0.250000,0,...,0,0,0,0,0,0,0,0,27.570131,yes
2331,883da1d5b3fffff,Delhi,0.127471,0.00,0,267,0.000000,0.000003,0.061538,0,...,0,0,0,0,0,0,0,0,28.763842,yes
2332,883da1d5bbfffff,Delhi,0.048453,0.00,0,296,0.003594,0.000339,0.550000,0,...,0,0,0,0,0,0,0,0,27.895054,yes
2333,883da1d5d3fffff,Delhi,0.000226,0.00,0,265,0.005203,0.000097,0.400000,0,...,0,0,0,0,0,0,0,0,34.599591,yes

In [567]:
df_3

,,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,auto_dealership,auto_service_maintenance,motorcycle_dealership,...,grocery_store,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price
hexid08,t_name,,,,,,,,,,,,,,,,,,,,,
883cf28945fffff,Kolkata,0.086059,6.84,5,3982,0.056038,0.004971,0.244236,0,3,0,...,45,5,0,0,0,0,1,0,0,13.491124
883cf28949fffff,Kolkata,0.169749,4.10,0,3725,0.037358,0.004139,0.309732,0,0,0,...,0,1,0,0,0,0,0,0,0,10.000000
883cf2894dfffff,Kolkata,0.311278,0.37,0,3403,0.030660,0.003579,0.469274,0,2,0,...,18,1,0,0,0,0,0,0,0,10.575139
883cf28961fffff,Kolkata,0.232866,11.60,0,4111,0.028392,0.003431,0.341649,0,2,0,...,12,1,3,0,1,0,0,0,0,22.123577
883cf28965fffff,Kolkata,0.149823,13.25,5,4157,0.029187,0.001848,0.277745,0,5,0,...,0,0,0,0,0,0,2,2,1,16.339713
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8861893591fffff,Bengaluru,0.180000,0.00,0,378,0.002130,0.000351,0.356000,0,0,0,...,0,0,0,0,0,0,0,0,0,11.330000
8861893597fffff,Bengaluru,0.000000,0.49,1,5383,0.006280,0.000915,0.528222,0,0,0,...,4,0,0,0,0,0,0,0,2,10.480000
886189359bfffff,Bengaluru,0.110000,7.04,0,3502,0.005382,0.000516,0.376945,0,1,0,...,0,1,2,0,2,0,0,0,0,14.590000
88618935b1fffff,Bengaluru,0.320000,0.21,0,719,0.000339,0.000198,0.289855,0,0,0,...,0,0,0,0,0,0,0,0,0,25.000000
88618935b7fffff,Bengaluru,0.210000,6.06,0,774,0.000489,0.000441,0.353659,0,0,0,...,0,0,0,0,0,0,0,0,0,14.650000

In [568]:
df_3=df_3.reset_index()

In [569]:
df_3

,hexid08,t_name,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,auto_dealership,...,grocery_store,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price
0,883cf28945fffff,Kolkata,0.086059,6.84,5,3982,0.056038,0.004971,0.244236,0,...,45,5,0,0,0,0,1,0,0,13.491124
1,883cf28949fffff,Kolkata,0.169749,4.10,0,3725,0.037358,0.004139,0.309732,0,...,0,1,0,0,0,0,0,0,0,10.000000
2,883cf2894dfffff,Kolkata,0.311278,0.37,0,3403,0.030660,0.003579,0.469274,0,...,18,1,0,0,0,0,0,0,0,10.575139
3,883cf28961fffff,Kolkata,0.232866,11.60,0,4111,0.028392,0.003431,0.341649,0,...,12,1,3,0,1,0,0,0,0,22.123577
4,883cf28965fffff,Kolkata,0.149823,13.25,5,4157,0.029187,0.001848,0.277745,0,...,0,0,0,0,0,0,2,2,1,16.339713
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2075,8861893591fffff,Bengaluru,0.180000,0.00,0,378,0.002130,0.000351,0.356000,0,...,0,0,0,0,0,0,0,0,0,11.330000
2076,8861893597fffff,Bengaluru,0.000000,0.49,1,5383,0.006280,0.000915,0.528222,0,...,4,0,0,0,0,0,0,0,2,10.480000
2077,886189359bfffff,Bengaluru,0.110000,7.04,0,3502,0.005382,0.000516,0.376945,0,...,0,1,2,0,2,0,0,0,0,14.590000
2078,88618935b1fffff,Bengaluru,0.320000,0.21,0,719,0.000339,0.000198,0.289855,0,...,0,0,0,0,0,0,0,0,0,25.000000
2079,88618935b7fffff,Bengaluru,0.210000,6.06,0,774,0.000489,0.000441,0.353659,0,...,0,0,0,0,0,0,0,0,0,14.650000

In [571]:
df_3_delhi=df_3[df_3["t_name"]=="Delhi"]

In [572]:
df_3_delhi

,hexid08,t_name,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,auto_dealership,...,grocery_store,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price
162,883da10001fffff,Delhi,0.525175,6.16,0,6351,0.000511,0.000475,0.179153,0,...,0,0,0,0,0,0,0,0,0,20.250000
163,883da10017fffff,Delhi,0.144150,0.00,0,1805,0.000000,0.000000,0.090909,0,...,0,0,0,0,0,0,0,0,0,22.067039
164,883da10043fffff,Delhi,0.375772,2.88,2,6983,0.001698,0.000930,0.509684,0,...,12,0,1,0,1,0,0,0,8,20.997480
165,883da10049fffff,Delhi,0.573691,2.05,0,5937,0.000646,0.000519,0.315978,0,...,0,0,0,0,0,0,0,0,0,17.317487
166,883da10059fffff,Delhi,0.201659,6.16,0,7339,0.009096,0.003071,0.329188,0,...,4,0,4,0,0,0,0,0,0,19.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927,883da1bb27fffff,Delhi,0.154237,0.00,1,164,0.006174,0.001632,0.249356,0,...,11,1,1,0,0,0,0,0,0,12.500000
928,883da1bb35fffff,Delhi,0.007565,2.05,3,205,0.010274,0.001707,0.298561,0,...,9,10,2,0,1,0,0,0,0,19.132001
929,883da1bb37fffff,Delhi,0.008243,4.24,15,222,0.017205,0.001818,0.424406,0,...,10,32,5,0,2,0,0,0,0,26.666667
930,883da1bb61fffff,Delhi,0.000000,5.13,6,220,0.007036,0.001469,0.642667,0,...,41,11,6,0,0,0,0,0,0,12.222222
931,883da1bb6dfffff,Delhi,0.004404,2.76,1,233,0.006139,0.001394,0.406602,0,...,19,2,0,0,0,0,0,0,0,11.666667

In [575]:
df_for_delhi_pre

,hexid08,t_name,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,auto_dealership,...,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,rent,predicted
184,883da10003fffff,Delhi,0.198031,16.41,0,5755,0.000531,0.000431,0.232639,0,...,0,0,0,0,0,0,0,0,28.184289,yes
185,883da10005fffff,Delhi,0.517805,6.16,0,6383,0.000446,0.000388,0.571429,0,...,0,0,0,0,0,0,0,0,33.924530,yes
186,883da10007fffff,Delhi,0.493969,4.10,0,5371,0.000592,0.000615,0.646154,0,...,0,0,0,0,0,0,0,0,32.557243,yes
187,883da10009fffff,Delhi,0.679111,6.16,0,6100,0.000399,0.000317,0.273196,0,...,0,0,0,0,0,0,0,0,33.710574,yes
188,883da1000bfffff,Delhi,0.590127,2.05,0,5789,0.000279,0.000203,0.171429,0,...,0,0,0,0,0,0,0,0,29.632257,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2329,883da1d4e7fffff,Delhi,0.030639,1.57,0,279,0.000050,0.000109,0.428571,0,...,0,0,0,0,0,0,0,0,28.573229,yes
2330,883da1d593fffff,Delhi,0.003509,0.00,0,267,0.000000,0.000010,0.250000,0,...,0,0,0,0,0,0,0,0,27.570131,yes
2331,883da1d5b3fffff,Delhi,0.127471,0.00,0,267,0.000000,0.000003,0.061538,0,...,0,0,0,0,0,0,0,0,28.763842,yes
2332,883da1d5bbfffff,Delhi,0.048453,0.00,0,296,0.003594,0.000339,0.550000,0,...,0,0,0,0,0,0,0,0,27.895054,yes
2333,883da1d5d3fffff,Delhi,0.000226,0.00,0,265,0.005203,0.000097,0.400000,0,...,0,0,0,0,0,0,0,0,34.599591,yes

In [ ]:
2738

In [580]:
1814+586

2400

In [594]:
df_delhi=pd.concat([df_3_delhi, df_for_delhi_pre])

In [595]:
df_delhi

,hexid08,t_name,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,auto_dealership,...,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price,rent,predicted
162,883da10001fffff,Delhi,0.525175,6.16,0,6351,0.000511,0.000475,0.179153,0,...,0,0,0,0,0,0,0,20.250000,NaN,NaN
163,883da10017fffff,Delhi,0.144150,0.00,0,1805,0.000000,0.000000,0.090909,0,...,0,0,0,0,0,0,0,22.067039,NaN,NaN
164,883da10043fffff,Delhi,0.375772,2.88,2,6983,0.001698,0.000930,0.509684,0,...,1,0,1,0,0,0,8,20.997480,NaN,NaN
165,883da10049fffff,Delhi,0.573691,2.05,0,5937,0.000646,0.000519,0.315978,0,...,0,0,0,0,0,0,0,17.317487,NaN,NaN
166,883da10059fffff,Delhi,0.201659,6.16,0,7339,0.009096,0.003071,0.329188,0,...,4,0,0,0,0,0,0,19.444444,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2329,883da1d4e7fffff,Delhi,0.030639,1.57,0,279,0.000050,0.000109,0.428571,0,...,0,0,0,0,0,0,0,NaN,28.573229,yes
2330,883da1d593fffff,Delhi,0.003509,0.00,0,267,0.000000,0.000010,0.250000,0,...,0,0,0,0,0,0,0,NaN,27.570131,yes
2331,883da1d5b3fffff,Delhi,0.127471,0.00,0,267,0.000000,0.000003,0.061538,0,...,0,0,0,0,0,0,0,NaN,28.763842,yes
2332,883da1d5bbfffff,Delhi,0.048453,0.00,0,296,0.003594,0.000339,0.550000,0,...,0,0,0,0,0,0,0,NaN,27.895054,yes
2333,883da1d5d3fffff,Delhi,0.000226,0.00,0,265,0.005203,0.000097,0.400000,0,...,0,0,0,0,0,0,0,NaN,34.599591,yes

In [596]:
df_delhi.to_csv(r"D:\Sociometrik\rent prediction\rent_prediction_for_delhi.csv")

In [600]:
df_for_mumbai_pre=df_for_predict[df_for_predict['t_name']=='Mumbai']

In [601]:
df_for_mumbai_pre

,hexid08,t_name,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,auto_dealership,...,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,rent,predicted
2852,88608b0101fffff,Mumbai,0.000000,0.99,0,5362,0.007692,0.000042,0.230159,0,...,1,0,1,0,0,0,0,0,40.785990,yes
2853,88608b010bfffff,Mumbai,0.000773,0.82,1,7216,0.013203,0.000073,0.474048,0,...,0,1,0,1,0,0,0,4,57.841197,yes
2854,88608b0129fffff,Mumbai,0.000129,6.93,3,8782,0.010189,0.000153,0.646259,1,...,0,1,1,90,0,0,0,2,72.336811,yes
2855,88608b012dfffff,Mumbai,0.000387,3.25,0,4557,0.014856,0.000030,0.235016,0,...,0,0,2,0,0,0,0,0,50.315603,yes
2856,88608b0143fffff,Mumbai,0.000129,0.00,0,4163,0.015160,0.000088,0.426941,0,...,0,2,0,0,0,0,0,0,38.253636,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3344,88608b5713fffff,Mumbai,0.000000,0.00,0,1343,0.000000,0.000000,0.250000,0,...,0,0,0,0,0,0,0,0,36.833427,yes
3345,88608b5717fffff,Mumbai,0.000000,0.00,0,1537,0.000000,0.000000,0.283505,0,...,0,0,0,0,0,0,0,0,37.186025,yes
3346,88608b571bfffff,Mumbai,0.000000,0.00,0,1314,0.000000,0.000000,0.261501,0,...,0,0,0,0,0,0,0,0,36.750962,yes
3347,88608b5733fffff,Mumbai,0.005655,0.00,0,4087,0.000000,0.000000,0.162651,0,...,0,0,0,0,0,0,0,0,39.881197,yes
3348,88608b5737fffff,Mumbai,0.000000,0.00,0,3699,0.000000,0.000000,0.285714,0,...,0,0,0,0,0,0,0,0,38.872460,yes

In [602]:
df_3_mumbai=df_3[df_3["t_name"]=="Mumbai"]

In [603]:
df_3_mumbai

,hexid08,t_name,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,auto_dealership,...,grocery_store,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price
1307,88608b0105fffff,Mumbai,0.001418,12.88,0,10673,0.008440,0.000130,0.610790,0,...,0,2,0,0,2,0,0,0,0,155.789474
1308,88608b0109fffff,Mumbai,0.041634,23.93,0,21790,0.014399,0.000210,0.605739,0,...,10,1,1,0,0,0,0,0,0,134.751773
1309,88608b010dfffff,Mumbai,0.017917,10.64,3,23393,0.024184,0.000380,0.783198,3,...,17,28,4,4,14,0,0,0,7,147.894507
1310,88608b0141fffff,Mumbai,0.000000,9.23,4,5610,0.002723,0.000013,0.509041,0,...,0,0,0,1,0,0,0,3,5,56.151420
1311,88608b0145fffff,Mumbai,0.000000,27.68,61,26313,0.033583,0.000417,0.617674,6,...,39,24,42,2,44,0,2,0,31,88.977703
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1590,88608b56c7fffff,Mumbai,0.000000,18.11,12,16409,0.173921,0.001050,0.693490,0,...,100,14,15,1,1,0,1,0,0,34.415584
1591,88608b56c9fffff,Mumbai,0.066669,4.96,23,14694,0.155824,0.001038,0.610657,1,...,70,8,6,0,1,0,0,4,1,26.323319
1592,88608b56d3fffff,Mumbai,0.324852,13.65,8,14044,0.035784,0.000860,0.271327,2,...,62,25,3,0,3,0,0,0,5,55.113651
1593,88608b56d9fffff,Mumbai,0.050066,5.18,0,14053,0.003383,0.000289,0.480423,0,...,11,0,1,0,0,0,0,0,0,30.379747
1594,88608b56ddfffff,Mumbai,0.010296,10.14,2,16058,0.118317,0.000744,0.554643,6,...,6,0,3,4,0,0,1,0,2,58.620690

In [604]:
df_mumbai=pd.concat([df_3_mumbai, df_for_mumbai_pre])

In [606]:
df_mumbai.to_csv(r"D:\Sociometrik\rent prediction\rent_prediction_for_mumbai.csv")

In [612]:
df_mumbai=df_mumbai.reset_index(drop=True)
df_mumbai

,hexid08,t_name,green_space_density,public_infrastructure_index,transportation_hubs,total_digital_consumers,pop_density_per_sqm,building_density_per_sqm,luxery_percentage,auto_dealership,...,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station,hotel,average_monthly_residential_rental_price,rent,predicted
0,88608b0105fffff,Mumbai,0.001418,12.88,0,10673,0.008440,0.000130,0.610790,0,...,0,0,2,0,0,0,0,155.789474,NaN,NaN
1,88608b0109fffff,Mumbai,0.041634,23.93,0,21790,0.014399,0.000210,0.605739,0,...,1,0,0,0,0,0,0,134.751773,NaN,NaN
2,88608b010dfffff,Mumbai,0.017917,10.64,3,23393,0.024184,0.000380,0.783198,3,...,4,4,14,0,0,0,7,147.894507,NaN,NaN
3,88608b0141fffff,Mumbai,0.000000,9.23,4,5610,0.002723,0.000013,0.509041,0,...,0,1,0,0,0,3,5,56.151420,NaN,NaN
4,88608b0145fffff,Mumbai,0.000000,27.68,61,26313,0.033583,0.000417,0.617674,6,...,42,2,44,0,2,0,31,88.977703,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
780,88608b5713fffff,Mumbai,0.000000,0.00,0,1343,0.000000,0.000000,0.250000,0,...,0,0,0,0,0,0,0,NaN,36.833427,yes
781,88608b5717fffff,Mumbai,0.000000,0.00,0,1537,0.000000,0.000000,0.283505,0,...,0,0,0,0,0,0,0,NaN,37.186025,yes
782,88608b571bfffff,Mumbai,0.000000,0.00,0,1314,0.000000,0.000000,0.261501,0,...,0,0,0,0,0,0,0,NaN,36.750962,yes
783,88608b5733fffff,Mumbai,0.005655,0.00,0,4087,0.000000,0.000000,0.162651,0,...,0,0,0,0,0,0,0,NaN,39.881197,yes
784,88608b5737fffff,Mumbai,0.000000,0.00,0,3699,0.000000,0.000000,0.285714,0,...,0,0,0,0,0,0,0,NaN,38.872460,yes

# TO find the affluence

In [168]:
df_rent=pd.read_csv(r"D:\Sociometrik\rent prediction\rent_prediction_v_1.csv")

In [169]:
df_rent

,hexid08,t_name,locality,count_locality_oneby one,count_locality_at_once,average_monthly_residential_rental_price,locality_rental_price,prediction,green_space_density,building_density_per_sqm,...,convenience_store,department_store,grocery_store,home_specialty_store,office_supply_services_store,petrol_gasoline_station,sporting_goods_store,airport,bus_station,train_station
0,8860145987fffff,Bengaluru,Aanchepalya Village,1,1,27.650000,27.650000,old,0.090000,0.001151,...,3,3,45,5,0,0,0,0,1,0
1,8861892a97fffff,Bengaluru,Aavalahalli,1,9,13.694000,13.694000,old,0.030000,0.000000,...,23,23,0,1,0,0,0,0,0,0
2,8861892f09fffff,Bengaluru,Aavalahalli,2,9,11.540000,13.694000,old,0.030000,0.000280,...,6,6,18,1,0,0,0,0,0,0
3,8861892f41fffff,Bengaluru,Aavalahalli,3,9,11.760000,13.694000,old,0.000000,0.000210,...,23,23,12,1,3,0,1,0,0,0
4,8861892f43fffff,Bengaluru,Aavalahalli,4,9,13.694000,13.694000,old,0.010000,0.000241,...,0,0,0,0,0,0,0,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5715,88608b0a19fffff,Mumbai,Worli,3,7,137.726293,111.436194,old,0.000000,0.000074,...,0,0,0,0,0,0,0,0,0,0
5716,88608b0a1dfffff,Mumbai,Worli,4,7,137.726293,111.436194,old,0.001547,0.000234,...,0,0,0,0,0,0,0,0,0,0
5717,88608b0a51fffff,Mumbai,Worli,5,7,111.436194,111.436194,old,0.012632,0.000150,...,0,0,0,0,0,0,0,0,0,0
5718,88608b0a53fffff,Mumbai,Worli,6,7,111.436194,111.436194,old,0.022815,0.000168,...,0,0,0,0,0,0,0,0,0,0
5719,88608b0a57fffff,Mumbai,Worli,7,7,129.282658,111.436194,old,0.002449,0.000295,...,0,0,0,0,0,0,0,0,0,0

In [170]:
df_expedi=pd.read_csv(r"C:\Users\chemi\Downloads\5cities_digital_expenditure (1).csv")

In [171]:
df_expedi

,hexid08,t_name,is_tc,consumer_digital_expenditure
0,883da10ac1fffff,Delhi,IND007094000001,59906
1,883da186e7fffff,Delhi,IND007094000001,12868
2,8861892633fffff,Bengaluru,IND029572803162,249130
3,883da118edfffff,Gurugram,IND006086800429,311167
4,883da11911fffff,Gurugram,IND006086800429,44669
...,...,...,...,...
6418,88618920d5fffff,Bengaluru,IND029572803162,30344
6419,883da112cdfffff,Delhi,IND007094000001,273179
6420,883da11433fffff,Delhi,IND007094000001,371831
6421,883da18eb5fffff,Delhi,IND007094000001,35561
6422,883cf2c555fffff,Kolkata,IND019342801742,66154

In [172]:
df_rent.columns

Index(['hexid08', 't_name', 'locality', 'count_locality_oneby one',
       'count_locality_at_once', 'average_monthly_residential_rental_price',
       'locality_rental_price', 'prediction', 'green_space_density',
       'building_density_per_sqm', 'government_office', 'museum', 'hotel',
       'green_space_score', 'building_density_per_sqm_', 'museum_score',
       'hotel_score', 'average_score', 'public_infrastructure_index',
       'transportation_hubs', 'total_digital_consumers', 'pop_density_per_sqm',
       'luxery_percentage', 'auto_dealership', 'auto_service_maintenance',
       'motorcycle_dealership', 'truck_dealership', 'higher_education',
       'library', 'amusement_park', 'bowling_centre', 'cinema', 'golf_course',
       'ice_skating_rink', 'nightlife', 'sports_centre', 'hospital',
       'industrial_zone', 'police_station', 'clothing_store',
       'consumer_electronics_store', 'convenience_store', 'department_store',
       'grocery_store', 'home_specialty_store', 'office_supply_services_store',
       'petrol_gasoline_station', 'sporting_goods_store', 'airport',
       'bus_station', 'train_station'],
      dtype='object')

In [173]:
df_rent=df_rent[["hexid08","t_name",'average_monthly_residential_rental_price']]

In [174]:
df_final=pd.merge(df_expedi, df_rent, how="left",on =['hexid08','t_name'])

In [175]:
df_locality_map=df[['hexid08','t_name','locality','luxery_percentage','green_space_density','pop_density_per_sqm']]

In [176]:
df_locality_map

,hexid08,t_name,locality,luxery_percentage,green_space_density,pop_density_per_sqm
0,883cf28945fffff,Kolkata,Sinthi,0.244236,0.086059,0.056038
1,883cf28949fffff,Kolkata,Baranagar,0.309732,0.169749,0.037358
2,883cf2894dfffff,Kolkata,Baranagar,0.469274,0.311278,0.030660
3,883cf28961fffff,Kolkata,Paikpara,0.341649,0.232866,0.028392
4,883cf28965fffff,Kolkata,Tala,0.277745,0.149823,0.029187
...,...,...,...,...,...,...
6418,88618935b9fffff,Bengaluru,Gulimangala,0.357143,0.070000,0.000576
6419,88618935bbfffff,Bengaluru,Gulimangala,0.250000,0.130000,0.000872
6420,88618935bdfffff,Bengaluru,Gulimangala,0.215470,0.180000,0.000934
6421,88618935d3fffff,Bengaluru,Bommasandra Village,0.409326,0.050000,0.005783
6422,88618935d7fffff,Bengaluru,Heelalige,0.379845,0.040000,0.003792

In [177]:
df_final=df_final.merge(df_locality_map,how="left",on=['hexid08','t_name'])

In [178]:
df_final

,hexid08,t_name,is_tc,consumer_digital_expenditure,average_monthly_residential_rental_price,locality,luxery_percentage,green_space_density,pop_density_per_sqm
0,883da10ac1fffff,Delhi,IND007094000001,59906,NaN,Mangar,NaN,0.537124,0.000000
1,883da186e7fffff,Delhi,IND007094000001,12868,34.350163,Rasoi,0.464545,0.091896,0.001532
2,8861892633fffff,Bengaluru,IND029572803162,249130,11.530000,Vittasandra,0.281501,0.090000,0.000322
3,883da118edfffff,Gurugram,IND006086800429,311167,38.450728,Sector 65,0.428571,0.050623,0.000142
4,883da11911fffff,Gurugram,IND006086800429,44669,6.862854,Tikli,0.116667,0.098748,0.000028
...,...,...,...,...,...,...,...,...,...
6418,88618920d5fffff,Bengaluru,IND029572803162,30344,21.240000,Gunjur,0.383954,0.140000,0.002097
6419,883da112cdfffff,Delhi,IND007094000001,273179,22.781740,Hastsal,0.558223,0.001583,0.043219
6420,883da11433fffff,Delhi,IND007094000001,371831,27.176520,Sant Nagar,0.250147,0.359884,0.002743
6421,883da18eb5fffff,Delhi,IND007094000001,35561,29.040996,Rohini,0.595533,0.190481,0.011990
6422,883cf2c555fffff,Kolkata,IND019342801742,66154,16.391225,Ganguli Bagan,0.187588,0.069278,0.024195

In [179]:
df_final=df_final[['hexid08','t_name','is_tc','locality','average_monthly_residential_rental_price','pop_density_per_sqm','luxery_percentage','green_space_density','consumer_digital_expenditure']]

In [180]:
df_final

,hexid08,t_name,is_tc,locality,average_monthly_residential_rental_price,pop_density_per_sqm,luxery_percentage,green_space_density,consumer_digital_expenditure
0,883da10ac1fffff,Delhi,IND007094000001,Mangar,NaN,0.000000,NaN,0.537124,59906
1,883da186e7fffff,Delhi,IND007094000001,Rasoi,34.350163,0.001532,0.464545,0.091896,12868
2,8861892633fffff,Bengaluru,IND029572803162,Vittasandra,11.530000,0.000322,0.281501,0.090000,249130
3,883da118edfffff,Gurugram,IND006086800429,Sector 65,38.450728,0.000142,0.428571,0.050623,311167
4,883da11911fffff,Gurugram,IND006086800429,Tikli,6.862854,0.000028,0.116667,0.098748,44669
...,...,...,...,...,...,...,...,...,...
6418,88618920d5fffff,Bengaluru,IND029572803162,Gunjur,21.240000,0.002097,0.383954,0.140000,30344
6419,883da112cdfffff,Delhi,IND007094000001,Hastsal,22.781740,0.043219,0.558223,0.001583,273179
6420,883da11433fffff,Delhi,IND007094000001,Sant Nagar,27.176520,0.002743,0.250147,0.359884,371831
6421,883da18eb5fffff,Delhi,IND007094000001,Rohini,29.040996,0.011990,0.595533,0.190481,35561
6422,883cf2c555fffff,Kolkata,IND019342801742,Ganguli Bagan,16.391225,0.024195,0.187588,0.069278,66154

In [181]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6423 entries, 0 to 6422
Data columns (total 9 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   hexid08                                   6423 non-null   object
 1   t_name                                    6423 non-null   object
 2   is_tc                                     6423 non-null   object
 3   locality                                  6423 non-null   object
 4   average_monthly_residential_rental_price  5700 non-null   float64
 5   pop_density_per_sqm                       6423 non-null   float64
 6   luxery_percentage                         5926 non-null   float64
 7   green_space_density                       6423 non-null   float64
 8   consumer_digital_expenditure              6423 non-null   int64
dtypes: float64(4), int64(1), object(4)
memory usage: 501.8+ KB

In [182]:
for i in df_final[df_final['pop_density_per_sqm']==0].index:
    df_final["average_monthly_residential_rental_price"][i]=0

C:\Users\chemi\AppData\Local\Temp\ipykernel_25836\1112406631.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final["average_monthly_residential_rental_price"][i]=0

In [183]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6423 entries, 0 to 6422
Data columns (total 9 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   hexid08                                   6423 non-null   object
 1   t_name                                    6423 non-null   object
 2   is_tc                                     6423 non-null   object
 3   locality                                  6423 non-null   object
 4   average_monthly_residential_rental_price  6403 non-null   float64
 5   pop_density_per_sqm                       6423 non-null   float64
 6   luxery_percentage                         5926 non-null   float64
 7   green_space_density                       6423 non-null   float64
 8   consumer_digital_expenditure              6423 non-null   int64
dtypes: float64(4), int64(1), object(4)
memory usage: 759.8+ KB

In [184]:
df_final.to_csv(r'D:\Sociometrik\rent prediction\afflunece_score_v2.csv')

In [204]:
df_aggr=pd.read_csv(r"D:\Sociometrik\rent prediction\afflunece_score_v2.csv")

In [205]:
df_aggr=df_aggr.drop(columns=['per_capita','average_monthly_residential_rental_price_score','green_space_density_score','luxery_percentage_score','per_capita_score','per_capita_score','average_score','affluence_score','remark'])

In [211]:
df_aggr

,hexid08,t_name,is_tc,locality,pop_count,consumer_digital_expenditure,average_monthly_residential_rental_price,luxery_percentage,green_space_density
0,8861892633fffff,Bengaluru,IND029572803162,Vittasandra,244,249130,11.530000,0.281501,0.090000
1,886189268dfffff,Bengaluru,IND029572803162,Hullahalli,550,247500,18.670000,0.187166,0.170000
2,88618926bdfffff,Bengaluru,IND029572803162,Basavanapura,1824,269843,12.220000,0.314010,0.250000
3,88618924adfffff,Bengaluru,IND029572803162,JP Nagar,17457,280713,19.300000,0.468432,0.100000
4,88601459cdfffff,Bengaluru,IND029572803162,Peenya,13214,1065668,15.930000,0.133036,0.040000
...,...,...,...,...,...,...,...,...,...
6418,88608b56e3fffff,Mumbai,IND027519000001,Vikhroli East,3884,93973,68.783321,0.282787,0.068986
6419,88608b090bfffff,Mumbai,IND027519000001,Juhu,10332,641785,108.000000,0.430618,0.005414
6420,88608b4555fffff,Mumbai,IND027519000001,Dahisar West,45770,28393,22.673043,0.680136,0.020009
6421,88608b4723fffff,Mumbai,IND027519000001,Sanjay Gandhi National Park,0,5412,0.000000,0.239264,0.156094
6422,88608b0a4bfffff,Mumbai,IND027519000001,Parel,27887,1001086,76.213018,0.524183,0.000129

In [218]:
df_aggr_loc=df_aggr.groupby(['t_name','is_tc','locality']).agg({'pop_count':'sum',"consumer_digital_expenditure":'sum',"average_monthly_residential_rental_price":'sum','luxery_percentage':'sum','green_space_density':'sum'}).reset_index()

In [220]:
df_aggr_loc.to_csv(r"D:\Sociometrik\rent prediction\afflunece_score_on_locality.csv")